// gpu/emit_wgsl.c — weftc-codegen backend: WGSL struct generator (target wgsl).
//
// For every verified struct this emitter produces <name>.wgsl containing:
//   * the storage-address-space struct (std430-equivalent) with explicit pad
//     members, BYTE-EXACT with the C/Rust host layout — queue.writeBuffer()
//     the host bytes straight into a storage buffer, no repacking (Pillar 1 §C)
//   * the uniform-address-space struct (std140-equivalent) when — and only
//     when — it is also byte-exact; otherwise a Law-4 refusal comment naming
//     the exact violating field and rule
//   * a total refusal (no struct at all) when the storage variant cannot
//     reproduce the host layout: a wrong layout is worse than none
// plus <name>_validate.wgsl — a generated compute shader that proves direct
// consumption by validating schema hashes GPU-side over a storage buffer.

#include "../weftc_codegen.h"
#include "gpu_layout.h"

// emit one struct definition from a computed layout
static void emit_wgsl_struct(strbuf* b, const char* name, const gpu_layout* L, const char* banner)
{
    wsb_printf(b, "// %s\n", banner);
    wsb_printf(b, "struct %s {\n", name);
    for (uint32_t m = 0; m < L->nmembers; m++) {
        const gpu_member* mb = &L->members[m];
        wsb_printf(b, "  %s: %s,%s        // @%u (%u)\n",
                   mb->name, mb->wgsl_type,
                   m + 1 == L->nmembers ? "" : " ",
                   mb->offset, mb->size);
    }
    wsb_printf(b, "}; // size %u, align %u\n\n", L->size, L->align);
}

// collect embedded struct deps (transitive closure) in topo order
static void collect_deps(const weft_struct* s, const weft_struct** deps, uint32_t* ndeps, uint32_t max)
{
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        weft_type_kind dep = (fl->kind == WT_ARRAY) ? fl->elem_kind : fl->kind;
        if (dep == WT_STRUCT) {
            collect_deps(fl->struct_type, deps, ndeps, max);
            bool seen = false;
            for (uint32_t k = 0; k < *ndeps; k++) {
                if (deps[k] == fl->struct_type) { seen = true; break; }
            }
            if (!seen && *ndeps < max) {
                deps[(*ndeps)++] = fl->struct_type;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// validate compute shader (storage-exact roots)
// ---------------------------------------------------------------------------

static void emit_wgsl_validate(const weft_ir* ir, const weft_struct* s, const gpu_layout* L,
                               const weft_emit_opts* o)
{
    strbuf b;
    wsb_init(&b);
    char sid[32];
    if (s->schema_width == 64) {
        snprintf(sid, sizeof(sid), "0x%016llXu", (unsigned long long)s->schema_id);
    } else {
        snprintf(sid, sizeof(sid), "0x%08Xu", (unsigned)s->schema_id);
    }

    wsb_printf(&b,
        "// %s_validate.wgsl — generated by weftc-codegen %s. DO NOT EDIT.\n"
        "// Direct-consumption proof: a compute shader reading an array of %s\n"
        "// straight out of a storage buffer (bytes written by C/Rust, no\n"
        "// repacking) and validating every schema hash GPU-side.\n"
        "//   binding 0: read-only storage — array<%s>\n"
        "//   binding 1: read_write storage — u32 triple [ok, bad_index+1, total]\n"
        "\n",
        s->name, WEFTC_CODEGEN_VERSION, s->rust_name, s->rust_name);
    if (L->uses_f16) {
        wsb_puts(&b, "enable f16;\n\n");
    }
    // closure
    const weft_struct* deps[64];
    uint32_t ndeps = 0;
    collect_deps(s, deps, &ndeps, 64);
    for (uint32_t d = 0; d < ndeps; d++) {
        gpu_layout dl;
        if (gpu_layout_compute(ir, deps[d], GPU_WGSL, GPU_STORAGE, &dl)) {
            char banner[160];
            snprintf(banner, sizeof(banner), "embedded type (storage rules) — byte-exact");
            emit_wgsl_struct(&b, deps[d]->rust_name, &dl, banner);
        }
    }
    emit_wgsl_struct(&b, s->rust_name, L, "address space: storage (std430-equivalent) — byte-exact");

    wsb_printf(&b,
        "@group(0) @binding(0) var<storage, read> frames_in: array<%s>;\n"
        "@group(0) @binding(1) var<storage, read_write> scan: array<u32>;\n"
        "\n"
        "@compute @workgroup_size(64)\n"
        "fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
        "  let i = gid.x;\n"
        "  let n = arrayLength(&frames_in);\n"
        "  if (i >= n) {\n"
        "    return;\n"
        "  }\n"
        "  atomicAdd(&scan[2], 1u);\n"
        "  if (frames_in[i].schema_id == %s) {\n"
        "    atomicAdd(&scan[0], 1u);\n"
        "  } else {\n"
        "    atomicExchange(&scan[1], i + 1u);\n"
        "  }\n"
        "}\n",
        s->rust_name, sid);

    char path[512];
    snprintf(path, sizeof(path), "%s/%s_validate.wgsl", o->out_dir, s->name);
    weft_write_file(path, &b);
    wsb_free(&b);
}

// ---------------------------------------------------------------------------
// entry
// ---------------------------------------------------------------------------

int weft_emit_wgsl(const weft_ir* ir, const weft_emit_opts* o)
{
    for (uint32_t k = 0; k < ir->nstructs; k++) {
        const weft_struct* s = &ir->ss[k];
        gpu_layout st, un;
        bool st_exact = gpu_layout_compute(ir, s, GPU_WGSL, GPU_STORAGE, &st);
        bool un_exact = gpu_layout_compute(ir, s, GPU_WGSL, GPU_UNIFORM, &un);
        (void)un_exact;

        strbuf b;
        wsb_init(&b);
        wsb_printf(&b,
            "// %s.wgsl — generated by weftc-codegen %s (target: wgsl). DO NOT EDIT.\n"
            "// module: %s | struct: %s",
            s->name, WEFTC_CODEGEN_VERSION, ir->module, s->name);
        if (s->root) {
            wsb_printf(&b, " | schema_id: %s", s->schema_id_str);
        }
        wsb_printf(&b, "\n// host layout: %u bytes, align %u\n", s->size, s->align);

        if (!st_exact) {
            wsb_printf(&b,
                "//\n"
                "// WEFT-GPU-NOT-EXACT: %s — storage variant WITHHELD (Law 4)\n"
                "// reason: %s\n"
                "// remediation: widen 8/16-bit integers to u32, replace bool with u32\n"
                "//   flags + bitfields, restructure f16-only layouts, or keep this struct\n"
                "//   host-side and project a GPU-exact mirror schema.\n"
                "// The refusal is total: no struct is emitted, because a struct with a\n"
                "// silently-wrong layout is worse than no struct.\n",
                s->name, st.reason);
            weft_warn("[wgsl] %s: storage variant withheld (Law 4) — %s", s->name, st.reason);
        } else {
            wsb_puts(&b,
                "// storage variant: BYTE-EXACT with the host struct — members sit at the\n"
                "// same offsets as the C/Rust projections; upload host bytes unchanged\n"
                "// via queue.writeBuffer() into a storage buffer. No host repacking.\n");
            if (!un_exact) {
                wsb_printf(&b, "// uniform variant: REFUSED (Law 4) — %s\n", un.reason);
            }
            wsb_puts(&b, "//\n");
            if (st.uses_f16) {
                wsb_puts(&b, "enable f16;\n//\n");
            }
            const weft_struct* deps[64];
            uint32_t ndeps = 0;
            collect_deps(s, deps, &ndeps, 64);
            for (uint32_t d = 0; d < ndeps; d++) {
                gpu_layout dl;
                if (gpu_layout_compute(ir, deps[d], GPU_WGSL, GPU_STORAGE, &dl)) {
                    emit_wgsl_struct(&b, deps[d]->rust_name, &dl, "embedded type (storage rules) — byte-exact");
                }
            }
            emit_wgsl_struct(&b, s->rust_name, &st, "address space: storage (std430-equivalent) — byte-exact");
            if (un_exact) {
                char uname[96];
                snprintf(uname, sizeof(uname), "%sUniform", s->rust_name);
                emit_wgsl_struct(&b, uname, &un, "address space: uniform (std140-equivalent) — byte-exact");
            }
        }

        char path[512];
        snprintf(path, sizeof(path), "%s/%s.wgsl", o->out_dir, s->name);
        weft_write_file(path, &b);
        wsb_free(&b);

        if (st_exact && s->root) {
            emit_wgsl_validate(ir, s, &st, o);
        }
    }
    return 0;
}
