// gpu/emit_glsl.c — weftc-codegen backend: GLSL (std140/std430) struct
// generator (target glsl).
//
// Emits <name>.glsl with:
//   * the std430 struct (Vulkan SSBO flavor) — BYTE-EXACT with the host
//     layout, explicit pads included, ready for `layout(std430)` blocks
//   * the std140 struct when it is also byte-exact (uniform blocks)
//   * total refusal (Law 4) with a precise reason otherwise
// and <name>_validate.comp — a complete, glslang-compilable compute shader
// proving direct consumption over an SSBO of host-written bytes.

#include "../weftc_codegen.h"
#include "gpu_layout.h"

static void emit_glsl_struct(strbuf* b, const char* name, const gpu_layout* L, const char* banner)
{
    wsb_printf(b, "// %s\n", banner);
    wsb_printf(b, "struct %s {\n", name);
    for (uint32_t m = 0; m < L->nmembers; m++) {
        const gpu_member* mb = &L->members[m];
        wsb_printf(b, "  %s %s;        // @%u (%u)\n",
                   mb->glsl_type, mb->name, mb->offset, mb->size);
    }
    wsb_printf(b, "}; // size %u, align %u\n\n", L->size, L->align);
}

static void collect_deps(const weft_struct* s, const weft_struct** deps, uint32_t* ndeps, uint32_t max)
{
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        weft_type_kind dep = (fl->kind == WT_ARRAY) ? fl->elem_kind : fl->kind;
        if (dep == WT_STRUCT) {
            collect_deps(fl->struct_type, deps, ndeps, max);
            bool seen = false;
            for (uint32_t k = 0; k < *ndeps; k++) {
                if (deps[k] == fl->struct_type) { seen = true; break; }
            }
            if (!seen && *ndeps < max) {
                deps[(*ndeps)++] = fl->struct_type;
            }
        }
    }
}

static void glsl_name(const weft_struct* s, char out[96])
{
    snprintf(out, 96, "Weft%s", s->rust_name);
}

static void emit_glsl_validate(const weft_ir* ir, const weft_struct* s, const gpu_layout* L,
                               const weft_emit_opts* o)
{
    strbuf b;
    wsb_init(&b);
    char sname[96], uname[96];
    glsl_name(s, sname);
    (void)uname;
    char sid[32];
    if (s->schema_width == 64) {
        snprintf(sid, sizeof(sid), "0x%016llXUL", (unsigned long long)s->schema_id);
    } else {
        snprintf(sid, sizeof(sid), "0x%08Xu", (unsigned)s->schema_id);
    }

    wsb_printf(&b,
        "#version 450\n"
        "// %s_validate.comp — generated by weftc-codegen %s. DO NOT EDIT.\n"
        "// Direct-consumption proof: a compute shader reading an SSBO of %s\n"
        "// (bytes written by C/Rust, no repacking) and validating every schema\n"
        "// hash GPU-side.  bindings: 0 = frames (std430, readonly), 1 = scan\n"
        "// u32 triple [ok, bad_index+1, total].\n",
        s->name, WEFTC_CODEGEN_VERSION, sname);
    if (L->uses_u64) {
        wsb_puts(&b, "#extension GL_ARB_gpu_shader_int64 : require\n");
    }
    if (L->uses_f64) {
        wsb_puts(&b, "#extension GL_ARB_gpu_shader_fp64 : require\n");
    }
    wsb_puts(&b, "layout(local_size_x = 64) in;\n\n");

    const weft_struct* deps[64];
    uint32_t ndeps = 0;
    collect_deps(s, deps, &ndeps, 64);
    for (uint32_t d = 0; d < ndeps; d++) {
        gpu_layout dl;
        if (gpu_layout_compute(ir, deps[d], GPU_GLSL, GPU_STORAGE, &dl)) {
            char dn[96];
            glsl_name(deps[d], dn);
            emit_glsl_struct(&b, dn, &dl, "embedded type (std430) — byte-exact");
        }
    }
    emit_glsl_struct(&b, sname, L, "std430 — byte-exact with the host struct");

    wsb_printf(&b,
        "layout(std430, binding = 0) readonly buffer FramesIn { %s frames_in[]; };\n"
        "layout(std430, binding = 1) buffer Scan { uint scan_out[]; };\n"
        "\n"
        "void main() {\n"
        "    uint i = gl_GlobalInvocationID.x;\n"
        "    if (i >= frames_in.length()) {\n"
        "        return;\n"
        "    }\n"
        "    atomicAdd(scan_out[2], 1u);\n"
        "    if (frames_in[i].schema_id == %s) {\n"
        "        atomicAdd(scan_out[0], 1u);\n"
        "    } else {\n"
        "        atomicExchange(scan_out[1], i + 1u);\n"
        "    }\n"
        "}\n",
        sname, sid);

    char path[512];
    snprintf(path, sizeof(path), "%s/%s_validate.comp", o->out_dir, s->name);
    weft_write_file(path, &b);
    wsb_free(&b);
}

int weft_emit_glsl(const weft_ir* ir, const weft_emit_opts* o)
{
    for (uint32_t k = 0; k < ir->nstructs; k++) {
        const weft_struct* s = &ir->ss[k];
        gpu_layout st, un;
        bool st_exact = gpu_layout_compute(ir, s, GPU_GLSL, GPU_STORAGE, &st);
        bool un_exact = gpu_layout_compute(ir, s, GPU_GLSL, GPU_UNIFORM, &un);

        strbuf b;
        wsb_init(&b);
        wsb_printf(&b,
            "// %s.glsl — generated by weftc-codegen %s (target: glsl). DO NOT EDIT.\n"
            "// module: %s | struct: %s",
            s->name, WEFTC_CODEGEN_VERSION, ir->module, s->name);
        if (s->root) {
            wsb_printf(&b, " | schema_id: %s", s->schema_id_str);
        }
        wsb_printf(&b, "\n// host layout: %u bytes, align %u\n", s->size, s->align);

        if (!st_exact) {
            wsb_printf(&b,
                "//\n"
                "// WEFT-GPU-NOT-EXACT: %s — std430 variant WITHHELD (Law 4)\n"
                "// reason: %s\n"
                "// remediation: widen 8/16-bit integers to u32, replace bool with u32\n"
                "//   flags + bitfields, or keep this struct host-side.\n"
                "// The refusal is total: no struct is emitted, because a struct with a\n"
                "// silently-wrong layout is worse than no struct.\n",
                s->name, st.reason);
            weft_warn("[glsl] %s: std430 variant withheld (Law 4) — %s", s->name, st.reason);
        } else {
            wsb_printf(&b,
                "// std430 variant: BYTE-EXACT with the host struct — members sit at the\n"
                "// same offsets as the C/Rust projections; fill an SSBO with host bytes\n"
                "// directly. No host repacking.\n");
            if (!un_exact) {
                wsb_printf(&b, "// std140 (uniform) variant: REFUSED (Law 4) — %s\n", un.reason);
            }
            wsb_puts(&b, "//\n");
            if (st.uses_u64) {
                wsb_puts(&b, "// requires: #extension GL_ARB_gpu_shader_int64 : require\n");
            }
            if (st.uses_f64) {
                wsb_puts(&b, "// requires: #extension GL_ARB_gpu_shader_fp64 : require\n");
            }
            wsb_puts(&b, "//\n");

            char sname[96], uname[96];
            glsl_name(s, sname);
            const weft_struct* deps[64];
            uint32_t ndeps = 0;
            collect_deps(s, deps, &ndeps, 64);
            for (uint32_t d = 0; d < ndeps; d++) {
                gpu_layout dl;
                if (gpu_layout_compute(ir, deps[d], GPU_GLSL, GPU_STORAGE, &dl)) {
                    char dn[96];
                    glsl_name(deps[d], dn);
                    emit_glsl_struct(&b, dn, &dl, "embedded type (std430) — byte-exact");
                }
            }
            emit_glsl_struct(&b, sname, &st, "std430 — byte-exact with the host struct");
            if (un_exact) {
                snprintf(uname, sizeof(uname), "Weft%sUniform", s->rust_name);
                emit_glsl_struct(&b, uname, &un, "std140 (uniform) — byte-exact");
            }
            wsb_printf(&b,
                "// usage (SSBO):\n"
                "//   layout(std430, binding = 0) readonly buffer FramesIn { %s frames[]; };\n",
                sname);
        }

        char path[512];
        snprintf(path, sizeof(path), "%s/%s.glsl", o->out_dir, s->name);
        weft_write_file(path, &b);
        wsb_free(&b);

        if (st_exact && s->root) {
            emit_glsl_validate(ir, s, &st, o);
        }
    }
    return 0;
}
