// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct ImuSample · 32 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/imu_sample.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over ImuSample — zero-allocation managed projection.
 * Header-less 32-byte lean payload: exercises the no-handshake validateHeader() path (bounds check only) and proves backends emit correct code when no const/role fields exist.
 *
 * Layout (little-endian):
 *
 *   0x00  u64  timestampNs
 *   0x08  f32[3]  accel
 *   0x14  f32[3]  gyro
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export class ImuSampleView {
  /** Struct size in bytes. */
  public static readonly BYTE_LENGTH: number = 32;
  /** @byteOffset 0 (u64) */
  public static readonly TIMESTAMP_NS_OFFSET: number = 0;
  /** @byteOffset 8 (f32[3]) */
  public static readonly ACCEL_OFFSET: number = 8;
  /** @byteOffset 20 (f32[3]) */
  public static readonly GYRO_OFFSET: number = 20;

  private _view!: DataView;
  private _byteOffset: number = 0;
  private _bound: boolean = false;

  /** Absolute byte offset this view is bound at (after window resolution). */
  public get byteOffset(): number { return this._byteOffset; }

  /** True once bound; getters require it. */
  public get isBound(): boolean { return this._bound; }

  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset: number = 0): this {
    // COLD PATH — one DataView per bind; hot frames never allocate (Law 1).
    // Accepts raw ArrayBuffer/SharedArrayBuffer, or any TypedArray/DataView/
    // Node Buffer window (its .buffer + .byteOffset are honored exactly).
    const maybeView = buffer as ArrayBufferView;
    let base;
    let baseOffset;
    let baseLen;
    if (typeof maybeView.byteOffset === "number" && typeof maybeView.byteLength === "number" && typeof maybeView.buffer !== "undefined") {
      base = maybeView.buffer;
      baseOffset = maybeView.byteOffset;
      baseLen = maybeView.byteLength;
    } else {
      base = buffer as ArrayBufferLike;
      baseOffset = 0;
      baseLen = base.byteLength;
    }
    if (typeof byteOffset !== "number" || !Number.isSafeInteger(byteOffset) || byteOffset < 0 || byteOffset + ImuSampleView.BYTE_LENGTH > baseLen) {
      throw new RangeError("ImuSampleView.bind: window [" + byteOffset + ".." + (byteOffset + ImuSampleView.BYTE_LENGTH) + ") exceeds buffer of " + baseLen + " bytes");
    }
    this._view = new DataView(base, baseOffset + byteOffset, ImuSampleView.BYTE_LENGTH);
    this._byteOffset = baseOffset + byteOffset;
    this._bound = true;
    return this;
  }

  public validateHeader(avail?: number): boolean {
    if (!this._bound) { return false; }
    return true;
  }

  /**
   * Monotonic hardware timestamp, nanoseconds.
   * @byteOffset 0x00 (u64)
   */
  public get timestampNs(): bigint {
    return this._view.getBigUint64(0, true);
  }
  public set timestampNs(value: bigint) {
    this._view.setBigUint64(0, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withTimestampNs(value: bigint): this {
    this.timestampNs = value;
    return this;
  }
  /** Low 32 bits of timestampNs @0x0 (u32 LE) — primitive-only path. */
  public get timestampNsLo(): number { return this._view.getUint32(0, true); }
  public set timestampNsLo(value: number) { this._view.setUint32(0, value, true); }
  /** High 32 bits of timestampNs @0x4 (u32 LE) — primitive-only path. */
  public get timestampNsHi(): number { return this._view.getUint32(4, true); }
  public set timestampNsHi(value: number) { this._view.setUint32(4, value, true); }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withTimestampNsLo(value: number): this {
    this._view.setUint32(0, value, true);
    return this;
  }
  public withTimestampNsHi(value: number): this {
    this._view.setUint32(4, value, true);
    return this;
  }

  /**
   * Linear acceleration, g.
   * @byteOffset 0x08 (f32[3], element stride 4)
   */
  public getAccelAt(index: number): number {
    return this._view.getFloat32(8 + index * 4, true);
  }
  public setAccelAt(index: number, value: number): void {
    this._view.setFloat32(8 + index * 4, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withAccelAt(index: number, value: number): this {
    this.setAccelAt(index, value);
    return this;
  }

  /**
   * Angular rate, rad/s.
   * @byteOffset 0x14 (f32[3], element stride 4)
   */
  public getGyroAt(index: number): number {
    return this._view.getFloat32(20 + index * 4, true);
  }
  public setGyroAt(index: number, value: number): void {
    this._view.setFloat32(20 + index * 4, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withGyroAt(index: number, value: number): this {
    this.setGyroAt(index, value);
    return this;
  }
}
