// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct ImuSample · 32 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/imu_sample.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over ImuSample — zero-allocation managed projection.
 * Header-less 32-byte lean payload: exercises the no-handshake validateHeader() path (bounds check only) and proves backends emit correct code when no const/role fields exist.
 *
 * Layout (little-endian):
 *
 *   0x00  u64  timestampNs
 *   0x08  f32[3]  accel
 *   0x14  f32[3]  gyro
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export declare class ImuSampleView {
  public static readonly BYTE_LENGTH: number;
  /** @byteOffset 0x00 (u64) */
  public static readonly TIMESTAMP_NS_OFFSET: number;
  /** @byteOffset 0x08 (f32[3]) */
  public static readonly ACCEL_OFFSET: number;
  /** @byteOffset 0x14 (f32[3]) */
  public static readonly GYRO_OFFSET: number;
  public get byteOffset(): number;
  public get isBound(): boolean;
  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset?: number): this;
  public validateHeader(avail?: number): boolean;
  public get timestampNs(): bigint;
  public set timestampNs(value: bigint);
  public withTimestampNs(value: bigint): this;
  public get timestampNsLo(): number;
  public set timestampNsLo(value: number);
  public get timestampNsHi(): number;
  public set timestampNsHi(value: number);
  public getAccelAt(index: number): number;
  public setAccelAt(index: number, value: number): void;
  public withAccelAt(index: number, value: number): this;
  public getGyroAt(index: number): number;
  public setGyroAt(index: number, value: number): void;
  public withGyroAt(index: number, value: number): this;
}
