// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct index · 0 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/imu_sample.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

export { ImuSampleView } from './imu-sample-view.js';
export { TelemetryFrameView } from './telemetry-frame-view.js';
export { WeftEnvelopeView } from './weft-envelope-view.js';
