// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/telemetry_frame.json (irVersion 1) · struct TelemetryFrame · 64 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/telemetry_frame.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over TelemetryFrame — zero-allocation managed projection.
 * Canonical 64-byte payload schema used across all managed backends for parity fixtures. Designed as the payload of a triad-1 envelope (bind at envelope.headerSize). Every numeric field is naturally aligned; all values in golden fixtures are exactly representable (dyadic) so cross-language comparisons are bit-exact.
 *
 * Layout (little-endian):
 *
 *   0x00  u64  schemaId  (const 10325646877637410834)  <schemaId>
 *   0x08  u64  timestampNs
 *   0x10  f32[3]  velocity
 *   0x1c  f32  pressurePa
 *   0x20  u8  state
 *   0x21  u8[3]  reserved  <reserved>
 *   0x28  f64[2]  gpsCoordinates
 *   0x38  u8[8]  payloadHash
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export class TelemetryFrameView {
  /** Struct size in bytes. */
  public static readonly BYTE_LENGTH: number = 64;
  /** Payload schema handshake (Law 4). */
  public static readonly SCHEMA_ID: bigint = 0x8f4c1120a9b30012n;
  public static readonly SCHEMA_VERSION: number = 3;
  /** @byteOffset 0 (u64) */
  public static readonly SCHEMA_ID_OFFSET: number = 0;
  /** @byteOffset 8 (u64) */
  public static readonly TIMESTAMP_NS_OFFSET: number = 8;
  /** @byteOffset 16 (f32[3]) */
  public static readonly VELOCITY_OFFSET: number = 16;
  /** @byteOffset 28 (f32) */
  public static readonly PRESSURE_PA_OFFSET: number = 28;
  /** @byteOffset 32 (u8) */
  public static readonly STATE_OFFSET: number = 32;
  /** @byteOffset 33 (u8[3]) */
  public static readonly RESERVED_OFFSET: number = 33;
  /** @byteOffset 40 (f64[2]) */
  public static readonly GPS_COORDINATES_OFFSET: number = 40;
  /** @byteOffset 56 (u8[8]) */
  public static readonly PAYLOAD_HASH_OFFSET: number = 56;

  private _view!: DataView;
  private _byteOffset: number = 0;
  private _bound: boolean = false;

  /** Absolute byte offset this view is bound at (after window resolution). */
  public get byteOffset(): number { return this._byteOffset; }

  /** True once bound; getters require it. */
  public get isBound(): boolean { return this._bound; }

  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset: number = 0): this {
    // COLD PATH — one DataView per bind; hot frames never allocate (Law 1).
    // Accepts raw ArrayBuffer/SharedArrayBuffer, or any TypedArray/DataView/
    // Node Buffer window (its .buffer + .byteOffset are honored exactly).
    const maybeView = buffer as ArrayBufferView;
    let base;
    let baseOffset;
    let baseLen;
    if (typeof maybeView.byteOffset === "number" && typeof maybeView.byteLength === "number" && typeof maybeView.buffer !== "undefined") {
      base = maybeView.buffer;
      baseOffset = maybeView.byteOffset;
      baseLen = maybeView.byteLength;
    } else {
      base = buffer as ArrayBufferLike;
      baseOffset = 0;
      baseLen = base.byteLength;
    }
    if (typeof byteOffset !== "number" || !Number.isSafeInteger(byteOffset) || byteOffset < 0 || byteOffset + TelemetryFrameView.BYTE_LENGTH > baseLen) {
      throw new RangeError("TelemetryFrameView.bind: window [" + byteOffset + ".." + (byteOffset + TelemetryFrameView.BYTE_LENGTH) + ") exceeds buffer of " + baseLen + " bytes");
    }
    this._view = new DataView(base, baseOffset + byteOffset, TelemetryFrameView.BYTE_LENGTH);
    this._byteOffset = baseOffset + byteOffset;
    this._bound = true;
    return this;
  }

  public validateHeader(avail?: number): boolean {
    if (!this._bound) { return false; }
    if (this._view.getBigUint64(0, true) !== TelemetryFrameView.SCHEMA_ID) { return false; }
    return true;
  }

  /**
   * Payload schema handshake; checked by validateHeader() before any field read (Law 4).
   * @byteOffset 0x00 (u64)
   * @const validated by validateHeader() (Law 4)
   */
  public get schemaId(): bigint {
    return this._view.getBigUint64(0, true);
  }
  /** Low 32 bits of schemaId @0x0 (u32 LE) — primitive-only path. */
  public get schemaIdLo(): number { return this._view.getUint32(0, true); }
  /** High 32 bits of schemaId @0x4 (u32 LE) — primitive-only path. */
  public get schemaIdHi(): number { return this._view.getUint32(4, true); }

  /**
   * Monotonic hardware timestamp, nanoseconds.
   * @byteOffset 0x08 (u64)
   */
  public get timestampNs(): bigint {
    return this._view.getBigUint64(8, true);
  }
  public set timestampNs(value: bigint) {
    this._view.setBigUint64(8, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withTimestampNs(value: bigint): this {
    this.timestampNs = value;
    return this;
  }
  /** Low 32 bits of timestampNs @0x8 (u32 LE) — primitive-only path. */
  public get timestampNsLo(): number { return this._view.getUint32(8, true); }
  public set timestampNsLo(value: number) { this._view.setUint32(8, value, true); }
  /** High 32 bits of timestampNs @0xc (u32 LE) — primitive-only path. */
  public get timestampNsHi(): number { return this._view.getUint32(12, true); }
  public set timestampNsHi(value: number) { this._view.setUint32(12, value, true); }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withTimestampNsLo(value: number): this {
    this._view.setUint32(8, value, true);
    return this;
  }
  public withTimestampNsHi(value: number): this {
    this._view.setUint32(12, value, true);
    return this;
  }

  /**
   * Velocity vector, m/s. Maps to SIMD3<Float> / vector_float3 on Apple platforms.
   * @byteOffset 0x10 (f32[3], element stride 4)
   */
  public getVelocityAt(index: number): number {
    return this._view.getFloat32(16 + index * 4, true);
  }
  public setVelocityAt(index: number, value: number): void {
    this._view.setFloat32(16 + index * 4, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withVelocityAt(index: number, value: number): this {
    this.setVelocityAt(index, value);
    return this;
  }

  /**
   * Ambient pressure, Pa.
   * @byteOffset 0x1c (f32)
   */
  public get pressurePa(): number {
    return this._view.getFloat32(28, true);
  }
  public set pressurePa(value: number) {
    this._view.setFloat32(28, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withPressurePa(value: number): this {
    this.pressurePa = value;
    return this;
  }

  /**
   * Device state enum byte.
   * @byteOffset 0x20 (u8)
   */
  public get state(): number {
    return this._view.getUint8(32);
  }
  public set state(value: number) {
    this._view.setUint8(32, value);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withState(value: number): this {
    this.state = value;
    return this;
  }

  /**
   * lat/lon pair, degrees.
   * @byteOffset 0x28 (f64[2], element stride 8)
   */
  public getGpsCoordinatesAt(index: number): number {
    return this._view.getFloat64(40 + index * 8, true);
  }
  public setGpsCoordinatesAt(index: number, value: number): void {
    this._view.setFloat64(40 + index * 8, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withGpsCoordinatesAt(index: number, value: number): this {
    this.setGpsCoordinatesAt(index, value);
    return this;
  }

  /**
   * Truncated payload digest (u8[8]).
   * @byteOffset 0x38 (u8[8], element stride 1)
   */
  public getPayloadHashAt(index: number): number {
    return this._view.getUint8(56 + index * 1);
  }
  public setPayloadHashAt(index: number, value: number): void {
    this._view.setUint8(56 + index * 1, value);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withPayloadHashAt(index: number, value: number): this {
    this.setPayloadHashAt(index, value);
    return this;
  }
}
