// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/telemetry_frame.json (irVersion 1) · struct TelemetryFrame · 64 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/telemetry_frame.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over TelemetryFrame — zero-allocation managed projection.
 * Canonical 64-byte payload schema used across all managed backends for parity fixtures. Designed as the payload of a triad-1 envelope (bind at envelope.headerSize). Every numeric field is naturally aligned; all values in golden fixtures are exactly representable (dyadic) so cross-language comparisons are bit-exact.
 *
 * Layout (little-endian):
 *
 *   0x00  u64  schemaId  (const 10325646877637410834)  <schemaId>
 *   0x08  u64  timestampNs
 *   0x10  f32[3]  velocity
 *   0x1c  f32  pressurePa
 *   0x20  u8  state
 *   0x21  u8[3]  reserved  <reserved>
 *   0x28  f64[2]  gpsCoordinates
 *   0x38  u8[8]  payloadHash
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export declare class TelemetryFrameView {
  public static readonly BYTE_LENGTH: number;
  public static readonly SCHEMA_ID: bigint;
  public static readonly SCHEMA_VERSION: number;
  /** @byteOffset 0x00 (u64) */
  public static readonly SCHEMA_ID_OFFSET: number;
  /** @byteOffset 0x08 (u64) */
  public static readonly TIMESTAMP_NS_OFFSET: number;
  /** @byteOffset 0x10 (f32[3]) */
  public static readonly VELOCITY_OFFSET: number;
  /** @byteOffset 0x1c (f32) */
  public static readonly PRESSURE_PA_OFFSET: number;
  /** @byteOffset 0x20 (u8) */
  public static readonly STATE_OFFSET: number;
  /** @byteOffset 0x21 (u8[3]) */
  public static readonly RESERVED_OFFSET: number;
  /** @byteOffset 0x28 (f64[2]) */
  public static readonly GPS_COORDINATES_OFFSET: number;
  /** @byteOffset 0x38 (u8[8]) */
  public static readonly PAYLOAD_HASH_OFFSET: number;
  public get byteOffset(): number;
  public get isBound(): boolean;
  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset?: number): this;
  public validateHeader(avail?: number): boolean;
  public get schemaId(): bigint;
  public get schemaIdLo(): number;
  public get schemaIdHi(): number;
  public get timestampNs(): bigint;
  public set timestampNs(value: bigint);
  public withTimestampNs(value: bigint): this;
  public get timestampNsLo(): number;
  public set timestampNsLo(value: number);
  public get timestampNsHi(): number;
  public set timestampNsHi(value: number);
  public getVelocityAt(index: number): number;
  public setVelocityAt(index: number, value: number): void;
  public withVelocityAt(index: number, value: number): this;
  public get pressurePa(): number;
  public set pressurePa(value: number);
  public withPressurePa(value: number): this;
  public get state(): number;
  public set state(value: number);
  public withState(value: number): this;
  public getGpsCoordinatesAt(index: number): number;
  public setGpsCoordinatesAt(index: number, value: number): void;
  public withGpsCoordinatesAt(index: number, value: number): this;
  public getPayloadHashAt(index: number): number;
  public setPayloadHashAt(index: number, value: number): void;
  public withPayloadHashAt(index: number, value: number): this;
}
