// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/weft_envelope.json (irVersion 1) · struct WeftEnvelope · 16 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/weft_envelope.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over WeftEnvelope — zero-allocation managed projection.
 * The triad-1 wire envelope per docs 03-ENVELOPE and core/c/weft.h. Byte-layout and validation semantics are normative: [0..4) magic 'WEFT', [4..6) version u16, [6..8) header_size u16, [8..12) seq u32, [12..16) payload_len u32. validateHeader() mirrors weft_envelope_decode() as a non-throwing boolean handshake (Law 4).
 *
 * Layout (little-endian):
 *
 *   0x00  u8[4]  magic  (const "WEFT")  <magic>
 *   0x04  u16  version  (const 1)  <schemaVersion>
 *   0x06  u16  headerSize  (const 16)  <headerSize>
 *   0x08  u32  seq  <seq>
 *   0x0c  u32  payloadLen  <payloadLen>
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export class WeftEnvelopeView {
  /** Struct size in bytes. */
  public static readonly BYTE_LENGTH: number = 16;
  public static readonly SCHEMA_VERSION: number = 1;
  /** Normative triad-1 minimum header size (03-ENVELOPE §2). */
  public static readonly MIN_HEADER_SIZE: number = 16;
  /** @byteOffset 0 (u8[4]) */
  public static readonly MAGIC_OFFSET: number = 0;
  /** @byteOffset 4 (u16) */
  public static readonly VERSION_OFFSET: number = 4;
  /** @byteOffset 6 (u16) */
  public static readonly HEADER_SIZE_OFFSET: number = 6;
  /** @byteOffset 8 (u32) */
  public static readonly SEQ_OFFSET: number = 8;
  /** @byteOffset 12 (u32) */
  public static readonly PAYLOAD_LEN_OFFSET: number = 12;

  private _view!: DataView;
  private _byteOffset: number = 0;
  private _bound: boolean = false;

  /** Absolute byte offset this view is bound at (after window resolution). */
  public get byteOffset(): number { return this._byteOffset; }

  /** True once bound; getters require it. */
  public get isBound(): boolean { return this._bound; }

  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset: number = 0): this {
    // COLD PATH — one DataView per bind; hot frames never allocate (Law 1).
    // Accepts raw ArrayBuffer/SharedArrayBuffer, or any TypedArray/DataView/
    // Node Buffer window (its .buffer + .byteOffset are honored exactly).
    const maybeView = buffer as ArrayBufferView;
    let base;
    let baseOffset;
    let baseLen;
    if (typeof maybeView.byteOffset === "number" && typeof maybeView.byteLength === "number" && typeof maybeView.buffer !== "undefined") {
      base = maybeView.buffer;
      baseOffset = maybeView.byteOffset;
      baseLen = maybeView.byteLength;
    } else {
      base = buffer as ArrayBufferLike;
      baseOffset = 0;
      baseLen = base.byteLength;
    }
    if (typeof byteOffset !== "number" || !Number.isSafeInteger(byteOffset) || byteOffset < 0 || byteOffset + WeftEnvelopeView.BYTE_LENGTH > baseLen) {
      throw new RangeError("WeftEnvelopeView.bind: window [" + byteOffset + ".." + (byteOffset + WeftEnvelopeView.BYTE_LENGTH) + ") exceeds buffer of " + baseLen + " bytes");
    }
    this._view = new DataView(base, baseOffset + byteOffset, WeftEnvelopeView.BYTE_LENGTH);
    this._byteOffset = baseOffset + byteOffset;
    this._bound = true;
    return this;
  }

  public validateHeader(avail?: number): boolean {
    if (!this._bound) { return false; }
    if (this._view.getUint8(0) !== 87) { return false; } // "W"
    if (this._view.getUint8(1) !== 69) { return false; } // "E"
    if (this._view.getUint8(2) !== 70) { return false; } // "F"
    if (this._view.getUint8(3) !== 84) { return false; } // "T"
    if (this._view.getUint16(4, true) !== 1) { return false; }
    if (this._view.getUint16(6, true) !== 16) { return false; }
    if (avail !== undefined) {
      const hs = this._view.getUint16(6, true);
      const pl = this._view.getUint32(12, true);
      if (hs < WeftEnvelopeView.MIN_HEADER_SIZE || hs > avail) { return false; }
      if (pl > avail - hs) { return false; } // payload bytes must exist (kernel SHORT)
    }
    return true;
  }

  /**
   * ASCII 'WEFT' frame magic.
   * @byteOffset 0x00 (u8[4], element stride 1)
   * @const validated by validateHeader() (Law 4)
   */
  public getMagicAt(index: number): number {
    return this._view.getUint8(0 + index * 1);
  }

  /**
   * Envelope wire version (triad-1 = 1).
   * @byteOffset 0x04 (u16)
   * @const validated by validateHeader() (Law 4)
   */
  public get version(): number {
    return this._view.getUint16(4, true);
  }

  /**
   * Total header size; payload begins at this offset, NEVER at 16 (L8b extensible headers).
   * @byteOffset 0x06 (u16)
   * @const validated by validateHeader() (Law 4)
   */
  public get headerSize(): number {
    return this._view.getUint16(6, true);
  }

  /**
   * Monotonic frame sequence number; mirrors the buffer canary.
   * @byteOffset 0x08 (u32)
   */
  public get seq(): number {
    return this._view.getUint32(8, true);
  }
  public set seq(value: number) {
    this._view.setUint32(8, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withSeq(value: number): this {
    this.seq = value;
    return this;
  }

  /**
   * Payload byte length starting at headerSize.
   * @byteOffset 0x0c (u32)
   */
  public get payloadLen(): number {
    return this._view.getUint32(12, true);
  }
  public set payloadLen(value: number) {
    this._view.setUint32(12, value, true);
  }
  /** Fluent mutator — returns this, allocates nothing (Law 1). */
  public withPayloadLen(value: number): this {
    this.payloadLen = value;
    return this;
  }
}
