// AUTO-GENERATED by weftc-managed/1.0.0 (ts) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/weft_envelope.json (irVersion 1) · struct WeftEnvelope · 16 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/weft_envelope.json --target ts
// Layout is normative; hand edits will be overwritten and drift will fail CI.

/**
 * Flyweight view over WeftEnvelope — zero-allocation managed projection.
 * The triad-1 wire envelope per docs 03-ENVELOPE and core/c/weft.h. Byte-layout and validation semantics are normative: [0..4) magic 'WEFT', [4..6) version u16, [6..8) header_size u16, [8..12) seq u32, [12..16) payload_len u32. validateHeader() mirrors weft_envelope_decode() as a non-throwing boolean handshake (Law 4).
 *
 * Layout (little-endian):
 *
 *   0x00  u8[4]  magic  (const "WEFT")  <magic>
 *   0x04  u16  version  (const 1)  <schemaVersion>
 *   0x06  u16  headerSize  (const 16)  <headerSize>
 *   0x08  u32  seq  <seq>
 *   0x0c  u32  payloadLen  <payloadLen>
 *
 * Steady-state reads and writes allocate nothing (Law 1): instantiate once,
 * then .bind(buffer, offset) for every frame. All multi-byte access is
 * explicitly little-endian (Law 2) and bit-exact with C/Rust/GPU buffers.
 * Runs on Node.js, Deno, Bun and browsers over ArrayBuffer |
 * SharedArrayBuffer | TypedArray windows (Law 3).
 */
export declare class WeftEnvelopeView {
  public static readonly BYTE_LENGTH: number;
  public static readonly SCHEMA_VERSION: number;
  public static readonly MIN_HEADER_SIZE: number;
  /** @byteOffset 0x00 (u8[4]) */
  public static readonly MAGIC_OFFSET: number;
  /** @byteOffset 0x04 (u16) */
  public static readonly VERSION_OFFSET: number;
  /** @byteOffset 0x06 (u16) */
  public static readonly HEADER_SIZE_OFFSET: number;
  /** @byteOffset 0x08 (u32) */
  public static readonly SEQ_OFFSET: number;
  /** @byteOffset 0x0c (u32) */
  public static readonly PAYLOAD_LEN_OFFSET: number;
  public get byteOffset(): number;
  public get isBound(): boolean;
  public bind(buffer: ArrayBufferLike | ArrayBufferView, byteOffset?: number): this;
  public validateHeader(avail?: number): boolean;
  public getMagicAt(index: number): number;
  public get version(): number;
  public get headerSize(): number;
  public get seq(): number;
  public set seq(value: number);
  public withSeq(value: number): this;
  public get payloadLen(): number;
  public set payloadLen(value: number);
  public withPayloadLen(value: number): this;
}
