/* weftc C golden-buffer verifier — kernel-grounded integration harness.
 *
 * Links against the FROZEN kernel (core/c/weft.c) and proves that the
 * Python-generated golden buffers are byte-identical to what the C world
 * view of the wire produces:
 *
 *   1. weft_envelope.bin  — must equal weft_envelope_encode_v1(0xBEEF, 64)
 *                           (the kernel's own triad-1 encoder)
 *   2. telemetry_frame.bin — field-by-field byte assertions at IR offsets
 *   3. imu_sample.bin      — field-by-field byte assertions at IR offsets
 *   4. weft_frame_stack.bin — envelope + payload + canary u64 LE = seq
 *
 * Exit 0 = all assertions hold; any mismatch exits nonzero with a diff.
 * This is the "buffers generated by the C harness" leg of the managed
 * codegen integration contract (Pillar 1 §5.3).
 *
 * Build: cc -std=c11 -I core/c -o /tmp/weftc_verify \
 *            tools/weftc/tests/harness/verify_golden.c core/c/weft.c
 * Run:   /tmp/weftc_verify tools/weftc/tests/golden
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Kernel surface (frozen; we only LINK, never modify) */
#include "weft.h"

static int failures = 0;

static void check(int cond, const char* what) {
    if (!cond) {
        fprintf(stderr, "FAIL: %s\n", what);
        failures++;
    }
}

static uint8_t* slurp(const char* dir, const char* name, size_t* len) {
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "FAIL: cannot open %s\n", path); failures++; return NULL; }
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* buf = malloc((size_t)n);
    if (!buf || fread(buf, 1, (size_t)n, f) != (size_t)n) {
        fprintf(stderr, "FAIL: short read %s\n", path);
        failures++; free(buf); fclose(f); return NULL;
    }
    fclose(f);
    *len = (size_t)n;
    return buf;
}

/* LE readers mirroring exactly what the managed backends emit */
static uint64_t rd_u64(const uint8_t* p) {
    return (uint64_t)p[0] | ((uint64_t)p[1] << 8) | ((uint64_t)p[2] << 16) |
           ((uint64_t)p[3] << 24) | ((uint64_t)p[4] << 32) | ((uint64_t)p[5] << 40) |
           ((uint64_t)p[6] << 48) | ((uint64_t)p[7] << 56);
}
static uint32_t rd_u32(const uint8_t* p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static uint16_t rd_u16(const uint8_t* p) { return (uint16_t)((uint32_t)p[0] | ((uint32_t)p[1] << 8)); }
static float rd_f32(const uint8_t* p) { uint32_t u = rd_u32(p); float f; memcpy(&f, &u, 4); return f; }
static double rd_f64(const uint8_t* p) { uint64_t u = rd_u64(p); double d; memcpy(&d, &u, 8); return d; }

int main(int argc, char** argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s <golden-dir>\n", argv[0]);
        return 2;
    }
    const char* dir = argv[1];
    size_t n;

    /* ---- 1. envelope vs the kernel's own encoder ---- */
    uint8_t kernel_env[16];
    weft_envelope_encode_v1(kernel_env, 0x0000BEEFu, 64);
    size_t env_len;
    uint8_t* env = slurp(dir, "weft_envelope.bin", &env_len);
    check(env && env_len == 16, "envelope is 16 bytes");
    if (env) {
        check(memcmp(env, kernel_env, 16) == 0, "envelope bytes == weft_envelope_encode_v1 output");
        check(memcmp(env, "WEFT", 4) == 0, "envelope magic");
        check(rd_u16(env + 4) == 1, "envelope version == 1");
        check(rd_u16(env + 6) == 16, "envelope headerSize == 16");
        check(rd_u32(env + 8) == 0x0000BEEFu, "envelope seq == 0xBEEF");
        check(rd_u32(env + 12) == 64, "envelope payloadLen == 64");
    }

    /* kernel decode contract (Law 4 handshake parity):
     * a BARE envelope advertises payload_len=64 but carries no payload bytes,
     * so weft_envelope_decode MUST return WEFT_DECODE_SHORT (avail-hs = 0 < 64).
     * Generated validateHeader() implementations mirror this exact semantics. */
    if (env) {
        uint16_t v = 0, hs = 0; uint32_t sq = 0, pl = 0;
        check(weft_envelope_decode(env, 16, &v, &hs, &sq, &pl) == WEFT_DECODE_SHORT,
              "bare envelope decodes SHORT (payload bytes absent) — kernel contract");
    }

    /* ---- 2. telemetry frame ---- */
    static const uint8_t want_hash[8] = {0xDE,0xAD,0xBE,0xEF,0xCA,0xFE,0xBA,0xBE};
    size_t tel_len;
    uint8_t* tel = slurp(dir, "telemetry_frame.bin", &tel_len);
    check(tel && tel_len == 64, "telemetry frame is 64 bytes");
    if (tel) {
        check(rd_u64(tel + 0) == 0x8F4C1120A9B30012ull, "telemetry schemaId @0");
        check(rd_u64(tel + 8) == 1737504000123456789ull, "telemetry timestampNs @8");
        check(rd_f32(tel + 16) == 1.5f, "telemetry velocity[0] @16");
        check(rd_f32(tel + 20) == -2.25f, "telemetry velocity[1] @20");
        check(rd_f32(tel + 24) == 4000.125f, "telemetry velocity[2] @24");
        check(rd_f32(tel + 28) == 1013.25f, "telemetry pressurePa @28");
        check(tel[32] == 7, "telemetry state @32");
        check(tel[33] == 0 && tel[34] == 0 && tel[35] == 0, "telemetry reserved @33..36");
        check(rd_f64(tel + 40) == 37.5, "telemetry gps[0] @40");
        check(rd_f64(tel + 48) == -122.25, "telemetry gps[1] @48");
        check(memcmp(tel + 56, want_hash, 8) == 0, "telemetry payloadHash @56");
    }

    /* ---- 3. imu sample ---- */
    size_t imu_len;
    uint8_t* imu = slurp(dir, "imu_sample.bin", &imu_len);
    check(imu && imu_len == 32, "imu sample is 32 bytes");
    if (imu) {
        check(rd_u64(imu + 0) == 999999999ull, "imu timestampNs @0");
        check(rd_f32(imu + 8) == 0.25f, "imu accel[0] @8");
        check(rd_f32(imu + 12) == -0.5f, "imu accel[1] @12");
        check(rd_f32(imu + 16) == 9.8125f, "imu accel[2] @16");
        check(rd_f32(imu + 20) == 0.125f, "imu gyro[0] @20");
        check(rd_f32(imu + 24) == -0.0625f, "imu gyro[1] @24");
        check(rd_f32(imu + 28) == 3.5f, "imu gyro[2] @28");
    }

    /* ---- 4. frame stack: envelope + payload + canary ---- */
    size_t stk_len;
    uint8_t* stk = slurp(dir, "weft_frame_stack.bin", &stk_len);
    check(stk && stk_len == 88, "frame stack is 88 bytes");
    if (stk && env && tel) {
        check(memcmp(stk, env, 16) == 0, "stack[0..16) == envelope");
        check(memcmp(stk + 16, tel, 64) == 0, "stack[16..80) == telemetry payload");
        check(rd_u64(stk + 80) == 0x0000BEEFull, "stack canary == seq (kernel canary rule)");
        /* the vertical slice: kernel-shaped buffer read via header_size indirection */
        uint16_t v = 0, hs = 0; uint32_t sq = 0, pl = 0;
        check(weft_envelope_decode(stk, (uint32_t)stk_len, &v, &hs, &sq, &pl) == WEFT_DECODE_OK,
              "kernel decodes frame stack OK");
        check(hs == 16 && pl == 64, "frame stack header_size/payload_len consistent");
        check(rd_u64(stk + hs) == 0x8F4C1120A9B30012ull, "payload schemaId readable at header_size");
    }

    free(env); free(tel); free(imu); free(stk);
    if (failures) {
        fprintf(stderr, "verify_golden: %d FAILURE(S)\n", failures);
        return 1;
    }
    printf("verify_golden: all C-side golden assertions hold\n");
    return 0;
}
