//! telemetry_frame — generated by weftc-codegen 0.1.0 (target: rust). DO NOT EDIT.
//! module: telemetry | struct: telemetry_frame | root: yes
//! schema_id: 0x8F4C1120A9B30012 (explicit)
//! layout: 64 bytes, align 8 — byte-identical with `weft_telemetry_frame_t` (C) and the
//! byte-exact GPU structs (WGSL storage / GLSL std430).
//!
//! Laws: zero allocation on every path; no_std (`core` only); unaligned
//! access only through read_unaligned/write_unaligned; layout is a
//! compile-time contract via #[repr(C)].
#![allow(dead_code)]

use super::weft_projection_core::WeftError;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TelemetryFrame {
    /// cryptographic schema hash header
    pub schema_id: u64,
    /// m/s
    pub velocity: f32,
    /// meters MSL
    pub altitude: f32,
    /// m/s^2 body frame
    pub accel: [f32; 3],
    /// explicit GPU-alignment pad (std430 vec3 tail)
    pub pad0: u32,
    /// rad/s body frame
    pub gyro: [f32; 3],
    /// Pa
    pub baro_pressure: f32,
    /// attitude w x y z
    pub quaternion: [f32; 4],
}

impl TelemetryFrame {
    /// 64-bit schema hash header this type projects.
    pub const SCHEMA_ID: u64 = 0x8F4C_1120_A9B3_0012;
    /// Exact struct size in bytes (weft-ir normative).
    pub const SIZE: usize = 64;
    /// Exact struct alignment in bytes (weft-ir normative).
    pub const ALIGN: usize = 8;

    /// Zero-copy projection: validates length, alignment and the schema
    /// hash header, then borrows the buffer as `&Self`. No copy, no
    /// allocation (Law 1); the check is three compares + one load.
    #[inline(always)]
    pub fn from_bytes(bytes: &[u8]) -> Result<&Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &*(bytes.as_ptr() as *const Self) })
    }

    /// Mutable twin (writer side: ring slots, UMEM pages).
    #[inline(always)]
    pub fn from_bytes_mut(bytes: &mut [u8]) -> Result<&mut Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &mut *(bytes.as_mut_ptr() as *mut Self) })
    }

    #[inline(always)]
    fn validate_header(bytes: &[u8]) -> Result<(), WeftError> {
        let p = bytes.as_ptr();
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        if (p as usize) & (Self::ALIGN - 1) != 0 {
            return Err(WeftError::BadAlign);
        }
        let id = unsafe { core::ptr::read_unaligned(p as *const u64) };
        if id != Self::SCHEMA_ID {
            return Err(WeftError::SchemaMismatch);
        }
        Ok(())
    }

    /// Byte view of this value (host little-endian) — direct
    /// queue.writeBuffer()/vkMapMemory upload source.
    #[inline(always)]
    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {
        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }
    }

    /// Alignment-free by-value read from a possibly-packed source
    /// (Law 3). Trusted-source path: no schema validation — use
    /// from_bytes for untrusted input.
    #[inline]
    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })
    }

    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).
    #[inline]
    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {
        if dst.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }
        Ok(())
    }

    /// Zero-overhead builder: `frame.with_schema_id(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_schema_id(mut self, schema_id: u64) -> Self {
        self.schema_id = schema_id;
        self
    }

    /// Zero-overhead builder: `frame.with_velocity(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_velocity(mut self, velocity: f32) -> Self {
        self.velocity = velocity;
        self
    }

    /// Zero-overhead builder: `frame.with_altitude(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_altitude(mut self, altitude: f32) -> Self {
        self.altitude = altitude;
        self
    }

    /// Zero-overhead builder: `frame.with_accel(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_accel(mut self, accel: [f32; 3]) -> Self {
        self.accel = accel;
        self
    }

    /// Zero-overhead builder: `frame.with_pad0(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_pad0(mut self, pad0: u32) -> Self {
        self.pad0 = pad0;
        self
    }

    /// Zero-overhead builder: `frame.with_gyro(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_gyro(mut self, gyro: [f32; 3]) -> Self {
        self.gyro = gyro;
        self
    }

    /// Zero-overhead builder: `frame.with_baro_pressure(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_baro_pressure(mut self, baro_pressure: f32) -> Self {
        self.baro_pressure = baro_pressure;
        self
    }

    /// Zero-overhead builder: `frame.with_quaternion(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_quaternion(mut self, quaternion: [f32; 4]) -> Self {
        self.quaternion = quaternion;
        self
    }

}

