// telemetry_frame.glsl — generated by weftc-codegen 0.1.0 (target: glsl). DO NOT EDIT.
// module: telemetry | struct: telemetry_frame | schema_id: 0x8F4C1120A9B30012
// host layout: 64 bytes, align 8
// std430 variant: BYTE-EXACT with the host struct — members sit at the
// same offsets as the C/Rust projections; fill an SSBO with host bytes
// directly. No host repacking.
// std140 (uniform) variant: REFUSED (Law 4) — field schema_id (scalar): u64/i64 are not permitted in the uniform address space (WGSL; std140 has no 64-bit integers) — use the storage variant
//
// requires: #extension GL_ARB_gpu_shader_int64 : require
//
// std430 — byte-exact with the host struct
struct WeftTelemetryFrame {
  uint64_t schema_id;        // @0 (8)
  float velocity;        // @8 (4)
  float altitude;        // @12 (4)
  vec3 accel;        // @16 (12)
  uint pad0;        // @28 (4)
  vec3 gyro;        // @32 (12)
  float baro_pressure;        // @44 (4)
  vec4 quaternion;        // @48 (16)
}; // size 64, align 16

// usage (SSBO):
//   layout(std430, binding = 0) readonly buffer FramesIn { WeftTelemetryFrame frames[]; };
