// telemetry_frame_validate.wgsl — generated by weftc-codegen 0.1.0. DO NOT EDIT.
// Direct-consumption proof: a compute shader reading an array of TelemetryFrame
// straight out of a storage buffer (bytes written by C/Rust, no
// repacking) and validating every schema hash GPU-side.
//   binding 0: read-only storage — array<TelemetryFrame>
//   binding 1: read_write storage — u32 triple [ok, bad_index+1, total]

// address space: storage (std430-equivalent) — byte-exact
struct TelemetryFrame {
  schema_id: u64,         // @0 (8)
  velocity: f32,         // @8 (4)
  altitude: f32,         // @12 (4)
  accel: vec3<f32>,         // @16 (12)
  pad0: u32,         // @28 (4)
  gyro: vec3<f32>,         // @32 (12)
  baro_pressure: f32,         // @44 (4)
  quaternion: vec4<f32>,        // @48 (16)
}; // size 64, align 16

@group(0) @binding(0) var<storage, read> frames_in: array<TelemetryFrame>;
@group(0) @binding(1) var<storage, read_write> scan: array<u32>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  let n = arrayLength(&frames_in);
  if (i >= n) {
    return;
  }
  atomicAdd(&scan[2], 1u);
  if (frames_in[i].schema_id == 0x8F4C1120A9B30012u) {
    atomicAdd(&scan[0], 1u);
  } else {
    atomicExchange(&scan[1], i + 1u);
  }
}
