// telemetry_frame.wgsl — generated by weftc-codegen 0.1.0 (target: wgsl). DO NOT EDIT.
// module: telemetry | struct: telemetry_frame | schema_id: 0x8F4C1120A9B30012
// host layout: 64 bytes, align 8
// storage variant: BYTE-EXACT with the host struct — members sit at the
// same offsets as the C/Rust projections; upload host bytes unchanged
// via queue.writeBuffer() into a storage buffer. No host repacking.
// uniform variant: REFUSED (Law 4) — field schema_id (scalar): u64/i64 are not permitted in the uniform address space (WGSL; std140 has no 64-bit integers) — use the storage variant
//
// address space: storage (std430-equivalent) — byte-exact
struct TelemetryFrame {
  schema_id: u64,         // @0 (8)
  velocity: f32,         // @8 (4)
  altitude: f32,         // @12 (4)
  accel: vec3<f32>,         // @16 (12)
  pad0: u32,         // @28 (4)
  gyro: vec3<f32>,         // @32 (12)
  baro_pressure: f32,         // @44 (4)
  quaternion: vec4<f32>,        // @48 (16)
}; // size 64, align 16

