// telemetry_frame.h — generated by weftc-codegen 0.1.0 (target: c). DO NOT EDIT.
// module: telemetry | struct: telemetry_frame | root: yes
// schema_id: 0x8F4C1120A9B30012 (explicit)
// layout: 64 bytes, align 8
//
// Laws (Pillar 1 briefing):
//   1. zero dynamic allocation on any read/write path below
//   2. pure C11 — the baseline build includes ONLY <stdint.h> <stdbool.h>
//      <stddef.h> <stdalign.h> <assert.h> (SIMD paths are behind
//      compiler capability macros and appear only when targeted)
//   3. unaligned-safe: cast helpers validate alignment; packed readers
//      are byte assembly — no UB on any architecture
//   4. host layout is guarded by static_assert below — a mismatched
//      compile is a build failure, never a silent misread

// ---- weft projection core (shared; self-guarded — safe in every header) ----
#ifndef WEFT_PROJECTION_CORE_H
#define WEFT_PROJECTION_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdalign.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Projection validation codes. Identical across every weftc-generated
/// header; legacy `rc == 0` checks remain correct (OK is 0).
typedef enum {
    WEFT_OK                  = 0,
    WEFT_ERR_SHORT_BUFFER    = 1,  // len < struct size (refused before any read)
    WEFT_ERR_BAD_ALIGN       = 2,  // buffer address violates struct alignment
    WEFT_ERR_SCHEMA_MISMATCH = 3,  // schema hash header does not match
} weft_error_t;

// The wire format is byte-exact little-endian. Refuse big-endian hosts at
// compile time rather than silently misreading every frame.
#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#error "weft projection: big-endian host not supported (wire format is byte-exact LE)"
#endif

/// Little-endian readers built from byte assembly — alignment-safe on every
/// architecture (Law 3) and dependency-free (Law 2). Optimizing compilers
/// fold these into a single load where the ISA allows it.
static inline uint16_t weft_read_u16_le(const uint8_t* p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}
static inline uint32_t weft_read_u32_le(const uint8_t* p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t weft_read_u64_le(const uint8_t* p)
{
    return (uint64_t)weft_read_u32_le(p) | ((uint64_t)weft_read_u32_le(p + 4) << 32);
}
static inline void weft_write_u16_le(uint8_t* p, uint16_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)(v >> 8);
}
static inline void weft_write_u32_le(uint8_t* p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu); p[3] = (uint8_t)(v >> 24);
}
static inline void weft_write_u64_le(uint8_t* p, uint64_t v)
{
    weft_write_u32_le(p, (uint32_t)(v & 0xFFFFFFFFu));
    weft_write_u32_le(p + 4, (uint32_t)(v >> 32));
}

typedef union { uint32_t u; float f; } weft_f32_bits;
typedef union { uint64_t u; double d; } weft_f64_bits;

static inline float weft_read_f32_le(const uint8_t* p)
{
    weft_f32_bits b; b.u = weft_read_u32_le(p); return b.f;
}
static inline double weft_read_f64_le(const uint8_t* p)
{
    weft_f64_bits b; b.u = weft_read_u64_le(p); return b.d;
}
static inline void weft_write_f32_le(uint8_t* p, float v)
{
    weft_f32_bits b; b.f = v; weft_write_u32_le(p, b.u);
}
static inline void weft_write_f64_le(uint8_t* p, double v)
{
    weft_f64_bits b; b.d = v; weft_write_u64_le(p, b.u);
}

/// IEEE 754 binary16 (half) codec — round-to-nearest-even both directions,
/// denormals and infinities exact. Zero dependencies: no <math.h>.
typedef uint16_t weft_f16_t;
static inline float weft_f16_to_f32(weft_f16_t h)
{
    const uint32_t sign = ((uint32_t)(h & 0x8000u)) << 16;
    const uint32_t exp  = ((uint32_t)(h >> 10)) & 0x1Fu;
    uint32_t man = h & 0x3FFu;
    uint32_t bits;
    if (exp == 0u) {
        if (man == 0u) {
            bits = sign;                                    /* +-0 */
        } else {
            uint32_t shift = 0u;                            /* subnormal -> normal */
            while ((man & 0x0400u) == 0u) { man <<= 1; shift++; }
            bits = sign | ((113u - shift) << 23) | ((man & 0x03FFu) << 13);
        }
    } else if (exp == 0x1Fu) {
        bits = sign | 0x7F800000u | (man ? (man << 13) : 0u);   /* inf / nan */
    } else {
        bits = sign | ((exp - 15u + 127u) << 23) | (man << 13);
    }
    weft_f32_bits b; b.u = bits; return b.f;
}
static inline weft_f16_t weft_f32_to_f16(float f)
{
    weft_f32_bits b; b.f = f;
    const uint32_t sign = (b.u >> 16) & 0x8000u;
    const uint32_t be = (b.u >> 23) & 0xFFu;
    const uint32_t man = b.u & 0x7FFFFFu;
    const int32_t exp = (int32_t)be - 127;
    if (be == 0xFFu) {
        return (weft_f16_t)(sign | 0x7C00u | (man ? 0x0200u : 0u));  /* inf/nan */
    }
    if (exp > 15) {
        return (weft_f16_t)(sign | 0x7C00u);                    /* overflow -> inf (RNE) */
    }
    if (exp >= -14) {
        uint32_t r = ((uint32_t)(exp + 15) << 10) | (man >> 13);
        const uint32_t rb = man & 0x1FFFu;
        if (rb > 0x1000u || (rb == 0x1000u && (r & 1u))) { r++; }
        return (weft_f16_t)(sign | r);
    }
    if (exp < -25) {
        return (weft_f16_t)sign;                               /* underflow -> 0 */
    }
    {
        const uint32_t m = man | 0x800000u;                    /* subnormal path */
        const uint32_t shift = (uint32_t)(-14 - exp);
        uint32_t r = m >> (13 + shift);
        const uint32_t rb = m & (((uint32_t)1 << (13 + shift)) - 1u);
        const uint32_t half = ((uint32_t)1 << (12 + shift));
        if (rb > half || (rb == half && (r & 1u))) {
            r++;
            if (r == 0x0400u) { return (weft_f16_t)(sign | 0x0400u); }
        }
        return (weft_f16_t)(sign | r);
    }
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_PROJECTION_CORE_H

#if defined(__AVX2__)
#include <immintrin.h>
#elif defined(__ARM_NEON)
#include <arm_neon.h>
#endif

#ifndef WEFT_TELEMETRY_FRAME_H
#define WEFT_TELEMETRY_FRAME_H

#define WEFT_TELEMETRY_FRAME_SCHEMA_ID UINT64_C(0x8F4C1120A9B30012)
#define WEFT_TELEMETRY_FRAME_SIZE 64u
#define WEFT_TELEMETRY_FRAME_ALIGN 8u
#define WEFT_TELEMETRY_FRAME_OFF_SCHEMA_ID 0u
#define WEFT_TELEMETRY_FRAME_OFF_VELOCITY 8u
#define WEFT_TELEMETRY_FRAME_OFF_ALTITUDE 12u
#define WEFT_TELEMETRY_FRAME_OFF_ACCEL 16u
#define WEFT_TELEMETRY_FRAME_LEN_ACCEL 3u
#define WEFT_TELEMETRY_FRAME_OFF_PAD0 28u
#define WEFT_TELEMETRY_FRAME_OFF_GYRO 32u
#define WEFT_TELEMETRY_FRAME_LEN_GYRO 3u
#define WEFT_TELEMETRY_FRAME_OFF_BARO_PRESSURE 44u
#define WEFT_TELEMETRY_FRAME_OFF_QUATERNION 48u
#define WEFT_TELEMETRY_FRAME_LEN_QUATERNION 4u

#ifdef __cplusplus
extern "C" {
#endif

/// weft_telemetry_frame_t — 64 bytes, align 8. Offsets are normative (weft-ir),
/// synthesized padding members make the C declaration match them exactly.
/// Canonical 64-byte GPU-exact telemetry frame (the Pillar 1 example ABI: sizeof 64, velocity at offset 8).
typedef struct weft_telemetry_frame {
    uint64_t schema_id; // cryptographic schema hash header              // @0 (8)
    float velocity; // m/s              // @8 (4)
    float altitude; // meters MSL              // @12 (4)
    float accel[3]; // m/s^2 body frame              // @16 (12)
    uint32_t pad0; // explicit GPU-alignment pad (std430 vec3 tail)              // @28 (4)
    float gyro[3]; // rad/s body frame              // @32 (12)
    float baro_pressure; // Pa              // @44 (4)
    float quaternion[4]; // attitude w x y z              // @48 (16)
} weft_telemetry_frame_t;

// Law 4 (host side): compile-time ABI guards.
static_assert(sizeof(weft_telemetry_frame_t) == 64, "weft ABI layout violation: telemetry_frame size");
static_assert(offsetof(weft_telemetry_frame_t, schema_id) == 0, "weft ABI: telemetry_frame.schema_id offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, velocity) == 8, "weft ABI: telemetry_frame.velocity offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, altitude) == 12, "weft ABI: telemetry_frame.altitude offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, accel) == 16, "weft ABI: telemetry_frame.accel offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, pad0) == 28, "weft ABI: telemetry_frame.pad0 offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, gyro) == 32, "weft ABI: telemetry_frame.gyro offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, baro_pressure) == 44, "weft ABI: telemetry_frame.baro_pressure offset mismatch");
static_assert(offsetof(weft_telemetry_frame_t, quaternion) == 48, "weft ABI: telemetry_frame.quaternion offset mismatch");

/// Zero-copy projection: validates byte length, buffer alignment and the
/// 64-bit schema hash header, then casts — no copy, no allocation. The hot
/// path is three compares and one load.
static inline const weft_telemetry_frame_t* weft_cast_telemetry_frame(const void* buffer, size_t len, weft_error_t* err)
{
    weft_error_t rc = WEFT_OK;
    const weft_telemetry_frame_t* out = NULL;
    const uint8_t* p = (const uint8_t*)buffer;
    if (len < (size_t)WEFT_TELEMETRY_FRAME_SIZE) {
        rc = WEFT_ERR_SHORT_BUFFER;
    } else if ((((uintptr_t)p) & (WEFT_TELEMETRY_FRAME_ALIGN - 1u)) != 0u) {
        rc = WEFT_ERR_BAD_ALIGN;
    } else if (*(const uint64_t*)(const void*)p != (uint64_t)WEFT_TELEMETRY_FRAME_SCHEMA_ID) {
        rc = WEFT_ERR_SCHEMA_MISMATCH;
    } else {
        out = (const weft_telemetry_frame_t*)p;
    }
    if (err) { *err = rc; }
    return out;
}

/// Mutable twin of weft_cast_telemetry_frame (writer side: UMEM/DMA ring slots).
static inline weft_telemetry_frame_t* weft_cast_telemetry_frame_mut(void* buffer, size_t len, weft_error_t* err)
{
    return (weft_telemetry_frame_t*)(void*)(uintptr_t)weft_cast_telemetry_frame((const void*)buffer, len, err);
}

/// Alignment-free by-value read from a possibly-packed source (Law 3).
/// Byte-assembly reads: safe on every architecture, no allocation.
static inline weft_error_t weft_telemetry_frame_read_packed(const void* buffer, size_t len, weft_telemetry_frame_t* out)
{
    if (len < (size_t)WEFT_TELEMETRY_FRAME_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    const uint8_t* p = (const uint8_t*)buffer;
    out->schema_id = weft_read_u64_le(p + 0u);
    out->velocity = weft_read_f32_le(p + 8u);
    out->altitude = weft_read_f32_le(p + 12u);
    for (uint32_t k = 0u; k < 3u; k++) {
        out->accel[k] = weft_read_f32_le(p + 16u + k * 4u);
    }
    out->pad0 = weft_read_u32_le(p + 28u);
    for (uint32_t k = 0u; k < 3u; k++) {
        out->gyro[k] = weft_read_f32_le(p + 32u + k * 4u);
    }
    out->baro_pressure = weft_read_f32_le(p + 44u);
    for (uint32_t k = 0u; k < 4u; k++) {
        out->quaternion[k] = weft_read_f32_le(p + 48u + k * 4u);
    }
    return WEFT_OK;
}

/// Alignment-free write to a possibly-packed destination (UMEM/DMA paths).
static inline weft_error_t weft_telemetry_frame_write_packed(void* buffer, size_t len, const weft_telemetry_frame_t* src)
{
    if (len < (size_t)WEFT_TELEMETRY_FRAME_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    uint8_t* p = (uint8_t*)buffer;
    weft_write_u64_le(p + 0u, (uint64_t)src->schema_id);
    weft_write_f32_le(p + 8u, src->velocity);
    weft_write_f32_le(p + 12u, src->altitude);
    for (uint32_t k = 0u; k < 3u; k++) {
        weft_write_f32_le(p + 16u + k * 4u, src->accel[k]);
    }
    weft_write_u32_le(p + 28u, (uint32_t)src->pad0);
    for (uint32_t k = 0u; k < 3u; k++) {
        weft_write_f32_le(p + 32u + k * 4u, src->gyro[k]);
    }
    weft_write_f32_le(p + 44u, src->baro_pressure);
    for (uint32_t k = 0u; k < 4u; k++) {
        weft_write_f32_le(p + 48u + k * 4u, src->quaternion[k]);
    }
    return WEFT_OK;
}

/// Batch schema-hash scan over an array of packed frames. AVX2 / NEON when
/// the compiler targets them, plain C11 scalar everywhere else (Law: the
/// portable build pulls no extra headers). Reads are alignment-safe on all
/// paths. On the first mismatching frame: returns WEFT_ERR_SCHEMA_MISMATCH,
/// *out_bad_index = its index, *out_count = frames validated before it.
static inline weft_error_t weft_validate_batch_telemetry_frame(const void* buffer, size_t len,
                                                 size_t* out_count, size_t* out_bad_index)
{
    const size_t stride = (size_t)WEFT_TELEMETRY_FRAME_SIZE;
    if (out_count) { *out_count = 0u; }
    if (out_bad_index) { *out_bad_index = 0u; }
    if ((len % stride) != 0u) { return WEFT_ERR_SHORT_BUFFER; }
    const size_t n = len / stride;
    const uint8_t* base = (const uint8_t*)buffer;
    size_t i = 0u;
#if defined(__AVX2__)
    if (n >= 4u) {
        const __m256i want = _mm256_set1_epi64x((long long)WEFT_TELEMETRY_FRAME_SCHEMA_ID);
        for (; (i + 4u) <= n; i += 4u) {
            const __m128i l0 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 0u) * stride));
            const __m128i l1 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 1u) * stride));
            const __m128i l2 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 2u) * stride));
            const __m128i l3 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 3u) * stride));
            const __m256i got = _mm256_set_epi64x(_mm_cvtsi128_si64(l3), _mm_cvtsi128_si64(l2),
                                                  _mm_cvtsi128_si64(l1), _mm_cvtsi128_si64(l0));
            const int mask = _mm256_movemask_epi8(_mm256_cmpeq_epi64(got, want));
            if (mask != -1) {
                for (int lane = 0; lane < 4; lane++) {
                    // movemask_epi8: 8 mask bits per 64-bit lane
                    if (((mask >> (lane * 8)) & 0xFF) != 0xFF) {
                        if (out_count) { *out_count = i + (size_t)lane; }
                        if (out_bad_index) { *out_bad_index = i + (size_t)lane; }
                        return WEFT_ERR_SCHEMA_MISMATCH;
                    }
                }
            }
        }
    }
#elif defined(__ARM_NEON) && defined(__aarch64__)
    if (n >= 2u) {
        const uint64x2_t want = vdupq_n_u64((uint64_t)WEFT_TELEMETRY_FRAME_SCHEMA_ID);
        for (; (i + 2u) <= n; i += 2u) {
            const uint64x2_t got = vcombine_u64(
                vld1_u64((const uint64_t*)(const void*)(base + (i + 0u) * stride)),
                vld1_u64((const uint64_t*)(const void*)(base + (i + 1u) * stride)));
            const uint64x2_t eq = vceqq_u64(got, want);
            if (vgetq_lane_u64(eq, 0) == 0u) {
                if (out_count) { *out_count = i; }
                if (out_bad_index) { *out_bad_index = i; }
                return WEFT_ERR_SCHEMA_MISMATCH;
            }
            if (vgetq_lane_u64(eq, 1) == 0u) {
                if (out_count) { *out_count = i + 1u; }
                if (out_bad_index) { *out_bad_index = i + 1u; }
                return WEFT_ERR_SCHEMA_MISMATCH;
            }
        }
    }
#endif
    for (; i < n; i++) {
        if (weft_read_u64_le(base + i * stride) != WEFT_TELEMETRY_FRAME_SCHEMA_ID) {
            if (out_count) { *out_count = i; }
            if (out_bad_index) { *out_bad_index = i; }
            return WEFT_ERR_SCHEMA_MISMATCH;
        }
    }
    if (out_count) { *out_count = n; }
    return WEFT_OK;
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_TELEMETRY_FRAME_H
