// camera_exposure.h — generated by weftc-codegen 0.1.0 (target: c). DO NOT EDIT.
// module: camera | struct: camera_exposure | root: yes
// schema_id: 0x0CD5F150 (auto: FNV-1a-64 of the canonical layout signature)
// layout: 128 bytes, align 16 (explicit alignas)
//
// Laws (Pillar 1 briefing):
//   1. zero dynamic allocation on any read/write path below
//   2. pure C11 — the baseline build includes ONLY <stdint.h> <stdbool.h>
//      <stddef.h> <stdalign.h> <assert.h> (SIMD paths are behind
//      compiler capability macros and appear only when targeted)
//   3. unaligned-safe: cast helpers validate alignment; packed readers
//      are byte assembly — no UB on any architecture
//   4. host layout is guarded by static_assert below — a mismatched
//      compile is a build failure, never a silent misread

// ---- weft projection core (shared; self-guarded — safe in every header) ----
#ifndef WEFT_PROJECTION_CORE_H
#define WEFT_PROJECTION_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdalign.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Projection validation codes. Identical across every weftc-generated
/// header; legacy `rc == 0` checks remain correct (OK is 0).
typedef enum {
    WEFT_OK                  = 0,
    WEFT_ERR_SHORT_BUFFER    = 1,  // len < struct size (refused before any read)
    WEFT_ERR_BAD_ALIGN       = 2,  // buffer address violates struct alignment
    WEFT_ERR_SCHEMA_MISMATCH = 3,  // schema hash header does not match
} weft_error_t;

// The wire format is byte-exact little-endian. Refuse big-endian hosts at
// compile time rather than silently misreading every frame.
#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#error "weft projection: big-endian host not supported (wire format is byte-exact LE)"
#endif

/// Little-endian readers built from byte assembly — alignment-safe on every
/// architecture (Law 3) and dependency-free (Law 2). Optimizing compilers
/// fold these into a single load where the ISA allows it.
static inline uint16_t weft_read_u16_le(const uint8_t* p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}
static inline uint32_t weft_read_u32_le(const uint8_t* p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t weft_read_u64_le(const uint8_t* p)
{
    return (uint64_t)weft_read_u32_le(p) | ((uint64_t)weft_read_u32_le(p + 4) << 32);
}
static inline void weft_write_u16_le(uint8_t* p, uint16_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)(v >> 8);
}
static inline void weft_write_u32_le(uint8_t* p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu); p[3] = (uint8_t)(v >> 24);
}
static inline void weft_write_u64_le(uint8_t* p, uint64_t v)
{
    weft_write_u32_le(p, (uint32_t)(v & 0xFFFFFFFFu));
    weft_write_u32_le(p + 4, (uint32_t)(v >> 32));
}

typedef union { uint32_t u; float f; } weft_f32_bits;
typedef union { uint64_t u; double d; } weft_f64_bits;

static inline float weft_read_f32_le(const uint8_t* p)
{
    weft_f32_bits b; b.u = weft_read_u32_le(p); return b.f;
}
static inline double weft_read_f64_le(const uint8_t* p)
{
    weft_f64_bits b; b.u = weft_read_u64_le(p); return b.d;
}
static inline void weft_write_f32_le(uint8_t* p, float v)
{
    weft_f32_bits b; b.f = v; weft_write_u32_le(p, b.u);
}
static inline void weft_write_f64_le(uint8_t* p, double v)
{
    weft_f64_bits b; b.d = v; weft_write_u64_le(p, b.u);
}

/// IEEE 754 binary16 (half) codec — round-to-nearest-even both directions,
/// denormals and infinities exact. Zero dependencies: no <math.h>.
typedef uint16_t weft_f16_t;
static inline float weft_f16_to_f32(weft_f16_t h)
{
    const uint32_t sign = ((uint32_t)(h & 0x8000u)) << 16;
    const uint32_t exp  = ((uint32_t)(h >> 10)) & 0x1Fu;
    uint32_t man = h & 0x3FFu;
    uint32_t bits;
    if (exp == 0u) {
        if (man == 0u) {
            bits = sign;                                    /* +-0 */
        } else {
            uint32_t shift = 0u;                            /* subnormal -> normal */
            while ((man & 0x0400u) == 0u) { man <<= 1; shift++; }
            bits = sign | ((113u - shift) << 23) | ((man & 0x03FFu) << 13);
        }
    } else if (exp == 0x1Fu) {
        bits = sign | 0x7F800000u | (man ? (man << 13) : 0u);   /* inf / nan */
    } else {
        bits = sign | ((exp - 15u + 127u) << 23) | (man << 13);
    }
    weft_f32_bits b; b.u = bits; return b.f;
}
static inline weft_f16_t weft_f32_to_f16(float f)
{
    weft_f32_bits b; b.f = f;
    const uint32_t sign = (b.u >> 16) & 0x8000u;
    const uint32_t be = (b.u >> 23) & 0xFFu;
    const uint32_t man = b.u & 0x7FFFFFu;
    const int32_t exp = (int32_t)be - 127;
    if (be == 0xFFu) {
        return (weft_f16_t)(sign | 0x7C00u | (man ? 0x0200u : 0u));  /* inf/nan */
    }
    if (exp > 15) {
        return (weft_f16_t)(sign | 0x7C00u);                    /* overflow -> inf (RNE) */
    }
    if (exp >= -14) {
        uint32_t r = ((uint32_t)(exp + 15) << 10) | (man >> 13);
        const uint32_t rb = man & 0x1FFFu;
        if (rb > 0x1000u || (rb == 0x1000u && (r & 1u))) { r++; }
        return (weft_f16_t)(sign | r);
    }
    if (exp < -25) {
        return (weft_f16_t)sign;                               /* underflow -> 0 */
    }
    {
        const uint32_t m = man | 0x800000u;                    /* subnormal path */
        const uint32_t shift = (uint32_t)(-14 - exp);
        uint32_t r = m >> (13 + shift);
        const uint32_t rb = m & (((uint32_t)1 << (13 + shift)) - 1u);
        const uint32_t half = ((uint32_t)1 << (12 + shift));
        if (rb > half || (rb == half && (r & 1u))) {
            r++;
            if (r == 0x0400u) { return (weft_f16_t)(sign | 0x0400u); }
        }
        return (weft_f16_t)(sign | r);
    }
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_PROJECTION_CORE_H

#if defined(__AVX2__)
#include <immintrin.h>
#elif defined(__ARM_NEON)
#include <arm_neon.h>
#endif

#ifndef WEFT_CAMERA_EXPOSURE_H
#define WEFT_CAMERA_EXPOSURE_H

#define WEFT_CAMERA_EXPOSURE_SCHEMA_ID UINT32_C(0x0CD5F150)
#define WEFT_CAMERA_EXPOSURE_SIZE 128u
#define WEFT_CAMERA_EXPOSURE_ALIGN 16u
#define WEFT_CAMERA_EXPOSURE_OFF_SCHEMA_ID 0u
#define WEFT_CAMERA_EXPOSURE_OFF_MODE 4u
#define WEFT_CAMERA_EXPOSURE_OFF_GAIN 8u
#define WEFT_CAMERA_EXPOSURE_OFF_EXPOSURE_US 12u
#define WEFT_CAMERA_EXPOSURE_OFF_POSITION 16u
#define WEFT_CAMERA_EXPOSURE_LEN_POSITION 4u
#define WEFT_CAMERA_EXPOSURE_OFF_PROJECTION 32u
#define WEFT_CAMERA_EXPOSURE_LEN_PROJECTION 16u
#define WEFT_CAMERA_EXPOSURE_OFF_ROI 96u
#define WEFT_CAMERA_EXPOSURE_LEN_ROI 2u

#ifdef __cplusplus
extern "C" {
#endif

/// weft_camera_exposure_t — 128 bytes, align 16. Offsets are normative (weft-ir),
/// synthesized padding members make the C declaration match them exactly.
/// Uniform-safe exposure block: every member satisfies std140 (16-aligned vectors/matrices, 16-stride arrays, u32 header).
typedef struct weft_camera_exposure {
    alignas(16) uint32_t schema_id;              // @0 (4)
    uint32_t mode;              // @4 (4)
    float gain; // ISO gain multiplier              // @8 (4)
    float exposure_us; // microseconds              // @12 (4)
    float position[4]; // camera world position              // @16 (16)
    float projection[16]; // column-major projection matrix              // @32 (64)
    float roi[2][4]; // region of interest rect x2              // @96 (32)
} weft_camera_exposure_t;

// Law 4 (host side): compile-time ABI guards.
static_assert(sizeof(weft_camera_exposure_t) == 128, "weft ABI layout violation: camera_exposure size");
static_assert(alignof(weft_camera_exposure_t) == 16, "weft ABI layout violation: camera_exposure alignment");
static_assert(offsetof(weft_camera_exposure_t, schema_id) == 0, "weft ABI: camera_exposure.schema_id offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, mode) == 4, "weft ABI: camera_exposure.mode offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, gain) == 8, "weft ABI: camera_exposure.gain offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, exposure_us) == 12, "weft ABI: camera_exposure.exposure_us offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, position) == 16, "weft ABI: camera_exposure.position offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, projection) == 32, "weft ABI: camera_exposure.projection offset mismatch");
static_assert(offsetof(weft_camera_exposure_t, roi) == 96, "weft ABI: camera_exposure.roi offset mismatch");

/// Zero-copy projection: validates byte length, buffer alignment and the
/// 32-bit schema hash header, then casts — no copy, no allocation. The hot
/// path is three compares and one load.
static inline const weft_camera_exposure_t* weft_cast_camera_exposure(const void* buffer, size_t len, weft_error_t* err)
{
    weft_error_t rc = WEFT_OK;
    const weft_camera_exposure_t* out = NULL;
    const uint8_t* p = (const uint8_t*)buffer;
    if (len < (size_t)WEFT_CAMERA_EXPOSURE_SIZE) {
        rc = WEFT_ERR_SHORT_BUFFER;
    } else if ((((uintptr_t)p) & (WEFT_CAMERA_EXPOSURE_ALIGN - 1u)) != 0u) {
        rc = WEFT_ERR_BAD_ALIGN;
    } else if (*(const uint32_t*)(const void*)p != (uint32_t)WEFT_CAMERA_EXPOSURE_SCHEMA_ID) {
        rc = WEFT_ERR_SCHEMA_MISMATCH;
    } else {
        out = (const weft_camera_exposure_t*)p;
    }
    if (err) { *err = rc; }
    return out;
}

/// Mutable twin of weft_cast_camera_exposure (writer side: UMEM/DMA ring slots).
static inline weft_camera_exposure_t* weft_cast_camera_exposure_mut(void* buffer, size_t len, weft_error_t* err)
{
    return (weft_camera_exposure_t*)(void*)(uintptr_t)weft_cast_camera_exposure((const void*)buffer, len, err);
}

/// Alignment-free by-value read from a possibly-packed source (Law 3).
/// Byte-assembly reads: safe on every architecture, no allocation.
static inline weft_error_t weft_camera_exposure_read_packed(const void* buffer, size_t len, weft_camera_exposure_t* out)
{
    if (len < (size_t)WEFT_CAMERA_EXPOSURE_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    const uint8_t* p = (const uint8_t*)buffer;
    out->schema_id = weft_read_u32_le(p + 0u);
    out->mode = weft_read_u32_le(p + 4u);
    out->gain = weft_read_f32_le(p + 8u);
    out->exposure_us = weft_read_f32_le(p + 12u);
    for (uint32_t k = 0u; k < 4u; k++) {
        out->position[k] = weft_read_f32_le(p + 16u + k * 4u);
    }
    for (uint32_t k = 0u; k < 16u; k++) {
        out->projection[k] = weft_read_f32_le(p + 32u + k * 4u);
    }
    for (uint32_t k = 0u; k < 2u; k++) {
        for (uint32_t j = 0u; j < 4u; j++) {
            out->roi[k][j] = weft_read_f32_le(p + 96u + (k * 4u + j) * 4u);
        }
    }
    return WEFT_OK;
}

/// Alignment-free write to a possibly-packed destination (UMEM/DMA paths).
static inline weft_error_t weft_camera_exposure_write_packed(void* buffer, size_t len, const weft_camera_exposure_t* src)
{
    if (len < (size_t)WEFT_CAMERA_EXPOSURE_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    uint8_t* p = (uint8_t*)buffer;
    weft_write_u32_le(p + 0u, (uint32_t)src->schema_id);
    weft_write_u32_le(p + 4u, (uint32_t)src->mode);
    weft_write_f32_le(p + 8u, src->gain);
    weft_write_f32_le(p + 12u, src->exposure_us);
    for (uint32_t k = 0u; k < 4u; k++) {
        weft_write_f32_le(p + 16u + k * 4u, src->position[k]);
    }
    for (uint32_t k = 0u; k < 16u; k++) {
        weft_write_f32_le(p + 32u + k * 4u, src->projection[k]);
    }
    for (uint32_t k = 0u; k < 2u; k++) {
        for (uint32_t j = 0u; j < 4u; j++) {
            weft_write_f32_le(p + 96u + (k * 4u + j) * 4u, src->roi[k][j]);
        }
    }
    return WEFT_OK;
}

/// camera_exposure.ae_lock: bits [0..0] of mode
static inline uint32_t weft_camera_exposure_get_ae_lock(const weft_camera_exposure_t* f)
{
    return (uint32_t)((f->mode >> 0) & 0x1u);
}
static inline void weft_camera_exposure_set_ae_lock(weft_camera_exposure_t* f, uint32_t v)
{
    f->mode = (uint32_t)((f->mode & ~(0x1u << 0)) | ((v & 0x1u) << 0));
}

/// camera_exposure.sensor: bits [1..3] of mode
static inline uint32_t weft_camera_exposure_get_sensor(const weft_camera_exposure_t* f)
{
    return (uint32_t)((f->mode >> 1) & 0x7u);
}
static inline void weft_camera_exposure_set_sensor(weft_camera_exposure_t* f, uint32_t v)
{
    f->mode = (uint32_t)((f->mode & ~(0x7u << 1)) | ((v & 0x7u) << 1));
}

/// Batch schema-hash scan over an array of packed frames. AVX2 / NEON when
/// the compiler targets them, plain C11 scalar everywhere else (Law: the
/// portable build pulls no extra headers). Reads are alignment-safe on all
/// paths. On the first mismatching frame: returns WEFT_ERR_SCHEMA_MISMATCH,
/// *out_bad_index = its index, *out_count = frames validated before it.
static inline weft_error_t weft_validate_batch_camera_exposure(const void* buffer, size_t len,
                                                 size_t* out_count, size_t* out_bad_index)
{
    const size_t stride = (size_t)WEFT_CAMERA_EXPOSURE_SIZE;
    if (out_count) { *out_count = 0u; }
    if (out_bad_index) { *out_bad_index = 0u; }
    if ((len % stride) != 0u) { return WEFT_ERR_SHORT_BUFFER; }
    const size_t n = len / stride;
    const uint8_t* base = (const uint8_t*)buffer;
    size_t i = 0u;
#if defined(__AVX2__)
    if (n >= 8u) {
        const __m256i want = _mm256_set1_epi32((int)WEFT_CAMERA_EXPOSURE_SCHEMA_ID);
        for (; (i + 8u) <= n; i += 8u) {
            const __m256i got = _mm256_set_epi32(
                (int)weft_read_u32_le(base + (i + 7u) * stride),
                (int)weft_read_u32_le(base + (i + 6u) * stride),
                (int)weft_read_u32_le(base + (i + 5u) * stride),
                (int)weft_read_u32_le(base + (i + 4u) * stride),
                (int)weft_read_u32_le(base + (i + 3u) * stride),
                (int)weft_read_u32_le(base + (i + 2u) * stride),
                (int)weft_read_u32_le(base + (i + 1u) * stride),
                (int)weft_read_u32_le(base + (i + 0u) * stride));
            const int mask = _mm256_movemask_epi8(_mm256_cmpeq_epi32(got, want));
            if (mask != -1) {
                for (int lane = 0; lane < 8; lane++) {
                    if (((mask >> (lane * 4)) & 0xF) != 0xF) {
                        if (out_count) { *out_count = i + (size_t)lane; }
                        if (out_bad_index) { *out_bad_index = i + (size_t)lane; }
                        return WEFT_ERR_SCHEMA_MISMATCH;
                    }
                }
            }
        }
    }
#elif defined(__ARM_NEON)
    if (n >= 4u) {
        const uint32x4_t want = vdupq_n_u32((uint32_t)WEFT_CAMERA_EXPOSURE_SCHEMA_ID);
        for (; (i + 4u) <= n; i += 4u) {
            const uint32x4_t got = vcombine_u32(
                vcreate_u32((uint64_t)weft_read_u32_le(base + (i + 0u) * stride)
                            | ((uint64_t)weft_read_u32_le(base + (i + 1u) * stride) << 32)),
                vcreate_u32((uint64_t)weft_read_u32_le(base + (i + 2u) * stride)
                            | ((uint64_t)weft_read_u32_le(base + (i + 3u) * stride) << 32)));
            const uint32x4_t eq = vceqq_u32(got, want);
            for (int lane = 0; lane < 4; lane++) {
                if (vgetq_lane_u32(eq, lane) != 0xFFFFFFFFu) {
                    if (out_count) { *out_count = i + (size_t)lane; }
                    if (out_bad_index) { *out_bad_index = i + (size_t)lane; }
                    return WEFT_ERR_SCHEMA_MISMATCH;
                }
            }
        }
    }
#endif
    for (; i < n; i++) {
        if (weft_read_u32_le(base + i * stride) != WEFT_CAMERA_EXPOSURE_SCHEMA_ID) {
            if (out_count) { *out_count = i; }
            if (out_bad_index) { *out_bad_index = i; }
            return WEFT_ERR_SCHEMA_MISMATCH;
        }
    }
    if (out_count) { *out_count = n; }
    return WEFT_OK;
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_CAMERA_EXPOSURE_H
