// camera_exposure.glsl — generated by weftc-codegen 0.1.0 (target: glsl). DO NOT EDIT.
// module: camera | struct: camera_exposure | schema_id: 0x0CD5F150
// host layout: 128 bytes, align 16
// std430 variant: BYTE-EXACT with the host struct — members sit at the
// same offsets as the C/Rust projections; fill an SSBO with host bytes
// directly. No host repacking.
//
//
// std430 — byte-exact with the host struct
struct WeftCameraExposure {
  uint schema_id;        // @0 (4)
  uint mode;        // @4 (4)
  float gain;        // @8 (4)
  float exposure_us;        // @12 (4)
  vec4 position;        // @16 (16)
  mat4 projection;        // @32 (64)
  vec4[2] roi;        // @96 (32)
}; // size 128, align 16

// std140 (uniform) — byte-exact
struct WeftCameraExposureUniform {
  uint schema_id;        // @0 (4)
  uint mode;        // @4 (4)
  float gain;        // @8 (4)
  float exposure_us;        // @12 (4)
  vec4 position;        // @16 (16)
  mat4 projection;        // @32 (64)
  vec4[2] roi;        // @96 (32)
}; // size 128, align 16

// usage (SSBO):
//   layout(std430, binding = 0) readonly buffer FramesIn { WeftCameraExposure frames[]; };
