//! camera_exposure — generated by weftc-codegen 0.1.0 (target: rust). DO NOT EDIT.
//! module: camera | struct: camera_exposure | root: yes
//! schema_id: 0x0CD5F150 (auto: FNV-1a-64 of the canonical layout signature)
//! layout: 128 bytes, align 16 — byte-identical with `weft_camera_exposure_t` (C) and the
//! byte-exact GPU structs (WGSL storage / GLSL std430).
//!
//! Laws: zero allocation on every path; no_std (`core` only); unaligned
//! access only through read_unaligned/write_unaligned; layout is a
//! compile-time contract via #[repr(C)].
#![allow(dead_code)]

use super::weft_projection_core::WeftError;

#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CameraExposure {
    pub schema_id: u32,
    pub mode: u32,
    /// ISO gain multiplier
    pub gain: f32,
    /// microseconds
    pub exposure_us: f32,
    /// camera world position
    pub position: [f32; 4],
    /// column-major projection matrix
    pub projection: [f32; 16],
    /// region of interest rect x2
    pub roi: [[f32; 4]; 2],
}

impl CameraExposure {
    /// 32-bit schema hash header this type projects.
    pub const SCHEMA_ID: u32 = 0x0CD5_F150;
    /// Exact struct size in bytes (weft-ir normative).
    pub const SIZE: usize = 128;
    /// Exact struct alignment in bytes (weft-ir normative).
    pub const ALIGN: usize = 16;

    /// Zero-copy projection: validates length, alignment and the schema
    /// hash header, then borrows the buffer as `&Self`. No copy, no
    /// allocation (Law 1); the check is three compares + one load.
    #[inline(always)]
    pub fn from_bytes(bytes: &[u8]) -> Result<&Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &*(bytes.as_ptr() as *const Self) })
    }

    /// Mutable twin (writer side: ring slots, UMEM pages).
    #[inline(always)]
    pub fn from_bytes_mut(bytes: &mut [u8]) -> Result<&mut Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &mut *(bytes.as_mut_ptr() as *mut Self) })
    }

    #[inline(always)]
    fn validate_header(bytes: &[u8]) -> Result<(), WeftError> {
        let p = bytes.as_ptr();
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        if (p as usize) & (Self::ALIGN - 1) != 0 {
            return Err(WeftError::BadAlign);
        }
        let id = unsafe { core::ptr::read_unaligned(p as *const u32) };
        if id != Self::SCHEMA_ID {
            return Err(WeftError::SchemaMismatch);
        }
        Ok(())
    }

    /// Byte view of this value (host little-endian) — direct
    /// queue.writeBuffer()/vkMapMemory upload source.
    #[inline(always)]
    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {
        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }
    }

    /// Alignment-free by-value read from a possibly-packed source
    /// (Law 3). Trusted-source path: no schema validation — use
    /// from_bytes for untrusted input.
    #[inline]
    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })
    }

    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).
    #[inline]
    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {
        if dst.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }
        Ok(())
    }

    /// Zero-overhead builder: `frame.with_schema_id(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_schema_id(mut self, schema_id: u32) -> Self {
        self.schema_id = schema_id;
        self
    }

    /// Zero-overhead builder: `frame.with_mode(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_mode(mut self, mode: u32) -> Self {
        self.mode = mode;
        self
    }

    /// Zero-overhead builder: `frame.with_gain(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_gain(mut self, gain: f32) -> Self {
        self.gain = gain;
        self
    }

    /// Zero-overhead builder: `frame.with_exposure_us(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_exposure_us(mut self, exposure_us: f32) -> Self {
        self.exposure_us = exposure_us;
        self
    }

    /// Zero-overhead builder: `frame.with_position(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_position(mut self, position: [f32; 4]) -> Self {
        self.position = position;
        self
    }

    /// Zero-overhead builder: `frame.with_projection(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_projection(mut self, projection: [f32; 16]) -> Self {
        self.projection = projection;
        self
    }

    /// Zero-overhead builder: `frame.with_roi(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_roi(mut self, roi: [[f32; 4]; 2]) -> Self {
        self.roi = roi;
        self
    }

    /// camera_exposure.ae_lock: bits [0..0] of mode
    #[inline(always)]
    pub const fn ae_lock(&self) -> u32 {
        (self.mode >> 0) & 0x1
    }
    #[inline(always)]
    pub fn set_ae_lock(&mut self, v: u32) {
        self.mode = (self.mode & !(0x1)) | ((v & 0x1) << 0);
    }
    #[inline(always)]
    pub const fn with_ae_lock(mut self, v: u32) -> Self {
        self.mode = (self.mode & !(0x1)) | ((v & 0x1) << 0);
        self
    }

    /// camera_exposure.sensor: bits [1..3] of mode
    #[inline(always)]
    pub const fn sensor(&self) -> u32 {
        (self.mode >> 1) & 0x7
    }
    #[inline(always)]
    pub fn set_sensor(&mut self, v: u32) {
        self.mode = (self.mode & !(0x7)) | ((v & 0x7) << 1);
    }
    #[inline(always)]
    pub const fn with_sensor(mut self, v: u32) -> Self {
        self.mode = (self.mode & !(0x7)) | ((v & 0x7) << 1);
        self
    }

}

