// camera_exposure_validate.wgsl — generated by weftc-codegen 0.1.0. DO NOT EDIT.
// Direct-consumption proof: a compute shader reading an array of CameraExposure
// straight out of a storage buffer (bytes written by C/Rust, no
// repacking) and validating every schema hash GPU-side.
//   binding 0: read-only storage — array<CameraExposure>
//   binding 1: read_write storage — u32 triple [ok, bad_index+1, total]

// address space: storage (std430-equivalent) — byte-exact
struct CameraExposure {
  schema_id: u32,         // @0 (4)
  mode: u32,         // @4 (4)
  gain: f32,         // @8 (4)
  exposure_us: f32,         // @12 (4)
  position: vec4<f32>,         // @16 (16)
  projection: mat4x4<f32>,         // @32 (64)
  roi: array<vec4<f32>, 2>,        // @96 (32)
}; // size 128, align 16

@group(0) @binding(0) var<storage, read> frames_in: array<CameraExposure>;
@group(0) @binding(1) var<storage, read_write> scan: array<u32>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  let n = arrayLength(&frames_in);
  if (i >= n) {
    return;
  }
  atomicAdd(&scan[2], 1u);
  if (frames_in[i].schema_id == 0x0CD5F150u) {
    atomicAdd(&scan[0], 1u);
  } else {
    atomicExchange(&scan[1], i + 1u);
  }
}
