// camera_exposure.wgsl — generated by weftc-codegen 0.1.0 (target: wgsl). DO NOT EDIT.
// module: camera | struct: camera_exposure | schema_id: 0x0CD5F150
// host layout: 128 bytes, align 16
// storage variant: BYTE-EXACT with the host struct — members sit at the
// same offsets as the C/Rust projections; upload host bytes unchanged
// via queue.writeBuffer() into a storage buffer. No host repacking.
//
// address space: storage (std430-equivalent) — byte-exact
struct CameraExposure {
  schema_id: u32,         // @0 (4)
  mode: u32,         // @4 (4)
  gain: f32,         // @8 (4)
  exposure_us: f32,         // @12 (4)
  position: vec4<f32>,         // @16 (16)
  projection: mat4x4<f32>,         // @32 (64)
  roi: array<vec4<f32>, 2>,        // @96 (32)
}; // size 128, align 16

// address space: uniform (std140-equivalent) — byte-exact
struct CameraExposureUniform {
  schema_id: u32,         // @0 (4)
  mode: u32,         // @4 (4)
  gain: f32,         // @8 (4)
  exposure_us: f32,         // @12 (4)
  position: vec4<f32>,         // @16 (16)
  projection: mat4x4<f32>,         // @32 (64)
  roi: array<vec4<f32>, 2>,        // @96 (32)
}; // size 128, align 16

