//! weft_projection_core — generated by weftc-codegen 0.1.0. DO NOT EDIT.
//!
//! Shared core for every weftc-generated Rust projection module:
//! the error taxonomy and the dependency-free IEEE 754 binary16 codec.
//! no_std — `core` only, no alloc (Law 2).
#![allow(dead_code)]

use core::fmt;

/// Projection validation codes — mirrors `weft_error_t` in the C core.
/// OK-success is encoded as `Ok(())`; these name every refusal mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WeftError {
    /// `len < struct size` — refused before any byte is read.
    ShortBuffer,
    /// buffer address violates the struct alignment requirement.
    BadAlign,
    /// schema hash header does not match this type.
    SchemaMismatch,
}

impl fmt::Display for WeftError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            WeftError::ShortBuffer => write!(f, "weft: buffer shorter than struct size"),
            WeftError::BadAlign => write!(f, "weft: buffer address violates struct alignment"),
            WeftError::SchemaMismatch => write!(f, "weft: schema hash header mismatch"),
        }
    }
}

/// IEEE 754 binary16 as a bit-exact newtype over `u16` — zero deps, no
/// `half` crate (Law 2). Round-to-nearest-even both directions,
/// denormals and infinities exact; mirrors the C core bit for bit.
#[derive(Clone, Copy, Default, PartialEq, Eq)]
pub struct WeftF16(pub u16);

impl WeftF16 {
    #[inline]
    pub const fn from_bits(bits: u16) -> Self { WeftF16(bits) }
    #[inline]
    pub const fn to_bits(self) -> u16 { self.0 }

    /// Exact half -> float (denormals normalized, inf/nan preserved).
    #[inline]
    pub fn to_f32(self) -> f32 {
        let sign = ((self.0 as u32 & 0x8000) as u32) << 16;
        let exp = ((self.0 >> 10) as u32) & 0x1F;
        let mut man = (self.0 & 0x3FF) as u32;
        let bits: u32;
        if exp == 0 {
            if man == 0 {
                bits = sign;
            } else {
                let mut shift = 0u32;
                while (man & 0x0400) == 0 { man <<= 1; shift += 1; }
                bits = sign | ((113 - shift) << 23) | ((man & 0x03FF) << 13);
            }
        } else if exp == 0x1F {
            bits = sign | 0x7F80_0000 | if man != 0 { man << 13 } else { 0 };
        } else {
            // exp + 112 == (exp - 15) + 127, arranged so no intermediate
            // underflow occurs (Rust debug builds panic on u32 wrap)
            bits = sign | ((exp + 112) << 23) | (man << 13);
        }
        f32::from_bits(bits)
    }

    /// Exact float -> half, round-to-nearest-even (RNE), overflow to
    /// infinity, underflow to zero — bit-identical with the C core.
    #[inline]
    pub fn from_f32(f: f32) -> Self {
        let b = f.to_bits();
        let sign = (b >> 16) & 0x8000;
        let be = (b >> 23) & 0xFF;
        let man = b & 0x7F_FF_FF;
        let exp = be as i32 - 127;
        if be == 0xFF {
            return WeftF16((sign | 0x7C00 | if man != 0 { 0x0200 } else { 0 }) as u16);
        }
        if exp > 15 {
            return WeftF16((sign | 0x7C00) as u16);
        }
        if exp >= -14 {
            let mut r = (((exp + 15) as u32) << 10) | (man >> 13);
            let rb = man & 0x1FFF;
            if rb > 0x1000 || (rb == 0x1000 && (r & 1) != 0) { r += 1; }
            return WeftF16((sign | r) as u16);
        }
        if exp < -25 {
            return WeftF16(sign as u16);
        }
        let m = man | 0x80_00_00;
        let shift = (-14 - exp) as u32;
        let mut r = m >> (13 + shift);
        let rb = m & ((1u32 << (13 + shift)) - 1);
        let half = 1u32 << (12 + shift);
        if rb > half || (rb == half && (r & 1) != 0) {
            r += 1;
            if r == 0x0400 { return WeftF16((sign | 0x0400) as u16); }
        }
        WeftF16((sign | r) as u16)
    }
}

impl fmt::Debug for WeftF16 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "WeftF16({:#06x} = {})", self.0, self.to_f32())
    }
}

/// Batch schema-hash scan (scalar; the C core carries the AVX2/NEON
/// specializations — LLVM auto-vectorizes this loop at -O2/-C opt-level=2).
pub fn weft_validate_batch<const STRIDE: usize>(
    bytes: &[u8],
    read_id: impl Fn(&[u8]) -> u64,
    expected: u64,
) -> (usize, Option<usize>) {
    let n = bytes.len() / STRIDE;
    for i in 0..n {
        let id = read_id(&bytes[i * STRIDE..]);
        if id != expected {
            return (i, Some(i));
        }
    }
    (n, None)
}

#[cfg(feature = "bytemuck")]
unsafe impl bytemuck::Zeroable for WeftF16 {}
#[cfg(feature = "bytemuck")]
impl bytemuck::Pod for WeftF16 {}
