"""AUTO-GENERATED by weftc-managed/1.0.0 (python) — DO NOT EDIT.

Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct ImuSample · 32 B · little-endian
Regenerate: node tools/weftc/weftc.mjs --ir <schema.json> --target py
Layout is normative; hand edits will be overwritten and drift will fail CI.

Zero-copy managed view (Pillar 1): bind() projects a bytes-like window
without copying; every struct format is explicitly little-endian (Law 2).
"""

from __future__ import annotations

import struct

try:  # NumPy is optional; the struct path is fully functional without it.
    import numpy as _np
except ImportError:  # pragma: no cover - exercised only on minimal installs
    _np = None

__all__ = ["ImuSample"]

_STRUCT_U32 = struct.Struct("<I")
_TIMESTAMP_NS_S = struct.Struct("<Q")
_ACCEL_S_E = struct.Struct("<f")
_ACCEL_S = struct.Struct("<3f")
_GYRO_S_E = struct.Struct("<f")
_GYRO_S = struct.Struct("<3f")


class ImuSample:
    """
    Header-less 32-byte lean payload: exercises the no-handshake validateHeader() path (bounds check only) and proves backends emit correct code when no const/role fields exist.
    """
    BYTE_LENGTH = 32
    TIMESTAMP_NS_OFFSET = 0  # u64
    ACCEL_OFFSET = 8  # f32[3]
    GYRO_OFFSET = 20  # f32[3]

    __slots__ = ("_buf", "_offset")

    def __init__(self) -> None:
        self._buf = None
        self._offset = 0

    @property
    def bound(self) -> bool:
        """True once bound."""
        return self._buf is not None

    @property
    def offset(self) -> int:
        """Byte offset this view is bound at (relative to the bound object)."""
        return self._offset

    def bind(self, buf, offset: int = 0):
        """Bind to a bytes-like object (bytes/bytearray/memoryview/ndarray).

        Zero-copy: the bytes are referenced, never duplicated. Rebinding one
        instance per frame is the steady-state pattern (Law 1). Writable
        buffers (bytearray, writable ndarray) unlock the setter path.
        """
        mv = memoryview(buf)
        if mv.itemsize != 1 or mv.ndim != 1:
            mv = mv.cast("B")  # normalize to a flat byte view (no data copy)
        if offset < 0 or offset + ImuSample.BYTE_LENGTH > mv.nbytes:
            raise ValueError("ImuSample.bind: window [%d..%d) exceeds buffer of %d bytes" % (offset, offset + ImuSample.BYTE_LENGTH, mv.nbytes))
        self._buf = mv
        self._offset = offset
        return self

    def validate_header(self, avail=None) -> bool:
        """Non-throwing Law 4 handshake: bounds + consts (+ payload avail)."""
        if self._buf is None:
            return False
        base = self._offset
        return True


    # Monotonic hardware timestamp, nanoseconds.
    # @byteOffset 0x0 (u64)
    @property
    def timestamp_ns(self):
        return _TIMESTAMP_NS_S.unpack_from(self._buf, self._offset + 0)[0]

    @timestamp_ns.setter
    def timestamp_ns(self, value):
        _TIMESTAMP_NS_S.pack_into(self._buf, self._offset + 0, value)

    def with_timestamp_ns(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.timestamp_ns = value
        return self

    @property
    def timestamp_ns_lo(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 0)[0]

    @timestamp_ns_lo.setter
    def timestamp_ns_lo(self, value):
        _STRUCT_U32.pack_into(self._buf, self._offset + 0, value)

    @property
    def timestamp_ns_hi(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 4)[0]

    @timestamp_ns_hi.setter
    def timestamp_ns_hi(self, value):
        _STRUCT_U32.pack_into(self._buf, self._offset + 4, value)

    def with_timestamp_ns_lo(self, value):
        """Fluent mutator for the low 32 bits — returns self."""
        _STRUCT_U32.pack_into(self._buf, self._offset + 0, value)
        return self

    def with_timestamp_ns_hi(self, value):
        """Fluent mutator for the high 32 bits — returns self."""
        _STRUCT_U32.pack_into(self._buf, self._offset + 4, value)
        return self

    # Linear acceleration, g.
    # @byteOffset 0x8 (f32[3])
    def get_accel_at(self, index: int):
        return _ACCEL_S_E.unpack_from(self._buf, self._offset + 8 + index * 4)[0]

    def set_accel_at(self, index: int, value):
        _ACCEL_S_E.pack_into(self._buf, self._offset + 8 + index * 4, value)

    def with_accel_at(self, index: int, value):
        self.set_accel_at(index, value)
        return self

    # Angular rate, rad/s.
    # @byteOffset 0x14 (f32[3])
    def get_gyro_at(self, index: int):
        return _GYRO_S_E.unpack_from(self._buf, self._offset + 20 + index * 4)[0]

    def set_gyro_at(self, index: int, value):
        _GYRO_S_E.pack_into(self._buf, self._offset + 20 + index * 4, value)

    def with_gyro_at(self, index: int, value):
        self.set_gyro_at(index, value)
        return self

    def get_accel_all(self):
        """All 3 elements as a tuple (convenience; not the hot path)."""
        return _ACCEL_S.unpack_from(self._buf, self._offset + 8)

    def get_gyro_all(self):
        """All 3 elements as a tuple (convenience; not the hot path)."""
        return _GYRO_S.unpack_from(self._buf, self._offset + 20)

    @classmethod
    def dtype(cls):
        """NumPy structured dtype — explicit offsets + itemsize, gap-exact.

        Byte order is explicit little-endian (Law 2); layout is byte-exact
        with the IR and with C/Rust/GPU buffers.
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.dtype({
            "names": [
                "timestamp_ns",
                "accel",
                "gyro",
            ],
            "formats": [
                "<u8",
                ("<f4", (3,)),
                ("<f4", (3,)),
            ],
            "offsets": [
                0,
                8,
                20,
            ],
            "itemsize": 32,
        })

    def as_numpy(self):
        """Zero-copy NumPy structured scalar view over the bound window.

        The returned void scalar ALIASES the bound buffer: mutations of the
        buffer are visible in the view and (for writable buffers) writes
        through the view mutate the buffer. No bytes are copied (Law 1).
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.frombuffer(self._buf, dtype=ImuSample.dtype(), count=1, offset=self._offset)[0]

