"""AUTO-GENERATED by weftc-managed/1.0.0 (python) — DO NOT EDIT.

Source IR: tools/weftc/schema/fixtures/telemetry_frame.json (irVersion 1) · struct TelemetryFrame · 64 B · little-endian
Regenerate: node tools/weftc/weftc.mjs --ir <schema.json> --target py
Layout is normative; hand edits will be overwritten and drift will fail CI.

Zero-copy managed view (Pillar 1): bind() projects a bytes-like window
without copying; every struct format is explicitly little-endian (Law 2).
"""

from __future__ import annotations

import struct

try:  # NumPy is optional; the struct path is fully functional without it.
    import numpy as _np
except ImportError:  # pragma: no cover - exercised only on minimal installs
    _np = None

__all__ = ["TelemetryFrame"]

_STRUCT_U32 = struct.Struct("<I")
_SCHEMA_ID_S = struct.Struct("<Q")
_TIMESTAMP_NS_S = struct.Struct("<Q")
_VELOCITY_S_E = struct.Struct("<f")
_VELOCITY_S = struct.Struct("<3f")
_PRESSURE_PA_S = struct.Struct("<f")
_STATE_S = struct.Struct("<B")
_GPS_COORDINATES_S_E = struct.Struct("<d")
_GPS_COORDINATES_S = struct.Struct("<2d")


class TelemetryFrame:
    """
    Canonical 64-byte payload schema used across all managed backends for parity fixtures. Designed as the payload of a triad-1 envelope (bind at envelope.headerSize). Every numeric field is naturally aligned; all values in golden fixtures are exactly representable (dyadic) so cross-language comparisons are bit-exact.
    """
    BYTE_LENGTH = 64
    SCHEMA_ID = 0x8F4C1120A9B30012
    SCHEMA_VERSION = 3
    SCHEMA_ID_OFFSET = 0  # u64
    TIMESTAMP_NS_OFFSET = 8  # u64
    VELOCITY_OFFSET = 16  # f32[3]
    PRESSURE_PA_OFFSET = 28  # f32
    STATE_OFFSET = 32  # u8
    RESERVED_OFFSET = 33  # u8[3]
    GPS_COORDINATES_OFFSET = 40  # f64[2]
    PAYLOAD_HASH_OFFSET = 56  # u8[8]

    __slots__ = ("_buf", "_offset")

    def __init__(self) -> None:
        self._buf = None
        self._offset = 0

    @property
    def bound(self) -> bool:
        """True once bound."""
        return self._buf is not None

    @property
    def offset(self) -> int:
        """Byte offset this view is bound at (relative to the bound object)."""
        return self._offset

    def bind(self, buf, offset: int = 0):
        """Bind to a bytes-like object (bytes/bytearray/memoryview/ndarray).

        Zero-copy: the bytes are referenced, never duplicated. Rebinding one
        instance per frame is the steady-state pattern (Law 1). Writable
        buffers (bytearray, writable ndarray) unlock the setter path.
        """
        mv = memoryview(buf)
        if mv.itemsize != 1 or mv.ndim != 1:
            mv = mv.cast("B")  # normalize to a flat byte view (no data copy)
        if offset < 0 or offset + TelemetryFrame.BYTE_LENGTH > mv.nbytes:
            raise ValueError("TelemetryFrame.bind: window [%d..%d) exceeds buffer of %d bytes" % (offset, offset + TelemetryFrame.BYTE_LENGTH, mv.nbytes))
        self._buf = mv
        self._offset = offset
        return self

    def validate_header(self, avail=None) -> bool:
        """Non-throwing Law 4 handshake: bounds + consts (+ payload avail)."""
        if self._buf is None:
            return False
        base = self._offset
        if _SCHEMA_ID_S.unpack_from(self._buf, base + 0)[0] != 0x8f4c1120a9b30012:
            return False
        return True


    # Payload schema handshake; checked by validateHeader() before any field read (Law 4).
    # @byteOffset 0x0 (u64)
    @property
    def schema_id(self):
        return _SCHEMA_ID_S.unpack_from(self._buf, self._offset + 0)[0]

    @property
    def schema_id_lo(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 0)[0]

    @property
    def schema_id_hi(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 4)[0]

    # Monotonic hardware timestamp, nanoseconds.
    # @byteOffset 0x8 (u64)
    @property
    def timestamp_ns(self):
        return _TIMESTAMP_NS_S.unpack_from(self._buf, self._offset + 8)[0]

    @timestamp_ns.setter
    def timestamp_ns(self, value):
        _TIMESTAMP_NS_S.pack_into(self._buf, self._offset + 8, value)

    def with_timestamp_ns(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.timestamp_ns = value
        return self

    @property
    def timestamp_ns_lo(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 8)[0]

    @timestamp_ns_lo.setter
    def timestamp_ns_lo(self, value):
        _STRUCT_U32.pack_into(self._buf, self._offset + 8, value)

    @property
    def timestamp_ns_hi(self) -> int:
        return _STRUCT_U32.unpack_from(self._buf, self._offset + 12)[0]

    @timestamp_ns_hi.setter
    def timestamp_ns_hi(self, value):
        _STRUCT_U32.pack_into(self._buf, self._offset + 12, value)

    def with_timestamp_ns_lo(self, value):
        """Fluent mutator for the low 32 bits — returns self."""
        _STRUCT_U32.pack_into(self._buf, self._offset + 8, value)
        return self

    def with_timestamp_ns_hi(self, value):
        """Fluent mutator for the high 32 bits — returns self."""
        _STRUCT_U32.pack_into(self._buf, self._offset + 12, value)
        return self

    # Velocity vector, m/s. Maps to SIMD3<Float> / vector_float3 on Apple platforms.
    # @byteOffset 0x10 (f32[3])
    def get_velocity_at(self, index: int):
        return _VELOCITY_S_E.unpack_from(self._buf, self._offset + 16 + index * 4)[0]

    def set_velocity_at(self, index: int, value):
        _VELOCITY_S_E.pack_into(self._buf, self._offset + 16 + index * 4, value)

    def with_velocity_at(self, index: int, value):
        self.set_velocity_at(index, value)
        return self

    # Ambient pressure, Pa.
    # @byteOffset 0x1c (f32)
    @property
    def pressure_pa(self):
        return _PRESSURE_PA_S.unpack_from(self._buf, self._offset + 28)[0]

    @pressure_pa.setter
    def pressure_pa(self, value):
        _PRESSURE_PA_S.pack_into(self._buf, self._offset + 28, value)

    def with_pressure_pa(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.pressure_pa = value
        return self

    # Device state enum byte.
    # @byteOffset 0x20 (u8)
    @property
    def state(self):
        return _STATE_S.unpack_from(self._buf, self._offset + 32)[0]

    @state.setter
    def state(self, value):
        _STATE_S.pack_into(self._buf, self._offset + 32, value)

    def with_state(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.state = value
        return self

    # lat/lon pair, degrees.
    # @byteOffset 0x28 (f64[2])
    def get_gps_coordinates_at(self, index: int):
        return _GPS_COORDINATES_S_E.unpack_from(self._buf, self._offset + 40 + index * 8)[0]

    def set_gps_coordinates_at(self, index: int, value):
        _GPS_COORDINATES_S_E.pack_into(self._buf, self._offset + 40 + index * 8, value)

    def with_gps_coordinates_at(self, index: int, value):
        self.set_gps_coordinates_at(index, value)
        return self

    # Truncated payload digest (u8[8]).
    # @byteOffset 0x38 (u8[8])
    def get_payload_hash_at(self, index: int):
        return self._buf[self._offset + 56 + index * 1]

    def set_payload_hash_at(self, index: int, value):
        self._buf[self._offset + 56 + index * 1] = value

    def with_payload_hash_at(self, index: int, value):
        self.set_payload_hash_at(index, value)
        return self

    def get_velocity_all(self):
        """All 3 elements as a tuple (convenience; not the hot path)."""
        return _VELOCITY_S.unpack_from(self._buf, self._offset + 16)

    def get_gps_coordinates_all(self):
        """All 2 elements as a tuple (convenience; not the hot path)."""
        return _GPS_COORDINATES_S.unpack_from(self._buf, self._offset + 40)

    @classmethod
    def dtype(cls):
        """NumPy structured dtype — explicit offsets + itemsize, gap-exact.

        Byte order is explicit little-endian (Law 2); layout is byte-exact
        with the IR and with C/Rust/GPU buffers.
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.dtype({
            "names": [
                "schema_id",
                "timestamp_ns",
                "velocity",
                "pressure_pa",
                "state",
                "reserved",
                "gps_coordinates",
                "payload_hash",
            ],
            "formats": [
                "<u8",
                "<u8",
                ("<f4", (3,)),
                "<f4",
                "u1",
                ("u1", (3,)),
                ("<f8", (2,)),
                ("u1", (8,)),
            ],
            "offsets": [
                0,
                8,
                16,
                28,
                32,
                33,
                40,
                56,
            ],
            "itemsize": 64,
        })

    def as_numpy(self):
        """Zero-copy NumPy structured scalar view over the bound window.

        The returned void scalar ALIASES the bound buffer: mutations of the
        buffer are visible in the view and (for writable buffers) writes
        through the view mutate the buffer. No bytes are copied (Law 1).
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.frombuffer(self._buf, dtype=TelemetryFrame.dtype(), count=1, offset=self._offset)[0]

