"""AUTO-GENERATED by weftc-managed/1.0.0 (python) — DO NOT EDIT.

Source IR: tools/weftc/schema/fixtures/weft_envelope.json (irVersion 1) · struct WeftEnvelope · 16 B · little-endian
Regenerate: node tools/weftc/weftc.mjs --ir <schema.json> --target py
Layout is normative; hand edits will be overwritten and drift will fail CI.

Zero-copy managed view (Pillar 1): bind() projects a bytes-like window
without copying; every struct format is explicitly little-endian (Law 2).
"""

from __future__ import annotations

import struct

try:  # NumPy is optional; the struct path is fully functional without it.
    import numpy as _np
except ImportError:  # pragma: no cover - exercised only on minimal installs
    _np = None

__all__ = ["WeftEnvelope"]

_STRUCT_U32 = struct.Struct("<I")
_VERSION_S = struct.Struct("<H")
_HEADER_SIZE_S = struct.Struct("<H")
_SEQ_S = struct.Struct("<I")
_PAYLOAD_LEN_S = struct.Struct("<I")


class WeftEnvelope:
    """
    The triad-1 wire envelope per docs 03-ENVELOPE and core/c/weft.h. Byte-layout and validation semantics are normative: [0..4) magic 'WEFT', [4..6) version u16, [6..8) header_size u16, [8..12) seq u32, [12..16) payload_len u32. validateHeader() mirrors weft_envelope_decode() as a non-throwing boolean handshake (Law 4).
    """
    BYTE_LENGTH = 16
    SCHEMA_VERSION = 1
    MIN_HEADER_SIZE = 16  # normative triad-1 minimum (03-ENVELOPE §2)
    MAGIC_OFFSET = 0  # u8[4]
    VERSION_OFFSET = 4  # u16
    HEADER_SIZE_OFFSET = 6  # u16
    SEQ_OFFSET = 8  # u32
    PAYLOAD_LEN_OFFSET = 12  # u32

    __slots__ = ("_buf", "_offset")

    def __init__(self) -> None:
        self._buf = None
        self._offset = 0

    @property
    def bound(self) -> bool:
        """True once bound."""
        return self._buf is not None

    @property
    def offset(self) -> int:
        """Byte offset this view is bound at (relative to the bound object)."""
        return self._offset

    def bind(self, buf, offset: int = 0):
        """Bind to a bytes-like object (bytes/bytearray/memoryview/ndarray).

        Zero-copy: the bytes are referenced, never duplicated. Rebinding one
        instance per frame is the steady-state pattern (Law 1). Writable
        buffers (bytearray, writable ndarray) unlock the setter path.
        """
        mv = memoryview(buf)
        if mv.itemsize != 1 or mv.ndim != 1:
            mv = mv.cast("B")  # normalize to a flat byte view (no data copy)
        if offset < 0 or offset + WeftEnvelope.BYTE_LENGTH > mv.nbytes:
            raise ValueError("WeftEnvelope.bind: window [%d..%d) exceeds buffer of %d bytes" % (offset, offset + WeftEnvelope.BYTE_LENGTH, mv.nbytes))
        self._buf = mv
        self._offset = offset
        return self

    def validate_header(self, avail=None) -> bool:
        """Non-throwing Law 4 handshake: bounds + consts (+ payload avail)."""
        if self._buf is None:
            return False
        base = self._offset
        if self._buf[base + 0] != 87:  # "W"
            return False
        if self._buf[base + 1] != 69:  # "E"
            return False
        if self._buf[base + 2] != 70:  # "F"
            return False
        if self._buf[base + 3] != 84:  # "T"
            return False
        if _VERSION_S.unpack_from(self._buf, base + 4)[0] != 1:
            return False
        if _HEADER_SIZE_S.unpack_from(self._buf, base + 6)[0] != 16:
            return False
        if avail is not None:
            hs = _HEADER_SIZE_S.unpack_from(self._buf, base + 6)[0]
            pl = _PAYLOAD_LEN_S.unpack_from(self._buf, base + 12)[0]
            if hs < self.MIN_HEADER_SIZE or hs > avail:
                return False
            if pl > avail - hs:  # payload bytes must exist (kernel SHORT)
                return False
        return True


    # ASCII 'WEFT' frame magic.
    # @byteOffset 0x0 (u8[4])
    def get_magic_at(self, index: int):
        return self._buf[self._offset + 0 + index * 1]

    # Envelope wire version (triad-1 = 1).
    # @byteOffset 0x4 (u16)
    @property
    def version(self):
        return _VERSION_S.unpack_from(self._buf, self._offset + 4)[0]

    # Total header size; payload begins at this offset, NEVER at 16 (L8b extensible headers).
    # @byteOffset 0x6 (u16)
    @property
    def header_size(self):
        return _HEADER_SIZE_S.unpack_from(self._buf, self._offset + 6)[0]

    # Monotonic frame sequence number; mirrors the buffer canary.
    # @byteOffset 0x8 (u32)
    @property
    def seq(self):
        return _SEQ_S.unpack_from(self._buf, self._offset + 8)[0]

    @seq.setter
    def seq(self, value):
        _SEQ_S.pack_into(self._buf, self._offset + 8, value)

    def with_seq(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.seq = value
        return self

    # Payload byte length starting at headerSize.
    # @byteOffset 0xc (u32)
    @property
    def payload_len(self):
        return _PAYLOAD_LEN_S.unpack_from(self._buf, self._offset + 12)[0]

    @payload_len.setter
    def payload_len(self, value):
        _PAYLOAD_LEN_S.pack_into(self._buf, self._offset + 12, value)

    def with_payload_len(self, value):
        """Fluent mutator — returns self, no buffer copies (Law 1)."""
        self.payload_len = value
        return self

    @classmethod
    def dtype(cls):
        """NumPy structured dtype — explicit offsets + itemsize, gap-exact.

        Byte order is explicit little-endian (Law 2); layout is byte-exact
        with the IR and with C/Rust/GPU buffers.
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.dtype({
            "names": [
                "magic",
                "version",
                "header_size",
                "seq",
                "payload_len",
            ],
            "formats": [
                ("u1", (4,)),
                "<u2",
                "<u2",
                "<u4",
                "<u4",
            ],
            "offsets": [
                0,
                4,
                6,
                8,
                12,
            ],
            "itemsize": 16,
        })

    def as_numpy(self):
        """Zero-copy NumPy structured scalar view over the bound window.

        The returned void scalar ALIASES the bound buffer: mutations of the
        buffer are visible in the view and (for writable buffers) writes
        through the view mutate the buffer. No bytes are copied (Law 1).
        """
        if _np is None:
            raise RuntimeError("numpy is not available; struct accessors remain usable")
        return _np.frombuffer(self._buf, dtype=WeftEnvelope.dtype(), count=1, offset=self._offset)[0]

