// AUTO-GENERATED by weftc-managed/1.0.0 (swift) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct ImuSample · 32 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/imu_sample.json --target swift
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import Foundation

/// Flyweight view over ImuSample — zero-copy managed projection.
/// Header-less 32-byte lean payload: exercises the no-handshake validateHeader() path (bounds check only) and proves backends emit correct code when no const/role fields exist.
///
/// Layout (little-endian):
///   0x00  u64  timestampNs
///   0x08  f32[3]  accel
///   0x14  f32[3]  gyro
///
/// Steady-state reads and writes allocate nothing (Law 1): create once,
/// then bind(_:) for every frame. All multi-byte access decodes with
/// explicit little-endian conversion (Law 2) — correct on any host.
public final class ImuSample {
    public static let byteLength: Int = 32
    /// @byteOffset 0 (u64)
    public static let timestampNsOffset: Int = 0
    /// @byteOffset 8 (f32[3])
    public static let accelOffset: Int = 8
    /// @byteOffset 20 (f32[3])
    public static let gyroOffset: Int = 20

    public private(set) var base: UnsafeRawBufferPointer?
    /// Absolute byte offset within the underlying buffer.
    public private(set) var byteOffset: Int = 0

    public var isBound: Bool { base != nil }

    public init() {}

    /// COLD PATH — bind to a raw memory window (mmap region, shared
    /// memory, Data.withUnsafeBytes). Zero copy; rebinds in place.
    @discardableResult
    public func bind(_ buffer: UnsafeRawBufferPointer, byteOffset: Int = 0) -> Self {
        precondition(byteOffset >= 0 && byteOffset + Self.byteLength <= buffer.count,
                     "ImuSample.bind: window [\(byteOffset)..\(byteOffset + Self.byteLength)) exceeds \(buffer.count) bytes")
        if let start = buffer.baseAddress {
            self.base = UnsafeRawBufferPointer(start: start.advanced(by: byteOffset), count: Self.byteLength)
        } else {
            self.base = UnsafeRawBufferPointer(start: nil, count: 0)
        }
        self.byteOffset = byteOffset
        return self
    }

    /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
    public func validateHeader(avail: Int? = nil) -> Bool {
        guard let b = base else { return false }
        _ = b
        return true
    }

    // MARK: raw load/store helpers (hot path; allocation-free)

    @inline(__always)
    private func raw<T>(_ type: T.Type, at offset: Int) -> T {
        base!.loadUnaligned(fromByteOffset: offset, as: type)
    }

    @inline(__always)
    private func store<T>(_ value: T, at offset: Int) {
        base!.storeBytes(of: value, toByteOffset: offset, as: T.self)
    }

    /// Monotonic hardware timestamp, nanoseconds.
    /// @byteOffset 0x00 (u64)
    @inline(__always)
    public var timestampNs: UInt64 {
        raw(UInt64.self, at: 0).littleEndian
    }

    @inline(__always)
    public func setTimestampNs(_ value: UInt64) {
        store(value.littleEndian, at: 0)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withTimestampNs(_ value: UInt64) -> Self {
        setTimestampNs(value)
        return self
    }

    /// Low 32 bits of timestampNs @0x0 (UInt32 LE) — primitive-only path.
    public var timestampNsLo: UInt32 { raw(UInt32.self, at: 0).littleEndian }
    /// High 32 bits of timestampNs @0x4 (UInt32 LE).
    public var timestampNsHi: UInt32 { raw(UInt32.self, at: 4).littleEndian }
    public func setTimestampNsLo(_ value: UInt32) { store(value.littleEndian, at: 0) }
    public func setTimestampNsHi(_ value: UInt32) { store(value.littleEndian, at: 4) }
    @discardableResult
    public func withTimestampNsLo(_ value: UInt32) -> Self { setTimestampNsLo(value); return self }
    @discardableResult
    public func withTimestampNsHi(_ value: UInt32) -> Self { setTimestampNsHi(value); return self }

    /// Linear acceleration, g.
    /// @byteOffset 0x08 (f32[3])
    @inline(__always)
    public func getAccel(at index: Int) -> Float {
        Float(bitPattern: raw(UInt32.self, at: 8 + index * 4).littleEndian)
    }

    public func setAccel(at index: Int, _ value: Float) {
        store(value.bitPattern.littleEndian, at: 8 + index * 4)
    }
    @discardableResult
    public func withAccel(at index: Int, _ value: Float) -> Self {
        setAccel(at: index, value)
        return self
    }

    /// Apple Silicon vector mapping — element decode is little-endian.
    public var accelSIMD: SIMD3<Float> {
        SIMD3<Float>(getAccel(at: 0), getAccel(at: 1), getAccel(at: 2))
    }

    /// Writes the vector's components little-endian, element order 0..<3.
    public func setAccel(_ value: SIMD3<Float>) {
        setAccel(at: 0, value.x)
        setAccel(at: 1, value.y)
        setAccel(at: 2, value.z)
    }
    @discardableResult
    public func withAccel(_ value: SIMD3<Float>) -> Self {
        setAccel(value)
        return self
    }

    /// Angular rate, rad/s.
    /// @byteOffset 0x14 (f32[3])
    @inline(__always)
    public func getGyro(at index: Int) -> Float {
        Float(bitPattern: raw(UInt32.self, at: 20 + index * 4).littleEndian)
    }

    public func setGyro(at index: Int, _ value: Float) {
        store(value.bitPattern.littleEndian, at: 20 + index * 4)
    }
    @discardableResult
    public func withGyro(at index: Int, _ value: Float) -> Self {
        setGyro(at: index, value)
        return self
    }

    /// Apple Silicon vector mapping — element decode is little-endian.
    public var gyroSIMD: SIMD3<Float> {
        SIMD3<Float>(getGyro(at: 0), getGyro(at: 1), getGyro(at: 2))
    }

    /// Writes the vector's components little-endian, element order 0..<3.
    public func setGyro(_ value: SIMD3<Float>) {
        setGyro(at: 0, value.x)
        setGyro(at: 1, value.y)
        setGyro(at: 2, value.z)
    }
    @discardableResult
    public func withGyro(_ value: SIMD3<Float>) -> Self {
        setGyro(value)
        return self
    }
}
