// AUTO-GENERATED by weftc-managed/1.0.0 (swift) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/telemetry_frame.json (irVersion 1) · struct TelemetryFrame · 64 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/telemetry_frame.json --target swift
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import Foundation

/// Flyweight view over TelemetryFrame — zero-copy managed projection.
/// Canonical 64-byte payload schema used across all managed backends for parity fixtures. Designed as the payload of a triad-1 envelope (bind at envelope.headerSize). Every numeric field is naturally aligned; all values in golden fixtures are exactly representable (dyadic) so cross-language comparisons are bit-exact.
///
/// Layout (little-endian):
///   0x00  u64  schemaId
///   0x08  u64  timestampNs
///   0x10  f32[3]  velocity
///   0x1c  f32  pressurePa
///   0x20  u8  state
///   0x21  u8[3]  reserved
///   0x28  f64[2]  gpsCoordinates
///   0x38  u8[8]  payloadHash
///
/// Steady-state reads and writes allocate nothing (Law 1): create once,
/// then bind(_:) for every frame. All multi-byte access decodes with
/// explicit little-endian conversion (Law 2) — correct on any host.
public final class TelemetryFrame {
    public static let byteLength: Int = 64
    public static let schemaID: UInt64 = 0x8F4C1120A9B30012
    public static let schemaVersion: Int = 3
    /// @byteOffset 0 (u64)
    public static let schemaIdOffset: Int = 0
    /// @byteOffset 8 (u64)
    public static let timestampNsOffset: Int = 8
    /// @byteOffset 16 (f32[3])
    public static let velocityOffset: Int = 16
    /// @byteOffset 28 (f32)
    public static let pressurePaOffset: Int = 28
    /// @byteOffset 32 (u8)
    public static let stateOffset: Int = 32
    /// @byteOffset 33 (u8[3])
    public static let reservedOffset: Int = 33
    /// @byteOffset 40 (f64[2])
    public static let gpsCoordinatesOffset: Int = 40
    /// @byteOffset 56 (u8[8])
    public static let payloadHashOffset: Int = 56

    public private(set) var base: UnsafeRawBufferPointer?
    /// Absolute byte offset within the underlying buffer.
    public private(set) var byteOffset: Int = 0

    public var isBound: Bool { base != nil }

    public init() {}

    /// COLD PATH — bind to a raw memory window (mmap region, shared
    /// memory, Data.withUnsafeBytes). Zero copy; rebinds in place.
    @discardableResult
    public func bind(_ buffer: UnsafeRawBufferPointer, byteOffset: Int = 0) -> Self {
        precondition(byteOffset >= 0 && byteOffset + Self.byteLength <= buffer.count,
                     "TelemetryFrame.bind: window [\(byteOffset)..\(byteOffset + Self.byteLength)) exceeds \(buffer.count) bytes")
        if let start = buffer.baseAddress {
            self.base = UnsafeRawBufferPointer(start: start.advanced(by: byteOffset), count: Self.byteLength)
        } else {
            self.base = UnsafeRawBufferPointer(start: nil, count: 0)
        }
        self.byteOffset = byteOffset
        return self
    }

    /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
    public func validateHeader(avail: Int? = nil) -> Bool {
        guard let b = base else { return false }
        _ = b
        guard b.loadUnaligned(fromByteOffset: 0, as: UInt64.self).littleEndian == UInt64(0x8F4C1120A9B30012) else { return false }
        return true
    }

    // MARK: raw load/store helpers (hot path; allocation-free)

    @inline(__always)
    private func raw<T>(_ type: T.Type, at offset: Int) -> T {
        base!.loadUnaligned(fromByteOffset: offset, as: type)
    }

    @inline(__always)
    private func store<T>(_ value: T, at offset: Int) {
        base!.storeBytes(of: value, toByteOffset: offset, as: T.self)
    }

    /// Payload schema handshake; checked by validateHeader() before any field read (Law 4).
    /// @byteOffset 0x00 (u64)
    @inline(__always)
    public var schemaId: UInt64 {
        raw(UInt64.self, at: 0).littleEndian
    }

    /// Low 32 bits of schemaId @0x0 (UInt32 LE) — primitive-only path.
    public var schemaIdLo: UInt32 { raw(UInt32.self, at: 0).littleEndian }
    /// High 32 bits of schemaId @0x4 (UInt32 LE).
    public var schemaIdHi: UInt32 { raw(UInt32.self, at: 4).littleEndian }

    /// Monotonic hardware timestamp, nanoseconds.
    /// @byteOffset 0x08 (u64)
    @inline(__always)
    public var timestampNs: UInt64 {
        raw(UInt64.self, at: 8).littleEndian
    }

    @inline(__always)
    public func setTimestampNs(_ value: UInt64) {
        store(value.littleEndian, at: 8)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withTimestampNs(_ value: UInt64) -> Self {
        setTimestampNs(value)
        return self
    }

    /// Low 32 bits of timestampNs @0x8 (UInt32 LE) — primitive-only path.
    public var timestampNsLo: UInt32 { raw(UInt32.self, at: 8).littleEndian }
    /// High 32 bits of timestampNs @0xc (UInt32 LE).
    public var timestampNsHi: UInt32 { raw(UInt32.self, at: 12).littleEndian }
    public func setTimestampNsLo(_ value: UInt32) { store(value.littleEndian, at: 8) }
    public func setTimestampNsHi(_ value: UInt32) { store(value.littleEndian, at: 12) }
    @discardableResult
    public func withTimestampNsLo(_ value: UInt32) -> Self { setTimestampNsLo(value); return self }
    @discardableResult
    public func withTimestampNsHi(_ value: UInt32) -> Self { setTimestampNsHi(value); return self }

    /// Velocity vector, m/s. Maps to SIMD3<Float> / vector_float3 on Apple platforms.
    /// @byteOffset 0x10 (f32[3])
    @inline(__always)
    public func getVelocity(at index: Int) -> Float {
        Float(bitPattern: raw(UInt32.self, at: 16 + index * 4).littleEndian)
    }

    public func setVelocity(at index: Int, _ value: Float) {
        store(value.bitPattern.littleEndian, at: 16 + index * 4)
    }
    @discardableResult
    public func withVelocity(at index: Int, _ value: Float) -> Self {
        setVelocity(at: index, value)
        return self
    }

    /// Apple Silicon vector mapping — element decode is little-endian.
    public var velocitySIMD: SIMD3<Float> {
        SIMD3<Float>(getVelocity(at: 0), getVelocity(at: 1), getVelocity(at: 2))
    }

    /// Writes the vector's components little-endian, element order 0..<3.
    public func setVelocity(_ value: SIMD3<Float>) {
        setVelocity(at: 0, value.x)
        setVelocity(at: 1, value.y)
        setVelocity(at: 2, value.z)
    }
    @discardableResult
    public func withVelocity(_ value: SIMD3<Float>) -> Self {
        setVelocity(value)
        return self
    }

    /// Ambient pressure, Pa.
    /// @byteOffset 0x1c (f32)
    @inline(__always)
    public var pressurePa: Float {
        Float(bitPattern: raw(UInt32.self, at: 28).littleEndian)
    }

    @inline(__always)
    public func setPressurePa(_ value: Float) {
        store(value.bitPattern.littleEndian, at: 28)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withPressurePa(_ value: Float) -> Self {
        setPressurePa(value)
        return self
    }

    /// Device state enum byte.
    /// @byteOffset 0x20 (u8)
    @inline(__always)
    public var state: UInt8 {
        raw(UInt8.self, at: 32)
    }

    @inline(__always)
    public func setState(_ value: UInt8) {
        store(value, at: 32)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withState(_ value: UInt8) -> Self {
        setState(value)
        return self
    }

    /// lat/lon pair, degrees.
    /// @byteOffset 0x28 (f64[2])
    @inline(__always)
    public func getGpsCoordinates(at index: Int) -> Double {
        Double(bitPattern: raw(UInt64.self, at: 40 + index * 8).littleEndian)
    }

    public func setGpsCoordinates(at index: Int, _ value: Double) {
        store(value.bitPattern.littleEndian, at: 40 + index * 8)
    }
    @discardableResult
    public func withGpsCoordinates(at index: Int, _ value: Double) -> Self {
        setGpsCoordinates(at: index, value)
        return self
    }

    /// Truncated payload digest (u8[8]).
    /// @byteOffset 0x38 (u8[8])
    @inline(__always)
    public func getPayloadHash(at index: Int) -> UInt8 {
        raw(UInt8.self, at: 56 + index * 1)
    }

    public func setPayloadHash(at index: Int, _ value: UInt8) {
        store(value, at: 56 + index * 1)
    }
    @discardableResult
    public func withPayloadHash(at index: Int, _ value: UInt8) -> Self {
        setPayloadHash(at: index, value)
        return self
    }
}
