// AUTO-GENERATED by weftc-managed/1.0.0 (swift) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/weft_envelope.json (irVersion 1) · struct WeftEnvelope · 16 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/weft_envelope.json --target swift
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import Foundation

/// Flyweight view over WeftEnvelope — zero-copy managed projection.
/// The triad-1 wire envelope per docs 03-ENVELOPE and core/c/weft.h. Byte-layout and validation semantics are normative: [0..4) magic 'WEFT', [4..6) version u16, [6..8) header_size u16, [8..12) seq u32, [12..16) payload_len u32. validateHeader() mirrors weft_envelope_decode() as a non-throwing boolean handshake (Law 4).
///
/// Layout (little-endian):
///   0x00  u8[4]  magic
///   0x04  u16  version
///   0x06  u16  headerSize
///   0x08  u32  seq
///   0x0c  u32  payloadLen
///
/// Steady-state reads and writes allocate nothing (Law 1): create once,
/// then bind(_:) for every frame. All multi-byte access decodes with
/// explicit little-endian conversion (Law 2) — correct on any host.
public final class WeftEnvelope {
    public static let byteLength: Int = 16
    public static let schemaVersion: Int = 1
    /// Normative triad-1 minimum header size (03-ENVELOPE §2).
    public static let minHeaderSize: Int = 16
    /// @byteOffset 0 (u8[4])
    public static let magicOffset: Int = 0
    /// @byteOffset 4 (u16)
    public static let versionOffset: Int = 4
    /// @byteOffset 6 (u16)
    public static let headerSizeOffset: Int = 6
    /// @byteOffset 8 (u32)
    public static let seqOffset: Int = 8
    /// @byteOffset 12 (u32)
    public static let payloadLenOffset: Int = 12

    public private(set) var base: UnsafeRawBufferPointer?
    /// Absolute byte offset within the underlying buffer.
    public private(set) var byteOffset: Int = 0

    public var isBound: Bool { base != nil }

    public init() {}

    /// COLD PATH — bind to a raw memory window (mmap region, shared
    /// memory, Data.withUnsafeBytes). Zero copy; rebinds in place.
    @discardableResult
    public func bind(_ buffer: UnsafeRawBufferPointer, byteOffset: Int = 0) -> Self {
        precondition(byteOffset >= 0 && byteOffset + Self.byteLength <= buffer.count,
                     "WeftEnvelope.bind: window [\(byteOffset)..\(byteOffset + Self.byteLength)) exceeds \(buffer.count) bytes")
        if let start = buffer.baseAddress {
            self.base = UnsafeRawBufferPointer(start: start.advanced(by: byteOffset), count: Self.byteLength)
        } else {
            self.base = UnsafeRawBufferPointer(start: nil, count: 0)
        }
        self.byteOffset = byteOffset
        return self
    }

    /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
    public func validateHeader(avail: Int? = nil) -> Bool {
        guard let b = base else { return false }
        _ = b
        guard b.load(fromByteOffset: 0, as: UInt8.self) == 87 else { return false } // "W"
        guard b.load(fromByteOffset: 1, as: UInt8.self) == 69 else { return false } // "E"
        guard b.load(fromByteOffset: 2, as: UInt8.self) == 70 else { return false } // "F"
        guard b.load(fromByteOffset: 3, as: UInt8.self) == 84 else { return false } // "T"
        guard b.loadUnaligned(fromByteOffset: 4, as: UInt16.self).littleEndian == UInt16(1) else { return false }
        guard b.loadUnaligned(fromByteOffset: 6, as: UInt16.self).littleEndian == UInt16(16) else { return false }
        if let avail = avail {
            let hs = Int(b.loadUnaligned(fromByteOffset: 6, as: UInt16.self).littleEndian)
            let pl = Int(b.loadUnaligned(fromByteOffset: 12, as: UInt32.self).littleEndian)
            if hs < Self.minHeaderSize || hs > avail { return false }
            if pl > avail - hs { return false } // payload bytes must exist (kernel SHORT)
        }
        return true
    }

    // MARK: raw load/store helpers (hot path; allocation-free)

    @inline(__always)
    private func raw<T>(_ type: T.Type, at offset: Int) -> T {
        base!.loadUnaligned(fromByteOffset: offset, as: type)
    }

    @inline(__always)
    private func store<T>(_ value: T, at offset: Int) {
        base!.storeBytes(of: value, toByteOffset: offset, as: T.self)
    }

    /// ASCII 'WEFT' frame magic.
    /// @byteOffset 0x00 (u8[4])
    @inline(__always)
    public func getMagic(at index: Int) -> UInt8 {
        raw(UInt8.self, at: 0 + index * 1)
    }

    /// Envelope wire version (triad-1 = 1).
    /// @byteOffset 0x04 (u16)
    @inline(__always)
    public var version: UInt16 {
        raw(UInt16.self, at: 4).littleEndian
    }

    /// Total header size; payload begins at this offset, NEVER at 16 (L8b extensible headers).
    /// @byteOffset 0x06 (u16)
    @inline(__always)
    public var headerSize: UInt16 {
        raw(UInt16.self, at: 6).littleEndian
    }

    /// Monotonic frame sequence number; mirrors the buffer canary.
    /// @byteOffset 0x08 (u32)
    @inline(__always)
    public var seq: UInt32 {
        raw(UInt32.self, at: 8).littleEndian
    }

    @inline(__always)
    public func setSeq(_ value: UInt32) {
        store(value.littleEndian, at: 8)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withSeq(_ value: UInt32) -> Self {
        setSeq(value)
        return self
    }

    /// Payload byte length starting at headerSize.
    /// @byteOffset 0x0c (u32)
    @inline(__always)
    public var payloadLen: UInt32 {
        raw(UInt32.self, at: 12).littleEndian
    }

    @inline(__always)
    public func setPayloadLen(_ value: UInt32) {
        store(value.littleEndian, at: 12)
    }

    /// Fluent mutator — returns self, allocates nothing (Law 1).
    @discardableResult
    public func withPayloadLen(_ value: UInt32) -> Self {
        setPayloadLen(value)
        return self
    }
}
