#!/usr/bin/env node
// gen.mjs — weftc Python backend (`--target=py`).
//
// Emits, per IR struct, a Python module `<snake_name>.py` containing a
// zero-copy flyweight view class:
//   - bind(buf, offset) rebinds in place (flyweight; no per-frame objects)
//   - struct.Struct('<...') accessors — explicit little-endian (Law 2)
//   - u64 fields get _lo/_hi u32 split properties (Python ints, exact)
//   - DTYPE: NumPy structured dtype with EXPLICIT offsets + itemsize
//     (gap-exact with the IR byte layout) — np.frombuffer zero-copy view
//   - validate_header(avail?): Law 4 handshake; envelope schemas mirror
//     kernel weft_envelope_decode() semantics
//
// Zero-copy honesty (Law 1, Python edition): the BYTES are never duplicated
// (memoryview projection; NumPy views alias the bound buffer). Python-level
// container objects (tuples returned by struct.unpack) are unavoidable at
// language level; the hot scalar path returns bare int/float primitives.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseIrJson } from '../lib/ir.mjs';
import { PY_FMT, NP_DTYPE } from '../lib/types.mjs';
import { banner, docComment } from '../lib/emitter.mjs';
import { snake, screaming, safeIdent } from '../lib/names.mjs';

const GENERATOR = 'weftc-managed/1.0.0';

function stableIrPath(p) {
  const i = p.lastIndexOf('tools/weftc/');
  return i >= 0 ? p.slice(i) : p;
}

function snakeName(name) {
  return snake(name);
}

function pyClassName(name) {
  // IR names are PascalCase already.
  return name;
}

const SUFFIX = '_S'; // per-field Struct constant suffix

function structConstName(fieldName) {
  return `_${screaming(fieldName)}${SUFFIX}`;
}

function renderModule(ir, irPath) {
  const cls = pyClassName(ir.name);
  const fields = ir.fields.filter((f) => f.role !== 'reserved');
  const hasHeaderSize = ir.fields.some((f) => f.role === 'headerSize');
  const hasPayloadLen = ir.fields.some((f) => f.role === 'payloadLen');

  const L = [];
  // Module docstring banner (Python flavor of the deterministic banner).
  L.push(`"""AUTO-GENERATED by ${GENERATOR} (python) — DO NOT EDIT.`);
  L.push('');
  L.push(`Source IR: ${stableIrPath(irPath)} (irVersion 1) · struct ${ir.name} · ${ir.byteLength} B · ${ir.endian}-endian`);
  L.push('Regenerate: node tools/weftc/weftc.mjs --ir <schema.json> --target py');
  L.push('Layout is normative; hand edits will be overwritten and drift will fail CI.');
  L.push('');
  L.push('Zero-copy managed view (Pillar 1): bind() projects a bytes-like window');
  L.push('without copying; every struct format is explicitly little-endian (Law 2).');
  L.push('"""');
  L.push('');
  L.push('from __future__ import annotations');
  L.push('');
  L.push('import struct');
  L.push('');
  L.push('try:  # NumPy is optional; the struct path is fully functional without it.');
  L.push('    import numpy as _np');
  L.push('except ImportError:  # pragma: no cover - exercised only on minimal installs');
  L.push('    _np = None');
  L.push('');
  L.push('__all__ = ["' + cls + '"]');
  L.push('');
  L.push(`_STRUCT_U32 = struct.Struct("<I")`);
  // Per-field structs (Law 2: '<' prefix on every format).
  for (const f of ir.fields) {
    if (f.role === 'reserved') continue;
    if (f.count > 1 && f.type === 'u8') continue; // byte arrays read by index
    if (f.count > 1) {
      // element struct for per-index access + bulk struct for _all()
      L.push(`${structConstName(f.name)}_E = struct.Struct("<${PY_FMT[f.type]}")`);
      L.push(`${structConstName(f.name)} = struct.Struct("<${f.count}${PY_FMT[f.type]}")`);
    } else {
      L.push(`${structConstName(f.name)} = struct.Struct("<${PY_FMT[f.type]}")`);
    }
  }
  L.push('');
  L.push('');
  L.push(`class ${cls}:`);
  if (ir.doc) {
    L.push(`    """`);
    for (const l of docComment(ir.doc, '    ')) L.push(l);
    L.push('    """');
  }
  // class constants
  L.push(`    BYTE_LENGTH = ${ir.byteLength}`);
  if (ir.schemaId !== null) {
    L.push(`    SCHEMA_ID = 0x${ir.schemaId.toString(16).toUpperCase()}`);
  }
  if (ir.schemaVersion !== null) {
    L.push(`    SCHEMA_VERSION = ${ir.schemaVersion}`);
  }
  if (hasHeaderSize) {
    L.push('    MIN_HEADER_SIZE = 16  # normative triad-1 minimum (03-ENVELOPE §2)');
  }
  for (const f of ir.fields) {
    const arr = f.count > 1 ? `[${f.count}]` : '';
    L.push(`    ${screaming(f.name)}_OFFSET = ${f.offset}  # ${f.type}${arr}`);
  }
  L.push('');
  L.push('    __slots__ = ("_buf", "_offset")');
  L.push('');
  L.push('    def __init__(self) -> None:');
  L.push('        self._buf = None');
  L.push('        self._offset = 0');
  L.push('');
  L.push('    @property');
  L.push('    def bound(self) -> bool:');
  L.push('        """True once bound."""');
  L.push('        return self._buf is not None');
  L.push('');
  L.push('    @property');
  L.push('    def offset(self) -> int:');
  L.push('        """Byte offset this view is bound at (relative to the bound object)."""');
  L.push('        return self._offset');
  L.push('');
  L.push('    def bind(self, buf, offset: int = 0):');
  L.push('        """Bind to a bytes-like object (bytes/bytearray/memoryview/ndarray).');
  L.push('');
  L.push('        Zero-copy: the bytes are referenced, never duplicated. Rebinding one');
  L.push('        instance per frame is the steady-state pattern (Law 1). Writable');
  L.push('        buffers (bytearray, writable ndarray) unlock the setter path.');
  L.push('        """');
  L.push('        mv = memoryview(buf)');
  L.push('        if mv.itemsize != 1 or mv.ndim != 1:');
  L.push('            mv = mv.cast("B")  # normalize to a flat byte view (no data copy)');
  L.push(`        if offset < 0 or offset + ${cls}.BYTE_LENGTH > mv.nbytes:`);
  L.push(`            raise ValueError("${cls}.bind: window [%d..%d) exceeds buffer of %d bytes" % (offset, offset + ${cls}.BYTE_LENGTH, mv.nbytes))`);
  L.push('        self._buf = mv');
  L.push('        self._offset = offset');
  L.push('        return self');
  L.push('');
  L.push('    def validate_header(self, avail=None) -> bool:');
  L.push('        """Non-throwing Law 4 handshake: bounds + consts (+ payload avail)."""');
  L.push('        if self._buf is None:');
  L.push('            return False');
  L.push('        base = self._offset');
  for (const f of ir.fields) {
    if (f.role === 'reserved') continue;
    if (!f.const) continue;
    if (f.count > 1 && f.type === 'u8' && f.const.kind === 'bytes') {
      for (let i = 0; i < f.const.bytes.length; i++) {
        const ch = String.fromCharCode(f.const.bytes[i]);
        L.push(`        if self._buf[base + ${f.offset + i}] != ${f.const.bytes[i]}:  # "${ch}"`);
        L.push('            return False');
      }
    } else if (f.type === 'u8' || f.type === 'bool') {
      L.push(`        if self._buf[base + ${f.offset}] != ${f.const.value}:`);
      L.push('            return False');
    } else {
      const cv = typeof f.const.value === 'bigint' ? `0x${f.const.value.toString(16)}` : JSON.stringify(f.const.value);
      L.push(`        if ${structConstName(f.name)}.unpack_from(self._buf, base + ${f.offset})[0] != ${cv}:`);
      L.push('            return False');
    }
  }
  if (hasHeaderSize && hasPayloadLen) {
    const hs = ir.fields.find((f) => f.role === 'headerSize');
    const pl = ir.fields.find((f) => f.role === 'payloadLen');
    L.push('        if avail is not None:');
    L.push(`            hs = ${structConstName(hs.name)}.unpack_from(self._buf, base + ${hs.offset})[0]`);
    L.push(`            pl = ${structConstName(pl.name)}.unpack_from(self._buf, base + ${pl.offset})[0]`);
    L.push('            if hs < self.MIN_HEADER_SIZE or hs > avail:');
    L.push('                return False');
    L.push('            if pl > avail - hs:  # payload bytes must exist (kernel SHORT)');
    L.push('                return False');
  }
  L.push('        return True');
  L.push('');

  for (const f of fields) {
    const ident = safeIdent(snake(f.name), 'python');
    const o = f.offset;
    const isArray = f.count > 1;
    const isBytes = isArray && f.type === 'u8';
    L.push('');
    if (f.doc) for (const l of docComment(f.doc, '    # ')) L.push(l);
    L.push(`    # @byteOffset 0x${o.toString(16)} (${f.type}${isArray ? `[${f.count}]` : ''})`);
    if (!isArray) {
      const st = structConstName(f.name);
      const getExpr = f.type === 'bool'
        ? `${st}.unpack_from(self._buf, self._offset + ${o})[0] != 0`
        : `${st}.unpack_from(self._buf, self._offset + ${o})[0]`;
      L.push('    @property');
      L.push(`    def ${ident}(self):`);
      L.push(`        return ${getExpr}`);
      if (!f.const) {
        L.push('');
        L.push(`    @${ident}.setter`);
        L.push(`    def ${ident}(self, value):`);
        if (f.type === 'bool') {
          L.push(`        ${st}.pack_into(self._buf, self._offset + ${o}, 1 if value else 0)`);
        } else {
          L.push(`        ${st}.pack_into(self._buf, self._offset + ${o}, value)`);
        }
        L.push('');
        L.push(`    def with_${ident}(self, value):`);
        L.push(`        """Fluent mutator — returns self, no buffer copies (Law 1)."""`);
        L.push(`        self.${ident} = value`);
        L.push('        return self');
      }
      if (f.type === 'u64' || f.type === 'i64') {
        // u32 split: primitive ints, exact, hot-path friendly.
        L.push('');
        L.push(`    @property`);
        L.push(`    def ${ident}_lo(self) -> int:`);
        L.push(`        return _STRUCT_U32.unpack_from(self._buf, self._offset + ${o})[0]`);
        if (!f.const) {
          L.push('');
          L.push(`    @${ident}_lo.setter`);
          L.push(`    def ${ident}_lo(self, value):`);
          L.push(`        _STRUCT_U32.pack_into(self._buf, self._offset + ${o}, value)`);
        }
        L.push('');
        L.push(`    @property`);
        L.push(`    def ${ident}_hi(self) -> int:`);
        L.push(`        return _STRUCT_U32.unpack_from(self._buf, self._offset + ${o + 4})[0]`);
        if (!f.const) {
          L.push('');
          L.push(`    @${ident}_hi.setter`);
          L.push(`    def ${ident}_hi(self, value):`);
          L.push(`        _STRUCT_U32.pack_into(self._buf, self._offset + ${o + 4}, value)`);
          L.push('');
          L.push(`    def with_${ident}_lo(self, value):`);
          L.push(`        """Fluent mutator for the low 32 bits — returns self."""`);
          L.push(`        _STRUCT_U32.pack_into(self._buf, self._offset + ${o}, value)`);
          L.push('        return self');
          L.push('');
          L.push(`    def with_${ident}_hi(self, value):`);
          L.push(`        """Fluent mutator for the high 32 bits — returns self."""`);
          L.push(`        _STRUCT_U32.pack_into(self._buf, self._offset + ${o + 4}, value)`);
          L.push('        return self');
        }
      }
    } else {
      const stride = Math.round(f.size / f.count);
      if (isBytes) {
        const getExpr = f.type === 'bool'
          ? `self._buf[self._offset + ${o} + index * ${stride}] != 0`
          : `self._buf[self._offset + ${o} + index * ${stride}]`;
        L.push(`    def get_${ident}_at(self, index: int):`);
        L.push(`        return ${getExpr}`);
        if (!f.const) {
          L.push('');
          L.push(`    def set_${ident}_at(self, index: int, value):`);
          if (f.type === 'bool') {
            L.push(`        self._buf[self._offset + ${o} + index * ${stride}] = 1 if value else 0`);
          } else {
            L.push(`        self._buf[self._offset + ${o} + index * ${stride}] = value`);
          }
          L.push('');
          L.push(`    def with_${ident}_at(self, index: int, value):`);
          L.push(`        self.set_${ident}_at(index, value)`);
          L.push('        return self');
        }
      } else {
        const stE = `${structConstName(f.name)}_E`;
        const offExpr = `self._offset + ${o} + index * ${stride}`;
        const getExpr = f.type === 'bool'
          ? `${stE}.unpack_from(self._buf, ${offExpr})[0] != 0`
          : `${stE}.unpack_from(self._buf, ${offExpr})[0]`;
        L.push(`    def get_${ident}_at(self, index: int):`);
        L.push(`        return ${getExpr}`);
        if (!f.const) {
          L.push('');
          L.push(`    def set_${ident}_at(self, index: int, value):`);
          if (f.type === 'bool') {
            L.push(`        ${stE}.pack_into(self._buf, ${offExpr}, 1 if value else 0)`);
          } else {
            L.push(`        ${stE}.pack_into(self._buf, ${offExpr}, value)`);
          }
          L.push('');
          L.push(`    def with_${ident}_at(self, index: int, value):`);
          L.push(`        self.set_${ident}_at(index, value)`);
          L.push('        return self');
        }
      }
    }
  }

  // Bulk tuple getter for arrays (convenience; allocates a tuple — not hot path).
  for (const f of fields) {
    if (!(f.count > 1 && f.type !== 'u8')) continue;
    const ident = safeIdent(snake(f.name), 'python');
    const st = structConstName(f.name);
    L.push('');
    L.push(`    def get_${ident}_all(self):`);
    L.push(`        """All ${f.count} elements as a tuple (convenience; not the hot path)."""`);
    L.push(`        return ${st}.unpack_from(self._buf, self._offset + ${f.offset})`);
  }

  // NumPy structured view (the canonical zero-copy projection).
  L.push('');
  L.push('    @classmethod');
  L.push('    def dtype(cls):');
  L.push('        """NumPy structured dtype — explicit offsets + itemsize, gap-exact.');
  L.push('');
  L.push('        Byte order is explicit little-endian (Law 2); layout is byte-exact');
  L.push('        with the IR and with C/Rust/GPU buffers.');
  L.push('        """');
  L.push('        if _np is None:');
  L.push('            raise RuntimeError("numpy is not available; struct accessors remain usable")');
  L.push('        return _np.dtype({');
  L.push('            "names": [');
  const names = ir.fields.map((f) => `                "${snake(f.name)}",`);
  L.push(...names);
  L.push('            ],');
  L.push('            "formats": [');
  for (const f of ir.fields) {
    const base = NP_DTYPE[f.type];
    const fmt = f.count > 1 ? `(${JSON.stringify(base)}, (${f.count},))` : JSON.stringify(base);
    L.push(`                ${fmt},`);
  }
  L.push('            ],');
  L.push('            "offsets": [');
  L.push(...ir.fields.map((f) => `                ${f.offset},`));
  L.push('            ],');
  L.push(`            "itemsize": ${ir.byteLength},`);
  L.push('        })');
  L.push('');
  L.push('    def as_numpy(self):');
  L.push('        """Zero-copy NumPy structured scalar view over the bound window.');
  L.push('');
  L.push('        The returned void scalar ALIASES the bound buffer: mutations of the');
  L.push('        buffer are visible in the view and (for writable buffers) writes');
  L.push('        through the view mutate the buffer. No bytes are copied (Law 1).');
  L.push('        """');
  L.push('        if _np is None:');
  L.push('            raise RuntimeError("numpy is not available; struct accessors remain usable")');
  L.push(`        return _np.frombuffer(self._buf, dtype=${cls}.dtype(), count=1, offset=self._offset)[0]`);
  L.push('');
  return L.join('\n') + '\n';
}

/** @returns {{files: Map<string,string>, base: string}} */
export function generatePython(ir, { irPath = 'ir.json' } = {}) {
  const base = snakeName(ir.name);
  const files = new Map([[`${base}.py`, renderModule(ir, irPath)]]);
  return { files, base };
}

// CLI: --ir <path> --out <dir>
function main() {
  const argv = process.argv.slice(2);
  const get = (flag) => {
    const i = argv.indexOf(flag);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const irPathArg = get('--ir');
  const outArg = get('--out');
  if (!irPathArg || !outArg) {
    console.error('usage: node gen.mjs --ir <schema.json> --out <dir>');
    process.exit(2);
  }
  const irPath = resolve(irPathArg);
  const ir = parseIrJson(readFileSync(irPath, 'utf8'));
  const outDir = resolve(outArg);
  mkdirSync(outDir, { recursive: true });
  const { files } = generatePython(ir, { irPath });
  for (const [name, content] of [...files].sort()) {
    const p = join(outDir, name);
    writeFileSync(p, content);
    console.error(`wrote ${p}`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
