//! axis_sample — generated by weftc-codegen 0.1.0 (target: rust). DO NOT EDIT.
//! module: sensors | struct: axis_sample | root: no (embedded layout type)
//! layout: 8 bytes, align 2 — byte-identical with `weft_axis_sample_t` (C) and the
//! byte-exact GPU structs (WGSL storage / GLSL std430).
//!
//! Laws: zero allocation on every path; no_std (`core` only); unaligned
//! access only through read_unaligned/write_unaligned; layout is a
//! compile-time contract via #[repr(C)].
#![allow(dead_code)]

use super::weft_projection_core::WeftError;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AxisSample {
    pub x: i16,
    pub y: i16,
    pub z: i16,
    pub pad: u16,
}

impl AxisSample {
    /// Exact struct size in bytes (weft-ir normative).
    pub const SIZE: usize = 8;
    /// Exact struct alignment in bytes (weft-ir normative).
    pub const ALIGN: usize = 2;

    /// Byte view of this value (host little-endian) — direct
    /// queue.writeBuffer()/vkMapMemory upload source.
    #[inline(always)]
    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {
        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }
    }

    /// Alignment-free by-value read from a possibly-packed source
    /// (Law 3). Trusted-source path: no schema validation — use
    /// from_bytes for untrusted input.
    #[inline]
    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })
    }

    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).
    #[inline]
    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {
        if dst.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }
        Ok(())
    }

    /// Zero-overhead builder: `frame.with_x(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_x(mut self, x: i16) -> Self {
        self.x = x;
        self
    }

    /// Zero-overhead builder: `frame.with_y(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_y(mut self, y: i16) -> Self {
        self.y = y;
        self
    }

    /// Zero-overhead builder: `frame.with_z(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_z(mut self, z: i16) -> Self {
        self.z = z;
        self
    }

    /// Zero-overhead builder: `frame.with_pad(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_pad(mut self, pad: u16) -> Self {
        self.pad = pad;
        self
    }

}

