// axis_sample.glsl — generated by weftc-codegen 0.1.0 (target: glsl). DO NOT EDIT.
// module: sensors | struct: axis_sample
// host layout: 8 bytes, align 2
//
// WEFT-GPU-NOT-EXACT: axis_sample — std430 variant WITHHELD (Law 4)
// reason: field x (scalar): WGSL and GLSL expose no 16-bit integer buffer types; widen to u32 (or keep this struct CPU-side)
// remediation: widen 8/16-bit integers to u32, replace bool with u32
//   flags + bitfields, or keep this struct host-side.
// The refusal is total: no struct is emitted, because a struct with a
// silently-wrong layout is worse than no struct.
