//! sensor_event — generated by weftc-codegen 0.1.0 (target: rust). DO NOT EDIT.
//! module: sensors | struct: sensor_event | root: yes
//! schema_id: 0x4173163A7BD694EC (auto: FNV-1a-64 of the canonical layout signature)
//! layout: 32 bytes, align 8 — byte-identical with `weft_sensor_event_t` (C) and the
//! byte-exact GPU structs (WGSL storage / GLSL std430).
//!
//! Laws: zero allocation on every path; no_std (`core` only); unaligned
//! access only through read_unaligned/write_unaligned; layout is a
//! compile-time contract via #[repr(C)].
#![allow(dead_code)]

use super::weft_projection_core::WeftError;
use super::axis_sample::AxisSample;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SensorEvent {
    pub schema_id: u64,
    pub timestamp_ns: u64,
    pub imu: AxisSample,
    pub quality: u32,
    pub crc32: u32,
}

impl SensorEvent {
    /// 64-bit schema hash header this type projects.
    pub const SCHEMA_ID: u64 = 0x4173_163A_7BD6_94EC;
    /// Exact struct size in bytes (weft-ir normative).
    pub const SIZE: usize = 32;
    /// Exact struct alignment in bytes (weft-ir normative).
    pub const ALIGN: usize = 8;

    /// Zero-copy projection: validates length, alignment and the schema
    /// hash header, then borrows the buffer as `&Self`. No copy, no
    /// allocation (Law 1); the check is three compares + one load.
    #[inline(always)]
    pub fn from_bytes(bytes: &[u8]) -> Result<&Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &*(bytes.as_ptr() as *const Self) })
    }

    /// Mutable twin (writer side: ring slots, UMEM pages).
    #[inline(always)]
    pub fn from_bytes_mut(bytes: &mut [u8]) -> Result<&mut Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &mut *(bytes.as_mut_ptr() as *mut Self) })
    }

    #[inline(always)]
    fn validate_header(bytes: &[u8]) -> Result<(), WeftError> {
        let p = bytes.as_ptr();
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        if (p as usize) & (Self::ALIGN - 1) != 0 {
            return Err(WeftError::BadAlign);
        }
        let id = unsafe { core::ptr::read_unaligned(p as *const u64) };
        if id != Self::SCHEMA_ID {
            return Err(WeftError::SchemaMismatch);
        }
        Ok(())
    }

    /// Byte view of this value (host little-endian) — direct
    /// queue.writeBuffer()/vkMapMemory upload source.
    #[inline(always)]
    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {
        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }
    }

    /// Alignment-free by-value read from a possibly-packed source
    /// (Law 3). Trusted-source path: no schema validation — use
    /// from_bytes for untrusted input.
    #[inline]
    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })
    }

    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).
    #[inline]
    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {
        if dst.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }
        Ok(())
    }

    /// Zero-overhead builder: `frame.with_schema_id(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_schema_id(mut self, schema_id: u64) -> Self {
        self.schema_id = schema_id;
        self
    }

    /// Zero-overhead builder: `frame.with_timestamp_ns(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_timestamp_ns(mut self, timestamp_ns: u64) -> Self {
        self.timestamp_ns = timestamp_ns;
        self
    }

    /// Zero-overhead builder: `frame.with_imu(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_imu(mut self, imu: AxisSample) -> Self {
        self.imu = imu;
        self
    }

    /// Zero-overhead builder: `frame.with_quality(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_quality(mut self, quality: u32) -> Self {
        self.quality = quality;
        self
    }

    /// Zero-overhead builder: `frame.with_crc32(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_crc32(mut self, crc32: u32) -> Self {
        self.crc32 = crc32;
        self
    }

}

