// sensor_event.h — generated by weftc-codegen 0.1.0 (target: c). DO NOT EDIT.
// module: sensors | struct: sensor_event | root: yes
// schema_id: 0x4173163A7BD694EC (auto: FNV-1a-64 of the canonical layout signature)
// layout: 32 bytes, align 8
//
// Laws (Pillar 1 briefing):
//   1. zero dynamic allocation on any read/write path below
//   2. pure C11 — the baseline build includes ONLY <stdint.h> <stdbool.h>
//      <stddef.h> <stdalign.h> <assert.h> (SIMD paths are behind
//      compiler capability macros and appear only when targeted)
//   3. unaligned-safe: cast helpers validate alignment; packed readers
//      are byte assembly — no UB on any architecture
//   4. host layout is guarded by static_assert below — a mismatched
//      compile is a build failure, never a silent misread

// ---- weft projection core (shared; self-guarded — safe in every header) ----
#ifndef WEFT_PROJECTION_CORE_H
#define WEFT_PROJECTION_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdalign.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Projection validation codes. Identical across every weftc-generated
/// header; legacy `rc == 0` checks remain correct (OK is 0).
typedef enum {
    WEFT_OK                  = 0,
    WEFT_ERR_SHORT_BUFFER    = 1,  // len < struct size (refused before any read)
    WEFT_ERR_BAD_ALIGN       = 2,  // buffer address violates struct alignment
    WEFT_ERR_SCHEMA_MISMATCH = 3,  // schema hash header does not match
} weft_error_t;

// The wire format is byte-exact little-endian. Refuse big-endian hosts at
// compile time rather than silently misreading every frame.
#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#error "weft projection: big-endian host not supported (wire format is byte-exact LE)"
#endif

/// Little-endian readers built from byte assembly — alignment-safe on every
/// architecture (Law 3) and dependency-free (Law 2). Optimizing compilers
/// fold these into a single load where the ISA allows it.
static inline uint16_t weft_read_u16_le(const uint8_t* p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}
static inline uint32_t weft_read_u32_le(const uint8_t* p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t weft_read_u64_le(const uint8_t* p)
{
    return (uint64_t)weft_read_u32_le(p) | ((uint64_t)weft_read_u32_le(p + 4) << 32);
}
static inline void weft_write_u16_le(uint8_t* p, uint16_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)(v >> 8);
}
static inline void weft_write_u32_le(uint8_t* p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu); p[3] = (uint8_t)(v >> 24);
}
static inline void weft_write_u64_le(uint8_t* p, uint64_t v)
{
    weft_write_u32_le(p, (uint32_t)(v & 0xFFFFFFFFu));
    weft_write_u32_le(p + 4, (uint32_t)(v >> 32));
}

typedef union { uint32_t u; float f; } weft_f32_bits;
typedef union { uint64_t u; double d; } weft_f64_bits;

static inline float weft_read_f32_le(const uint8_t* p)
{
    weft_f32_bits b; b.u = weft_read_u32_le(p); return b.f;
}
static inline double weft_read_f64_le(const uint8_t* p)
{
    weft_f64_bits b; b.u = weft_read_u64_le(p); return b.d;
}
static inline void weft_write_f32_le(uint8_t* p, float v)
{
    weft_f32_bits b; b.f = v; weft_write_u32_le(p, b.u);
}
static inline void weft_write_f64_le(uint8_t* p, double v)
{
    weft_f64_bits b; b.d = v; weft_write_u64_le(p, b.u);
}

/// IEEE 754 binary16 (half) codec — round-to-nearest-even both directions,
/// denormals and infinities exact. Zero dependencies: no <math.h>.
typedef uint16_t weft_f16_t;
static inline float weft_f16_to_f32(weft_f16_t h)
{
    const uint32_t sign = ((uint32_t)(h & 0x8000u)) << 16;
    const uint32_t exp  = ((uint32_t)(h >> 10)) & 0x1Fu;
    uint32_t man = h & 0x3FFu;
    uint32_t bits;
    if (exp == 0u) {
        if (man == 0u) {
            bits = sign;                                    /* +-0 */
        } else {
            uint32_t shift = 0u;                            /* subnormal -> normal */
            while ((man & 0x0400u) == 0u) { man <<= 1; shift++; }
            bits = sign | ((113u - shift) << 23) | ((man & 0x03FFu) << 13);
        }
    } else if (exp == 0x1Fu) {
        bits = sign | 0x7F800000u | (man ? (man << 13) : 0u);   /* inf / nan */
    } else {
        bits = sign | ((exp - 15u + 127u) << 23) | (man << 13);
    }
    weft_f32_bits b; b.u = bits; return b.f;
}
static inline weft_f16_t weft_f32_to_f16(float f)
{
    weft_f32_bits b; b.f = f;
    const uint32_t sign = (b.u >> 16) & 0x8000u;
    const uint32_t be = (b.u >> 23) & 0xFFu;
    const uint32_t man = b.u & 0x7FFFFFu;
    const int32_t exp = (int32_t)be - 127;
    if (be == 0xFFu) {
        return (weft_f16_t)(sign | 0x7C00u | (man ? 0x0200u : 0u));  /* inf/nan */
    }
    if (exp > 15) {
        return (weft_f16_t)(sign | 0x7C00u);                    /* overflow -> inf (RNE) */
    }
    if (exp >= -14) {
        uint32_t r = ((uint32_t)(exp + 15) << 10) | (man >> 13);
        const uint32_t rb = man & 0x1FFFu;
        if (rb > 0x1000u || (rb == 0x1000u && (r & 1u))) { r++; }
        return (weft_f16_t)(sign | r);
    }
    if (exp < -25) {
        return (weft_f16_t)sign;                               /* underflow -> 0 */
    }
    {
        const uint32_t m = man | 0x800000u;                    /* subnormal path */
        const uint32_t shift = (uint32_t)(-14 - exp);
        uint32_t r = m >> (13 + shift);
        const uint32_t rb = m & (((uint32_t)1 << (13 + shift)) - 1u);
        const uint32_t half = ((uint32_t)1 << (12 + shift));
        if (rb > half || (rb == half && (r & 1u))) {
            r++;
            if (r == 0x0400u) { return (weft_f16_t)(sign | 0x0400u); }
        }
        return (weft_f16_t)(sign | r);
    }
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_PROJECTION_CORE_H

#if defined(__AVX2__)
#include <immintrin.h>
#elif defined(__ARM_NEON)
#include <arm_neon.h>
#endif

#ifndef WEFT_SENSOR_EVENT_H
#define WEFT_SENSOR_EVENT_H

#include "axis_sample.h" // embedded axis_sample
#define WEFT_SENSOR_EVENT_SCHEMA_ID UINT64_C(0x4173163A7BD694EC)
#define WEFT_SENSOR_EVENT_SIZE 32u
#define WEFT_SENSOR_EVENT_ALIGN 8u
#define WEFT_SENSOR_EVENT_OFF_SCHEMA_ID 0u
#define WEFT_SENSOR_EVENT_OFF_TIMESTAMP_NS 8u
#define WEFT_SENSOR_EVENT_OFF_IMU 16u
#define WEFT_SENSOR_EVENT_OFF_QUALITY 24u
#define WEFT_SENSOR_EVENT_OFF_CRC32 28u

#ifdef __cplusplus
extern "C" {
#endif

/// weft_sensor_event_t — 32 bytes, align 8. Offsets are normative (weft-ir),
/// synthesized padding members make the C declaration match them exactly.
/// Batch-validated sensor event with an embedded axis_sample. The SIMD batch-validation fixture.
typedef struct weft_sensor_event {
    uint64_t schema_id;              // @0 (8)
    uint64_t timestamp_ns;              // @8 (8)
    weft_axis_sample_t imu;              // @16 (8)
    uint32_t quality;              // @24 (4)
    uint32_t crc32;              // @28 (4)
} weft_sensor_event_t;

// Law 4 (host side): compile-time ABI guards.
static_assert(sizeof(weft_sensor_event_t) == 32, "weft ABI layout violation: sensor_event size");
static_assert(offsetof(weft_sensor_event_t, schema_id) == 0, "weft ABI: sensor_event.schema_id offset mismatch");
static_assert(offsetof(weft_sensor_event_t, timestamp_ns) == 8, "weft ABI: sensor_event.timestamp_ns offset mismatch");
static_assert(offsetof(weft_sensor_event_t, imu) == 16, "weft ABI: sensor_event.imu offset mismatch");
static_assert(offsetof(weft_sensor_event_t, quality) == 24, "weft ABI: sensor_event.quality offset mismatch");
static_assert(offsetof(weft_sensor_event_t, crc32) == 28, "weft ABI: sensor_event.crc32 offset mismatch");

/// Zero-copy projection: validates byte length, buffer alignment and the
/// 64-bit schema hash header, then casts — no copy, no allocation. The hot
/// path is three compares and one load.
static inline const weft_sensor_event_t* weft_cast_sensor_event(const void* buffer, size_t len, weft_error_t* err)
{
    weft_error_t rc = WEFT_OK;
    const weft_sensor_event_t* out = NULL;
    const uint8_t* p = (const uint8_t*)buffer;
    if (len < (size_t)WEFT_SENSOR_EVENT_SIZE) {
        rc = WEFT_ERR_SHORT_BUFFER;
    } else if ((((uintptr_t)p) & (WEFT_SENSOR_EVENT_ALIGN - 1u)) != 0u) {
        rc = WEFT_ERR_BAD_ALIGN;
    } else if (*(const uint64_t*)(const void*)p != (uint64_t)WEFT_SENSOR_EVENT_SCHEMA_ID) {
        rc = WEFT_ERR_SCHEMA_MISMATCH;
    } else {
        out = (const weft_sensor_event_t*)p;
    }
    if (err) { *err = rc; }
    return out;
}

/// Mutable twin of weft_cast_sensor_event (writer side: UMEM/DMA ring slots).
static inline weft_sensor_event_t* weft_cast_sensor_event_mut(void* buffer, size_t len, weft_error_t* err)
{
    return (weft_sensor_event_t*)(void*)(uintptr_t)weft_cast_sensor_event((const void*)buffer, len, err);
}

/// Alignment-free by-value read from a possibly-packed source (Law 3).
/// Byte-assembly reads: safe on every architecture, no allocation.
static inline weft_error_t weft_sensor_event_read_packed(const void* buffer, size_t len, weft_sensor_event_t* out)
{
    if (len < (size_t)WEFT_SENSOR_EVENT_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    const uint8_t* p = (const uint8_t*)buffer;
    out->schema_id = weft_read_u64_le(p + 0u);
    out->timestamp_ns = weft_read_u64_le(p + 8u);
    {
        weft_error_t sub = weft_axis_sample_read_packed(p + 16u, (len > 16u) ? (len - 16u) : 0u, &out->imu);
        if (sub != WEFT_OK) { return sub; }
    }
    out->quality = weft_read_u32_le(p + 24u);
    out->crc32 = weft_read_u32_le(p + 28u);
    return WEFT_OK;
}

/// Alignment-free write to a possibly-packed destination (UMEM/DMA paths).
static inline weft_error_t weft_sensor_event_write_packed(void* buffer, size_t len, const weft_sensor_event_t* src)
{
    if (len < (size_t)WEFT_SENSOR_EVENT_SIZE) { return WEFT_ERR_SHORT_BUFFER; }
    uint8_t* p = (uint8_t*)buffer;
    weft_write_u64_le(p + 0u, (uint64_t)src->schema_id);
    weft_write_u64_le(p + 8u, (uint64_t)src->timestamp_ns);
    {
        weft_error_t sub = weft_axis_sample_write_packed(p + 16u, (len > 16u) ? (len - 16u) : 0u, &src->imu);
        if (sub != WEFT_OK) { return sub; }
    }
    weft_write_u32_le(p + 24u, (uint32_t)src->quality);
    weft_write_u32_le(p + 28u, (uint32_t)src->crc32);
    return WEFT_OK;
}

/// Batch schema-hash scan over an array of packed frames. AVX2 / NEON when
/// the compiler targets them, plain C11 scalar everywhere else (Law: the
/// portable build pulls no extra headers). Reads are alignment-safe on all
/// paths. On the first mismatching frame: returns WEFT_ERR_SCHEMA_MISMATCH,
/// *out_bad_index = its index, *out_count = frames validated before it.
static inline weft_error_t weft_validate_batch_sensor_event(const void* buffer, size_t len,
                                                 size_t* out_count, size_t* out_bad_index)
{
    const size_t stride = (size_t)WEFT_SENSOR_EVENT_SIZE;
    if (out_count) { *out_count = 0u; }
    if (out_bad_index) { *out_bad_index = 0u; }
    if ((len % stride) != 0u) { return WEFT_ERR_SHORT_BUFFER; }
    const size_t n = len / stride;
    const uint8_t* base = (const uint8_t*)buffer;
    size_t i = 0u;
#if defined(__AVX2__)
    if (n >= 4u) {
        const __m256i want = _mm256_set1_epi64x((long long)WEFT_SENSOR_EVENT_SCHEMA_ID);
        for (; (i + 4u) <= n; i += 4u) {
            const __m128i l0 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 0u) * stride));
            const __m128i l1 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 1u) * stride));
            const __m128i l2 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 2u) * stride));
            const __m128i l3 = _mm_loadl_epi64((const __m128i*)(const void*)(base + (i + 3u) * stride));
            const __m256i got = _mm256_set_epi64x(_mm_cvtsi128_si64(l3), _mm_cvtsi128_si64(l2),
                                                  _mm_cvtsi128_si64(l1), _mm_cvtsi128_si64(l0));
            const int mask = _mm256_movemask_epi8(_mm256_cmpeq_epi64(got, want));
            if (mask != -1) {
                for (int lane = 0; lane < 4; lane++) {
                    // movemask_epi8: 8 mask bits per 64-bit lane
                    if (((mask >> (lane * 8)) & 0xFF) != 0xFF) {
                        if (out_count) { *out_count = i + (size_t)lane; }
                        if (out_bad_index) { *out_bad_index = i + (size_t)lane; }
                        return WEFT_ERR_SCHEMA_MISMATCH;
                    }
                }
            }
        }
    }
#elif defined(__ARM_NEON) && defined(__aarch64__)
    if (n >= 2u) {
        const uint64x2_t want = vdupq_n_u64((uint64_t)WEFT_SENSOR_EVENT_SCHEMA_ID);
        for (; (i + 2u) <= n; i += 2u) {
            const uint64x2_t got = vcombine_u64(
                vld1_u64((const uint64_t*)(const void*)(base + (i + 0u) * stride)),
                vld1_u64((const uint64_t*)(const void*)(base + (i + 1u) * stride)));
            const uint64x2_t eq = vceqq_u64(got, want);
            if (vgetq_lane_u64(eq, 0) == 0u) {
                if (out_count) { *out_count = i; }
                if (out_bad_index) { *out_bad_index = i; }
                return WEFT_ERR_SCHEMA_MISMATCH;
            }
            if (vgetq_lane_u64(eq, 1) == 0u) {
                if (out_count) { *out_count = i + 1u; }
                if (out_bad_index) { *out_bad_index = i + 1u; }
                return WEFT_ERR_SCHEMA_MISMATCH;
            }
        }
    }
#endif
    for (; i < n; i++) {
        if (weft_read_u64_le(base + i * stride) != WEFT_SENSOR_EVENT_SCHEMA_ID) {
            if (out_count) { *out_count = i; }
            if (out_bad_index) { *out_bad_index = i; }
            return WEFT_ERR_SCHEMA_MISMATCH;
        }
    }
    if (out_count) { *out_count = n; }
    return WEFT_OK;
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_SENSOR_EVENT_H
