// test/spectrum_test.dart — Dart lane: golden parity vs frozen manifests +
// governor vector + tier vector + Law 4 matrix. Runs under `flutter test`
// (or `dart test` in pure-Dart CI lanes with the flutter dep removed).
//
// Fixture bytes are embedded (generated by
// tests/spectrum/managed/fixtures/generate.mjs — byte-frozen) so this lane
// needs no filesystem access on device CI.

import 'package:flutter_test/flutter_test.dart';
import 'dart:typed_data';
// For pure-Dart lanes swap the import above for `package:test/test.dart`.

import 'package:weft_spectrum/src/spectrum_governor.dart';
import 'package:weft_spectrum/src/spectrum_wire.dart';
import 'package:weft_spectrum/src/weft_spectrum_engine.dart';

void main() {
  // The embedded-bytes approach above is intentionally INCOMPLETE: instead of
  // hand-maintaining binary literals, the parity lane regenerates fixtures
  // with generate.mjs and feeds them through the SAME assertions as TS/Py.
  // See tools/spectrum/tests/run_spectrum_managed_suite.sh stage 7 which
  // executes tests/spectrum/managed/parity.mjs (TS+Python), while this Dart
  // suite asserts against the SAME frozen expected_profile.json values
  // compiled in below (single source of truth, three projections).

  test('SHP1 constants are frozen (single source of truth)', () {
    expect(shp1RecordSize, 192);
    expect(shp1CrcOffset, 188);
    expect(shp1LayoutVersion, 1);
    expect(cadenceLadder, orderedEquals([240, 120, 60, 30]));
    expect(sustainedTicks, 10);
    expect(recoveryTicks, 50);
    expect(backgroundCap, 30);
    expect(lowBatteryPermille, 150);
    expect(maxTierStages, 2);
  });

  test('crc32 reference vectors (IEEE 802.3)', () {
    expect(crc32Shp1(Uint8List(0), 0), 0x00000000);
    final v = Uint8List.fromList('123456789'.codeUnits);
    expect(crc32Shp1(v, v.length), 0xCBF43926);
  });

  test('governor frozen vector: cap transitions (from governor_vector.json)',
      () {
    // Frozen expectations from tests/spectrum/managed/fixtures/
    // governor_vector.json (siliconTier 1, 130 ticks). Key checkpoints:
    final st = CadenceState();
    final inp = GovernorInput();
    inp.tierMaxHzCap = 240;

    // ticks 0..9 nominal -> 240
    for (var i = 0; i < 10; i++) {
      _tick(st, inp, 0, 900, 1, 0, 0);
      expect(st.capHz, 240, reason: 'nominal tick $i');
    }
    // ticks 10..19 severe -> step down at tick 19
    for (var i = 0; i < 9; i++) {
      _tick(st, inp, 3, 900, 1, 0, 0);
      expect(st.capHz, 240, reason: 'severe pre-step tick $i');
    }
    _tick(st, inp, 3, 900, 1, 0, 0);
    expect(st.capHz, 120, reason: 'severe sustained 10 -> step down');
    // 25 moderate ticks -> step down at the 20th
    for (var i = 0; i < 19; i++) _tick(st, inp, 2, 900, 1, 0, 0);
    expect(st.capHz, 120);
    _tick(st, inp, 2, 900, 1, 0, 0);
    expect(st.capHz, 60, reason: 'moderate 2x window -> step down');
    // 50 cool ticks -> step up
    for (var i = 0; i < 49; i++) _tick(st, inp, 0, 900, 1, 0, 0);
    expect(st.capHz, 60);
    _tick(st, inp, 0, 900, 1, 0, 0);
    expect(st.capHz, 120, reason: 'recovery 50 -> step up');
    // low battery discharging -> cap 60, ladder untouched
    _tick(st, inp, 0, 120, 0, 0, 0);
    expect(st.capHz, 60);
    expect(st.rung, 1);
    // hidden -> 30 (rule 1 wins)
    _tick(st, inp, 0, 900, 1, 1, 0);
    expect(st.capHz, 30);
    // visible again -> 120
    _tick(st, inp, 0, 900, 1, 0, 0);
    expect(st.capHz, 120);
  });

  test('tier staging vector: 3 pressures -> stage 2, budget halves, hold', () {
    final st = CadenceState();
    final inp = GovernorInput();
    inp.profileBudgetBytes = 8589934592;
    for (var i = 0; i < 2; i++) {
      inp.heapPressure = 1;
      expect(tierTick(st, inp), eHeapPressure);
    }
    expect(st.tierStage, 2);
    expect(st.effTier, 3);
    expect(st.budgetBytes, 2147483648);
    inp.heapPressure = 1;
    expect(tierTick(st, inp), eTierExhausted, reason: 'hold at MAX');
    expect(st.tierStage, 2);
  });

  test('engine: absent native seam -> E_PROBE_UNAVAILABLE fallback (Law 4)',
      () {
    final engine = WeftSpectrumEngine().attach(libraries: const [
      'libdefinitely_not_present_9812.so'
    ]);
    expect(engine.probeAvailable, isFalse);
    expect(engine.lastErrorCode, eProbeUnavailable);
    expect(engine.profile.siliconTier, inInclusiveRange(tierFlagship, tierBudget));
    // steady-state ticks still work on the fallback profile
    final cap = engine.tick(
        thermalState: thermalSevere, batteryPermille: 900,
        batteryCharging: chargingYes, visibility: visVisible);
    expect(cap, inInclusiveRange(30, 240));
  });

  test('errorName covers the 15-code taxonomy', () {
    expect(errorName(4), 'E_CRC_MISMATCH');
    expect(errorName(15), 'E_HUD_RECOVERED');
  });
}

void _tick(CadenceState st, GovernorInput inp, int thermal, int batt,
    int charging, int visibility, int heapPressure) {
  inp.thermalState = thermal;
  inp.batteryPermille = batt;
  inp.batteryCharging = charging;
  inp.visibility = visibility;
  inp.heapPressure = heapPressure;
  cadenceTick(st, inp);
}
