# conftest.py — path bootstrap + shared fixtures for weft_fintech tests.

import sys
from pathlib import Path

PKG_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PKG_ROOT.parent.parent  # python/weft_fintech -> Weft/
FIXTURES = REPO_ROOT / 'tests' / 'adapters' / 'managed' / 'fixtures'

sys.path.insert(0, str(PKG_ROOT / 'src'))
sys.path.insert(0, str(FIXTURES))

import pytest  # noqa: E402


@pytest.fixture(scope='session')
def golden_stream() -> bytes:
    return (FIXTURES / 'fintech-stream.bin').read_bytes()


@pytest.fixture(scope='session')
def manifest() -> dict:
    import json
    return json.loads((FIXTURES / 'expected-hashes' / 'expected_hashes.json').read_text())


@pytest.fixture(scope='session')
def scenario() -> dict:
    import json
    return json.loads((FIXTURES / 'scenario.json').read_text())


@pytest.fixture(scope='session')
def one_million_stream() -> bytes:
    """1,000,000-message deterministic stream (generated by Node, cached)."""
    import subprocess
    import os
    cache = Path(os.environ.get('TMPDIR', '/tmp')) / 'weft-adapters-1m.bin'
    if not cache.exists() or cache.stat().st_size < 1_000_000:
        node = subprocess.run(
            ['node', str(FIXTURES / 'dump_stream.mjs'),
             '--count', '1000000', '--out', str(cache)],
            check=True, capture_output=True, text=True,
        )
        assert '"count":1000000' in node.stdout
    return cache.read_bytes()
