// E2E integration: read a buffer PRODUCED BY THE C HARNESS (frozen kernel
// encoder) with the generated TS views. This is the Pillar 1 §5.3 leg —
// "integration tests reading buffers generated by the C harness".
//
// The C binary is built by tools/weftc/tests/run_integration.sh. When the
// binary is absent (bare `node --test`), the leg skips gracefully.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

import { TelemetryFrameView } from '../golden/telemetry-frame-view.js';
import { WeftEnvelopeView } from '../golden/weft-envelope-view.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..', '..', '..');
const EMIT_BIN = process.env.WEFTC_EMIT_BIN ?? '/tmp/weftc_emit';
const builtHere = !existsSync(EMIT_BIN) && existsSync(join(REPO, 'core', 'c', 'weft.c'));

const SKIP = !existsSync(EMIT_BIN) && !builtHere;

function produceKernelBuffer() {
  let bin = EMIT_BIN;
  if (!existsSync(bin)) {
    bin = join(mkdtempSync(join(tmpdir(), 'weftc-')), 'weftc_emit');
    execFileSync('cc', [
      '-std=c11', '-I', join(REPO, 'core', 'c'),
      '-o', bin,
      join(REPO, 'tools', 'weftc', 'tests', 'harness', 'emit_frame_stack.c'),
      join(REPO, 'core', 'c', 'weft.c'),
    ]);
  }
  const out = join(mkdtempSync(join(tmpdir(), 'weftc-')), 'kernel_stack.bin');
  execFileSync(bin, [out]);
  return readFileSync(out);
}

test('kernel-produced buffer reads back through the TS views', { skip: SKIP && 'C harness binary not built (run tools/weftc/tests/run_integration.sh)' }, () => {
  const stack = produceKernelBuffer();
  assert.equal(stack.length, 88);

  const env = new WeftEnvelopeView().bind(stack, 0);
  assert.equal(env.validateHeader(stack.length), true, 'kernel envelope must validate');
  assert.equal(env.version, 1);
  assert.equal(env.headerSize, 16);
  assert.equal(env.seq, 0xBEEF);
  assert.equal(env.payloadLen, 64);

  const frame = new TelemetryFrameView().bind(stack, env.headerSize);
  assert.equal(frame.validateHeader(), true, 'kernel payload must pass schema handshake');
  assert.equal(frame.schemaId, 0x8f4c1120a9b30012n);
  assert.equal(frame.timestampNs, 1737504000123456789n);
  assert.equal(frame.getVelocityAt(0), 1.5);
  assert.equal(frame.getVelocityAt(1), -2.25);
  assert.equal(frame.getVelocityAt(2), 4000.125);
  assert.equal(frame.pressurePa, 1013.25);
  assert.equal(frame.state, 7);
  assert.equal(frame.getGpsCoordinatesAt(0), 37.5);
  assert.equal(frame.getGpsCoordinatesAt(1), -122.25);
  assert.equal(frame.getPayloadHashAt(0), 0xDE);
  assert.equal(frame.getPayloadHashAt(7), 0xBE);

  // kernel canary rule: u64 LE == seq at buf_end-8
  const canary = new DataView(stack.buffer, stack.byteOffset + 80, 8).getBigUint64(0, true);
  assert.equal(canary, 0xBEEFn);
});

test('golden stack is byte-identical to what the kernel emitter produces', { skip: SKIP && 'C harness binary not built' }, () => {
  const stack = produceKernelBuffer();
  const golden = readFileSync(join(HERE, '..', '..', '..', 'tests', 'golden', 'weft_frame_stack.bin'));
  assert.deepEqual([...stack], [...golden], 'C harness and Python golden generator must agree byte-for-byte');
});
