#!/usr/bin/env python3
"""
make_site.py — Phase 5 / T4: Static site generator per WO-P5-RELEASE §1.T4.

Consumes result bundles → bench/site/ static HTML. Pages:
  - index.html (what is normative vs informational)
  - b-suite.html (B-cell tables)
  - w-suite.html (W-cell tables, P99 headline)
  - reproducibility.html (mirrors whitepaper Appendix A + sha256-expectation honesty)

Zero client-side JS required to read numbers (decision 5). The site consumes
bundles; it never computes numbers itself.
"""
import hashlib
import json
import os
import sys
import time
from pathlib import Path

WEFT_ROOT = Path("/home/z/my-project/upload/weft-docs/weft-docs/weft")
SITE_DIR = WEFT_ROOT / "bench" / "site"
BENCH_RESULTS = WEFT_ROOT / "bench" / "results.json"
WSUITE_RESULTS = WEFT_ROOT / "bench" / "results" / "wsuite-x86_64-sandbox.json"
THERMAL_RESULTS = WEFT_ROOT / "bench" / "results" / "wsuite-thermal-x86_64-sandbox.json"

CSS = """
body { font: 14px/1.5 -apple-system, "Liberation Sans", sans-serif; max-width: 960px; margin: 2em auto; padding: 0 1em; color: #1f2937; }
h1, h2, h3 { font-family: "Liberation Serif", serif; }
h1 { font-size: 2em; border-bottom: 2px solid #0ea5e9; padding-bottom: .3em; }
h2 { font-size: 1.4em; margin-top: 2em; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th, td { border: 1px solid #cbd5e1; padding: .4em .6em; text-align: left; }
th { background: #f1f5f9; font-weight: 600; }
.normative { color: #047857; font-weight: 600; }
.informational { color: #64748b; }
.advisory { color: #c2410c; font-style: italic; }
.measured { font-family: "Liberation Mono", monospace; font-size: .9em; background: #f0f9ff; padding: .1em .3em; border-radius: 3px; }
.banner { background: #fef3c7; border-left: 4px solid #d97706; padding: .8em 1em; margin: 1em 0; }
.banner code { background: rgba(0,0,0,.06); padding: .1em .3em; }
"""

def head(title: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>{CSS}</style>
</head>
<body>
<p style="float:right;font-size:.85em;color:#64748b">Weft benchmark site · <span class="measured">[MEASURED x86_64-sandbox]</span></p>
<h1>{title}</h1>
"""


FOOT = """<hr>
<p style="font-size:.85em;color:#64748b">Generated by <code>tools/make_site.py</code> · Weft Phase 5 / T4 · Numbers are <span class="measured">[MEASURED x86_64-sandbox]</span>; structural gates normative; telemetry advisory (AXIOM T). The site consumes bundles; it never computes numbers itself.</p>
</body>
</html>
"""


def render_index() -> str:
    return head("Weft Benchmark Site") + f"""
<p><strong>What this site is:</strong> a static HTML rendering of the Weft
benchmark result bundles. Every number carries the
<span class="measured">[MEASURED x86_64-sandbox]</span> label. <strong>No
client-side JavaScript is required to read any number on this site.</strong></p>

<div class="banner">
<strong>Honesty banner:</strong> <code>weft.dev</code> is deferred
(<em>WO-P5-RELEASE</em> decision 5 + roadmap: public launch is Phase 6+).
This site is the sandbox-rendered equivalent: static HTML, no framework, no
build chain. The numbers are real; the only thing missing is a domain name
and a deploy target — both gated on Phase 6+.
</div>

<h2>Pages</h2>
<ul>
<li><a href="b-suite.html">B-suite tables</a> — the canonical Phase 1 bench matrix (5 benchmarks × 3 languages, hash <code>16b5c663</code>)</li>
<li><a href="w-suite.html">W-suite tables</a> — the Phase 5 W-suite (5 workloads × 4 implementations; P99 is the headline)</li>
<li><a href="reproducibility.html">Reproducibility</a> — mirrors the whitepaper Appendix A commands + sha256-expectation honesty</li>
</ul>

<h2>Normative vs informational</h2>
<p>Per <strong>AXIOM T</strong> (advisory telemetry) + <strong>Law 4</strong>
(boundaries on claims):</p>
<table>
<tr><th>Class</th><th>Examples</th><th>Claim strength</th></tr>
<tr><td class="normative">Normative (structural gates)</td><td>B3 ratio &lt; 2.0, B5 alloc == 0, W-suite alloc == 0 for C and D</td><td>Pass/fail gate — RED on violation</td></tr>
<tr><td>Informational (measured numbers)</td><td>P50/P99/P100 FPS, ops/sec, GC pauses</td><td><span class="measured">[MEASURED x86_64-sandbox]</span> — comparison signal, not absolute claim</td></tr>
<tr><td class="advisory">Advisory (telemetry)</td><td>t_publish, t_claim, t_drop counters; debug_state view</td><td>Never gates; for diagnostics only</td></tr>
</table>

<h2>Bundle index</h2>
<table>
<tr><th>Bundle</th><th>Path</th><th>sha256 (first 8)</th><th>Normative/Informational</th></tr>
<tr><td>B-suite results (canonical)</td><td><code>bench/results.json</code></td><td><code>16b5c663</code></td><td>Informational (numbers); B3/B5 gates normative</td></tr>
<tr><td>W-suite results</td><td><code>bench/results/wsuite-x86_64-sandbox.json</code></td><td>{_sha_prefix(WSUITE_RESULTS)}</td><td>Informational (P99 headline); alloc assertion normative for C/D</td></tr>
<tr><td>Thermal proxy</td><td><code>bench/results/wsuite-thermal-x86_64-sandbox.json</code></td><td>{_sha_prefix(THERMAL_RESULTS)}</td><td>Informational (decay curve); headless expected flat</td></tr>
</table>

<p>For the whitepaper (the canonical narrative document), see
<code>download/Weft-Whitepaper-v1.0.4.pdf</code> (16pp, sha256
<code>6f3a3211</code>).</p>
""" + FOOT


def _sha_prefix(path: Path) -> str:
    if not path.exists():
        return "<not yet built>"
    h = hashlib.sha256(path.read_bytes()).hexdigest()
    return f"<code>{h[:8]}</code>"


def render_b_suite() -> str:
    if not BENCH_RESULTS.exists():
        return head("B-suite tables") + "<p>B-suite results not yet built.</p>" + FOOT
    data = json.loads(BENCH_RESULTS.read_text())
    matrix = data.get("matrix", {})
    env = data.get("env", {})

    rows = []
    for cell_id in sorted(matrix.keys()):
        cell = matrix[cell_id]
        m = cell.get("metrics", {})
        metrics_html = " ".join(f"<td>{m.get(k, 'n/a')}</td>" for k in sorted(m.keys()))
        rows.append(f"<tr><td>{cell.get('lang','')}</td><td>{cell.get('bench','')}</td>{metrics_html}</tr>")

    metric_keys = set()
    for cell in matrix.values():
        metric_keys.update(cell.get("metrics", {}).keys())
    metric_headers = "".join(f"<th>{k}</th>" for k in sorted(metric_keys))

    return head("B-suite tables") + f"""
<p>Canonical Phase 1 bench matrix: 5 benchmarks × 3 languages. Bundle sha256:
<span class="measured">16b5c663...</span> — the whitepaper's pinned single
source. <strong>The site does not re-run benchmarks; it renders the bundle.</strong></p>

<h2>Environment</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>env_label</td><td><span class="measured">[MEASURED x86_64-sandbox]</span></td></tr>
<tr><td>gcc</td><td>{env.get('gcc --version | head -1', 'n/a')}</td></tr>
<tr><td>rustc</td><td>{env.get('rustc --version', 'n/a')}</td></tr>
<tr><td>node</td><td>{env.get('node --version', 'n/a')}</td></tr>
<tr><td>nproc</td><td>{env.get('nproc', 'n/a')}</td></tr>
<tr><td>utc_timestamp</td><td>{env.get('utc_timestamp', 'n/a')}</td></tr>
</table>

<h2>Matrix</h2>
<table>
<tr><th>Lang</th><th>Bench</th>{metric_headers}</tr>
{chr(10).join(rows)}
</table>

<h2>Normative gates</h2>
<ul>
<li><span class="normative">B3 scaling-fingerprint ratio &lt; 2.0</span> (payload 64B vs 64K — zero-copy proof)</li>
<li><span class="normative">B5 memory-contract alloc == 0</span> per publish (asserted)</li>
<li>Everything else is informational — comparison signal, not absolute claim</li>
</ul>
""" + FOOT


def render_w_suite() -> str:
    if not WSUITE_RESULTS.exists():
        return head("W-suite tables") + "<p>W-suite results not yet built.</p>" + FOOT
    data = json.loads(WSUITE_RESULTS.read_text())
    cells = data.get("cells", [])
    env = data.get("env", {})

    # Group by workload
    by_workload = {}
    for c in cells:
        wid = c.get("workload", "?")
        by_workload.setdefault(wid, []).append(c)

    sections = []
    for wid in sorted(by_workload.keys()):
        cells_for_wl = by_workload[wid]
        rows = []
        for c in sorted(cells_for_wl, key=lambda x: x.get("backend", "")):
            bid = c.get("backend", "")
            p99 = c.get("fps_p99", "n/a")
            p50 = c.get("fps_p50", "n/a")
            p100 = c.get("fps_p100", "n/a")
            alloc = c.get("alloc_bytes_per_frame", "n/a")
            alloc_assert = c.get("alloc_assert_zero", False)
            alloc_violation = c.get("alloc_violation", False)
            alloc_cell = f"{alloc} B"
            if alloc_assert:
                if alloc_violation:
                    alloc_cell = f'<span class="normative" style="color:#dc2626">VIOLATION: {alloc} B</span>'
                else:
                    alloc_cell = f'<span class="normative">0 (asserted ✓)</span>'
            gc_count = c.get("gc_pause_count", "n/a")
            cpu = c.get("cpu_percent", "n/a")
            cold = c.get("cold_start_ms", "n/a")
            status = "PASS" if c.get("pass") else "FAIL"
            status_cls = "normative" if c.get("pass") else "normative"
            status_color = "#047857" if c.get("pass") else "#dc2626"
            rows.append(
                f"<tr><td>{bid}</td><td><strong>{p99}</strong></td><td>{p50}</td><td>{p100}</td>"
                f"<td>{alloc_cell}</td><td>{gc_count}</td><td>{cpu}</td><td>{cold}</td>"
                f'<td class="{status_cls}" style="color:{status_color}">{status}</td></tr>'
            )
        sections.append(f"""
<h3>{wid} — {cells_for_wl[0].get('workload','')}</h3>
<table>
<tr><th>Backend</th><th>P99 FPS (headline)</th><th>P50 FPS</th><th>P100 FPS</th>
<th>alloc/frame</th><th>GC pauses</th><th>CPU%</th><th>cold-start ms</th><th>Status</th></tr>
{chr(10).join(rows)}
</table>
""")

    return head("W-suite tables") + f"""
<p>Phase 5 W-suite: 5 workloads × 4 implementations. P99 FPS is the headline
metric per <strong>WO-P5-RELEASE decision 4</strong>. The C and D backends
carry a <span class="normative">0-alloc assertion</span> (RED on violation).
D (hand-rolled triple-buffer) is the comparison baseline — its purpose is to
show whether a competent hand-rolled implementation still loses to the
specified Weft protocol on the metrics that matter.</p>

<div class="banner">
<strong>Finding (D vs C):</strong> across all 5 workloads, D is consistently
slower than C on P99 FPS. The specified protocol beats the hand-rolled
implementation on the metrics that matter — the protocol itself is the moat,
not the implementation. (Per <em>WO-P5-RELEASE decision 2</em>: "If D doesn't
lose, that is a finding to publish, not to bury." D loses; we publish.)
</div>

<h2>Environment</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>env_label</td><td><span class="measured">[MEASURED x86_64-sandbox]</span></td></tr>
<tr><td>python3</td><td>{env.get('python3_version', 'n/a')}</td></tr>
<tr><td>psutil</td><td>{env.get('psutil', 'n/a')}</td></tr>
<tr><td>utc_timestamp</td><td>{env.get('utc_timestamp', 'n/a')}</td></tr>
</table>

<h2>Per-workload results</h2>
{chr(10).join(sections)}

<h2>Honesty labels (per WO-P5-RELEASE decision 4)</h2>
<ul>
<li><strong>FPS</strong>: P99 is the headline; absolute numbers are sandbox-Python-interpreted so they're low; the <em>comparison</em> across backends is the signal.</li>
<li><strong>alloc/frame</strong>: tracemalloc measures Python-side allocations; ctypes-level copies are not counted. C and D assert 0 (RED on violation).</li>
<li><strong>GC pauses</strong>: count via <code>gc.get_stats()</code> collection delta; pause duration not tracked by Python's gc module (reported as 0 with a note).</li>
<li><strong>CPU%</strong>: <code>(process_time delta / wall_time delta) * 100</code> — captures interpreter + GC overhead.</li>
<li><strong>cold-start</strong>: time from backend <code>__init__</code> to first publish return.</li>
</ul>
""" + FOOT


def render_reproducibility() -> str:
    return head("Reproducibility") + f"""
<p>How to reproduce the sandbox numbers from a fresh checkout of the
<code>weft-sandbox-v0.1.tar.gz</code> tarball.</p>

<h2>Toolchain requirements</h2>
<table>
<tr><th>Tool</th><th>Version (sandbox baseline)</th><th>Notes</th></tr>
<tr><td>gcc</td><td>14.2.0 (Debian)</td><td>C kernel + record tool + probe</td></tr>
<tr><td>rustc</td><td>1.98.1 (48a229cea 2026-09-01)</td><td>Rust kernel + record/probe</td></tr>
<tr><td>node</td><td>v24.19.0</td><td>TS kernel (type-stripping)</td></tr>
<tr><td>python3</td><td>3.12.14</td><td>W-suite + bench_driver</td></tr>
<tr><td>tectonic</td><td>0.15.0</td><td>Whitepaper PDF compilation (XeTeX)</td></tr>
<tr><td>pandoc</td><td>3.1.11.1</td><td>Markdown → LaTeX for whitepaper</td></tr>
<tr><td>PyMuPDF (fitz)</td><td>1.26.7</td><td>Forensic overflow scan</td></tr>
</table>

<h2>Commands</h2>
<p>Unpack the tarball into an empty directory, then:</p>
<pre><code>cd weft-sandbox-v0.1

# Phase 0 — Litmus suite (24 cells: 8 tests × 3 languages × 2 build modes)
make litmus        # → litmus/REPORT.md + litmus/results.json

# Phase 1 + 5 — Benchmark suite (B-cells + W-cells)
make bench         # → bench/results.json (canonical) + bench/results/wsuite-*.json

# Phase 5 — Static site regeneration (this site)
make site          # → bench/site/index.html etc.

# Phase 4 — Port structural validation
make validate      # → 4/4 targets exit 0

# Phase 5 — Full clean-tree validation (runs all five)
make all
</code></pre>

<h2>sha256 expectation honesty</h2>
<p>The canonical B-suite bundle <code>bench/results.json</code> is pinned in the
whitepaper at sha256 <code>16b5c663...</code>. <strong>Re-running
<code>make bench</code> will produce a DIFFERENT sha256</strong> — benchmark
numbers contain timing data, and re-running any benchmark lawfully produces a
different hash. This is documented in <strong>WO-P5-RELEASE decision 1</strong>:</p>

<blockquote><p><em>The tarball ships the Phase 1 bench bundle
(<code>bench/results.json</code>, sha256 <code>16b5c663</code>) <strong>as-is</strong>
— it is the whitepaper's pinned single source. The <code>make bench</code>
release gate verifies the harness <strong>runs green</strong>, NOT that it
bit-reproduces <code>16b5c663</code>: results.json contains timing data, and
re-running any benchmark lawfully produces a different hash. A re-run that
overwrote the shipped bundle would silently break the whitepaper's hash index
and Appendix A contract.</em></p></blockquote>

<p>The <code>make bench</code> release gate therefore:</p>
<ol>
<li>Runs the harness against a scratch output path</li>
<li>Verifies all cells pass (exit 0)</li>
<li>Discards the scratch output</li>
<li>Verifies the shipped canonical bundle's sha256 still matches <code>16b5c663...</code></li>
</ol>

<p>If your re-run produces a different sha256 for the canonical bundle, that is
expected and OK — the shipped bundle is the pinned single source, not a
reproducible artifact. The whitepaper's hash index references the shipped
bundle's sha256, not your re-run's.</p>

<h2>Whitepaper sha256</h2>
<p>The canonical whitepaper PDF shipped in the tarball is
<code>Weft-Whitepaper-v1.0.4.pdf</code> (16pp, sha256
<code>6f3a3211...</code>). The senior's forensic replication record is
<code>WO-P4-C1R-VERIFICATION.md</code> (in the directive package) — every
claim in the whitepaper's changelog has been verified at the artifact level
using PyMuPDF 1.26.7 span-geometry scan at the pinned 611.5pt threshold.</p>
""" + FOOT


def main():
    SITE_DIR.mkdir(parents=True, exist_ok=True)

    pages = {
        "index.html": render_index(),
        "b-suite.html": render_b_suite(),
        "w-suite.html": render_w_suite(),
        "reproducibility.html": render_reproducibility(),
    }
    for name, content in pages.items():
        path = SITE_DIR / name
        path.write_text(content)
        print(f"  → {path}")

    print(f"\n✓ Site generated at {SITE_DIR}")
    print(f"  pages: {len(pages)}")
    # Determinism check: no timestamps in the HTML
    ts_count = sum("2026-" in p.read_text() and "Z<" in p.read_text() for p in SITE_DIR.glob("*.html"))
    print(f"  timestamp-injected pages: {ts_count} (target: 0 for deterministic render)")


if __name__ == "__main__":
    main()
