// mcu_status.wgsl — generated by weftc-codegen 0.1.0 (target: wgsl). DO NOT EDIT.
// module: mcu | struct: mcu_status | schema_id: 0xCDB73E6BFDEC4F07
// host layout: 32 bytes, align 8
//
// WEFT-GPU-NOT-EXACT: mcu_status — storage variant WITHHELD (Law 4)
// reason: field vbus_mv (scalar): WGSL and GLSL expose no 16-bit integer buffer types; widen to u32 (or keep this struct CPU-side)
// remediation: widen 8/16-bit integers to u32, replace bool with u32
//   flags + bitfields, restructure f16-only layouts, or keep this struct
//   host-side and project a GPU-exact mirror schema.
// The refusal is total: no struct is emitted, because a struct with a
// silently-wrong layout is worse than no struct.
