//! mcu_status — generated by weftc-codegen 0.1.0 (target: rust). DO NOT EDIT.
//! module: mcu | struct: mcu_status | root: yes
//! schema_id: 0xCDB73E6BFDEC4F07 (auto: FNV-1a-64 of the canonical layout signature)
//! layout: 32 bytes, align 8 — byte-identical with `weft_mcu_status_t` (C) and the
//! byte-exact GPU structs (WGSL storage / GLSL std430).
//!
//! Laws: zero allocation on every path; no_std (`core` only); unaligned
//! access only through read_unaligned/write_unaligned; layout is a
//! compile-time contract via #[repr(C)].
#![allow(dead_code)]

use super::weft_projection_core::WeftError;
use super::weft_projection_core::WeftF16;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct McuStatus {
    pub schema_id: u64,
    pub flags: u32,
    /// bus voltage, millivolts
    pub vbus_mv: u16,
    /// board temperature
    pub temp_c: WeftF16,
    pub gyro_temp_c: WeftF16,
    /// synthesized pad (weft-ir gap 18..20)
    pub weft_pad0: [u16; 1],
    /// per-motor RPM
    pub motor_rpm: [u16; 4],
    pub crc32: u32,
}

impl McuStatus {
    /// 64-bit schema hash header this type projects.
    pub const SCHEMA_ID: u64 = 0xCDB7_3E6B_FDEC_4F07;
    /// Exact struct size in bytes (weft-ir normative).
    pub const SIZE: usize = 32;
    /// Exact struct alignment in bytes (weft-ir normative).
    pub const ALIGN: usize = 8;

    /// Zero-copy projection: validates length, alignment and the schema
    /// hash header, then borrows the buffer as `&Self`. No copy, no
    /// allocation (Law 1); the check is three compares + one load.
    #[inline(always)]
    pub fn from_bytes(bytes: &[u8]) -> Result<&Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &*(bytes.as_ptr() as *const Self) })
    }

    /// Mutable twin (writer side: ring slots, UMEM pages).
    #[inline(always)]
    pub fn from_bytes_mut(bytes: &mut [u8]) -> Result<&mut Self, WeftError> {
        Self::validate_header(bytes)?;
        Ok(unsafe { &mut *(bytes.as_mut_ptr() as *mut Self) })
    }

    #[inline(always)]
    fn validate_header(bytes: &[u8]) -> Result<(), WeftError> {
        let p = bytes.as_ptr();
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        if (p as usize) & (Self::ALIGN - 1) != 0 {
            return Err(WeftError::BadAlign);
        }
        let id = unsafe { core::ptr::read_unaligned(p as *const u64) };
        if id != Self::SCHEMA_ID {
            return Err(WeftError::SchemaMismatch);
        }
        Ok(())
    }

    /// Byte view of this value (host little-endian) — direct
    /// queue.writeBuffer()/vkMapMemory upload source.
    #[inline(always)]
    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {
        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }
    }

    /// Alignment-free by-value read from a possibly-packed source
    /// (Law 3). Trusted-source path: no schema validation — use
    /// from_bytes for untrusted input.
    #[inline]
    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {
        if bytes.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })
    }

    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).
    #[inline]
    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {
        if dst.len() < Self::SIZE {
            return Err(WeftError::ShortBuffer);
        }
        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }
        Ok(())
    }

    /// Zero-overhead builder: `frame.with_schema_id(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_schema_id(mut self, schema_id: u64) -> Self {
        self.schema_id = schema_id;
        self
    }

    /// Zero-overhead builder: `frame.with_flags(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_flags(mut self, flags: u32) -> Self {
        self.flags = flags;
        self
    }

    /// Zero-overhead builder: `frame.with_vbus_mv(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_vbus_mv(mut self, vbus_mv: u16) -> Self {
        self.vbus_mv = vbus_mv;
        self
    }

    /// Zero-overhead builder: `frame.with_temp_c(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_temp_c(mut self, temp_c: WeftF16) -> Self {
        self.temp_c = temp_c;
        self
    }

    /// Zero-overhead builder: `frame.with_gyro_temp_c(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_gyro_temp_c(mut self, gyro_temp_c: WeftF16) -> Self {
        self.gyro_temp_c = gyro_temp_c;
        self
    }

    /// Zero-overhead builder: `frame.with_motor_rpm(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_motor_rpm(mut self, motor_rpm: [u16; 4]) -> Self {
        self.motor_rpm = motor_rpm;
        self
    }

    /// Zero-overhead builder: `frame.with_crc32(v)` consumes and returns self.
    #[inline(always)]
    pub const fn with_crc32(mut self, crc32: u32) -> Self {
        self.crc32 = crc32;
        self
    }

    /// mcu_status.mode: bits [0..1] of flags
    #[inline(always)]
    pub const fn mode(&self) -> u32 {
        (self.flags >> 0) & 0x3
    }
    #[inline(always)]
    pub fn set_mode(&mut self, v: u32) {
        self.flags = (self.flags & !(0x3)) | ((v & 0x3) << 0);
    }
    #[inline(always)]
    pub const fn with_mode(mut self, v: u32) -> Self {
        self.flags = (self.flags & !(0x3)) | ((v & 0x3) << 0);
        self
    }

    /// mcu_status.armed: bits [4..4] of flags
    #[inline(always)]
    pub const fn armed(&self) -> u32 {
        (self.flags >> 4) & 0x1
    }
    #[inline(always)]
    pub fn set_armed(&mut self, v: u32) {
        self.flags = (self.flags & !(0x1)) | ((v & 0x1) << 4);
    }
    #[inline(always)]
    pub const fn with_armed(mut self, v: u32) -> Self {
        self.flags = (self.flags & !(0x1)) | ((v & 0x1) << 4);
        self
    }

    /// mcu_status.error_code: bits [8..15] of flags
    #[inline(always)]
    pub const fn error_code(&self) -> u32 {
        (self.flags >> 8) & 0xFF
    }
    #[inline(always)]
    pub fn set_error_code(&mut self, v: u32) {
        self.flags = (self.flags & !(0xFF)) | ((v & 0xFF) << 8);
    }
    #[inline(always)]
    pub const fn with_error_code(mut self, v: u32) -> Self {
        self.flags = (self.flags & !(0xFF)) | ((v & 0xFF) << 8);
        self
    }

}

