// weft_projection_core.h — generated by weftc-codegen 0.1.0. DO NOT EDIT.
// Shared projection core for all weftc-generated C headers.
// Every generated header embeds this block itself (self-guarded),
// so including this file directly is optional — it exists for
// tooling and for humans who want the core alone.

// ---- weft projection core (shared; self-guarded — safe in every header) ----
#ifndef WEFT_PROJECTION_CORE_H
#define WEFT_PROJECTION_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdalign.h>
#include <assert.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Projection validation codes. Identical across every weftc-generated
/// header; legacy `rc == 0` checks remain correct (OK is 0).
typedef enum {
    WEFT_OK                  = 0,
    WEFT_ERR_SHORT_BUFFER    = 1,  // len < struct size (refused before any read)
    WEFT_ERR_BAD_ALIGN       = 2,  // buffer address violates struct alignment
    WEFT_ERR_SCHEMA_MISMATCH = 3,  // schema hash header does not match
} weft_error_t;

// The wire format is byte-exact little-endian. Refuse big-endian hosts at
// compile time rather than silently misreading every frame.
#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
#error "weft projection: big-endian host not supported (wire format is byte-exact LE)"
#endif

/// Little-endian readers built from byte assembly — alignment-safe on every
/// architecture (Law 3) and dependency-free (Law 2). Optimizing compilers
/// fold these into a single load where the ISA allows it.
static inline uint16_t weft_read_u16_le(const uint8_t* p)
{
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}
static inline uint32_t weft_read_u32_le(const uint8_t* p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t weft_read_u64_le(const uint8_t* p)
{
    return (uint64_t)weft_read_u32_le(p) | ((uint64_t)weft_read_u32_le(p + 4) << 32);
}
static inline void weft_write_u16_le(uint8_t* p, uint16_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)(v >> 8);
}
static inline void weft_write_u32_le(uint8_t* p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xFFu); p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu); p[3] = (uint8_t)(v >> 24);
}
static inline void weft_write_u64_le(uint8_t* p, uint64_t v)
{
    weft_write_u32_le(p, (uint32_t)(v & 0xFFFFFFFFu));
    weft_write_u32_le(p + 4, (uint32_t)(v >> 32));
}

typedef union { uint32_t u; float f; } weft_f32_bits;
typedef union { uint64_t u; double d; } weft_f64_bits;

static inline float weft_read_f32_le(const uint8_t* p)
{
    weft_f32_bits b; b.u = weft_read_u32_le(p); return b.f;
}
static inline double weft_read_f64_le(const uint8_t* p)
{
    weft_f64_bits b; b.u = weft_read_u64_le(p); return b.d;
}
static inline void weft_write_f32_le(uint8_t* p, float v)
{
    weft_f32_bits b; b.f = v; weft_write_u32_le(p, b.u);
}
static inline void weft_write_f64_le(uint8_t* p, double v)
{
    weft_f64_bits b; b.d = v; weft_write_u64_le(p, b.u);
}

/// IEEE 754 binary16 (half) codec — round-to-nearest-even both directions,
/// denormals and infinities exact. Zero dependencies: no <math.h>.
typedef uint16_t weft_f16_t;
static inline float weft_f16_to_f32(weft_f16_t h)
{
    const uint32_t sign = ((uint32_t)(h & 0x8000u)) << 16;
    const uint32_t exp  = ((uint32_t)(h >> 10)) & 0x1Fu;
    uint32_t man = h & 0x3FFu;
    uint32_t bits;
    if (exp == 0u) {
        if (man == 0u) {
            bits = sign;                                    /* +-0 */
        } else {
            uint32_t shift = 0u;                            /* subnormal -> normal */
            while ((man & 0x0400u) == 0u) { man <<= 1; shift++; }
            bits = sign | ((113u - shift) << 23) | ((man & 0x03FFu) << 13);
        }
    } else if (exp == 0x1Fu) {
        bits = sign | 0x7F800000u | (man ? (man << 13) : 0u);   /* inf / nan */
    } else {
        bits = sign | ((exp - 15u + 127u) << 23) | (man << 13);
    }
    weft_f32_bits b; b.u = bits; return b.f;
}
static inline weft_f16_t weft_f32_to_f16(float f)
{
    weft_f32_bits b; b.f = f;
    const uint32_t sign = (b.u >> 16) & 0x8000u;
    const uint32_t be = (b.u >> 23) & 0xFFu;
    const uint32_t man = b.u & 0x7FFFFFu;
    const int32_t exp = (int32_t)be - 127;
    if (be == 0xFFu) {
        return (weft_f16_t)(sign | 0x7C00u | (man ? 0x0200u : 0u));  /* inf/nan */
    }
    if (exp > 15) {
        return (weft_f16_t)(sign | 0x7C00u);                    /* overflow -> inf (RNE) */
    }
    if (exp >= -14) {
        uint32_t r = ((uint32_t)(exp + 15) << 10) | (man >> 13);
        const uint32_t rb = man & 0x1FFFu;
        if (rb > 0x1000u || (rb == 0x1000u && (r & 1u))) { r++; }
        return (weft_f16_t)(sign | r);
    }
    if (exp < -25) {
        return (weft_f16_t)sign;                               /* underflow -> 0 */
    }
    {
        const uint32_t m = man | 0x800000u;                    /* subnormal path */
        const uint32_t shift = (uint32_t)(-14 - exp);
        uint32_t r = m >> (13 + shift);
        const uint32_t rb = m & (((uint32_t)1 << (13 + shift)) - 1u);
        const uint32_t half = ((uint32_t)1 << (12 + shift));
        if (rb > half || (rb == half && (r & 1u))) {
            r++;
            if (r == 0x0400u) { return (weft_f16_t)(sign | 0x0400u); }
        }
        return (weft_f16_t)(sign | r);
    }
}

#ifdef __cplusplus
}
#endif

#endif // WEFT_PROJECTION_CORE_H

