// rust/emit_rust.c — weftc-codegen backend: Rust zero-copy projection crates
// (target rust).
//
// Guarantees for every verified struct:
//   * #[repr(C)] (+ #[repr(align(N))] when the IR demands it) — byte-identical
//     with the C header and the byte-exact GPU structs
//   * no_std, zero dependencies: the emitted module uses `core` only
//     (Law 2) — it compiles for bare-metal, MCU and kernel targets
//   * zero-allocation projection API: from_bytes / from_bytes_mut return &Self
//     views after validating length, alignment and the schema hash header
//     (Law 1); read_packed / write_packed use core::ptr::{read,write}_unaligned
//     for alignment-free by-value projection (Law 3)
//   * optional bytemuck (Pod/Zeroable) and zerocopy (0.8 trio) impls behind
//     cargo features — never compiled unless the consumer opts in
//   * zero-overhead const-fn mutation builders + bitfield accessors
//
// The shared core module (error enum + f16 codec) is emitted once per
// generation run; every struct module references it as a sibling
// (`super::weft_projection_core`) — the flat layout the test harness mounts.

#include "../weftc_codegen.h"

static const char* rs_scalar_type(weft_type_kind k, bool* uses_f16)
{
    switch (k) {
    case WT_U8: return "u8";
    case WT_I8: return "i8";
    case WT_U16: return "u16";
    case WT_I16: return "i16";
    case WT_U32: return "u32";
    case WT_I32: return "i32";
    case WT_U64: return "u64";
    case WT_I64: return "i64";
    case WT_F16: *uses_f16 = true; return "WeftF16";
    case WT_F32: return "f32";
    case WT_F64: return "f64";
    case WT_BOOL: return "bool";
    default: return "?";
    }
}

// full Rust type text for a field, e.g. "[f32; 3]" / "AxisSample"
static void rs_field_type(const weft_field* f, char out[176], bool* uses_f16, bool* uses_super)
{
    switch (f->kind) {
    case WT_VEC2F32: strcpy(out, "[f32; 2]"); break;
    case WT_VEC3F32: strcpy(out, "[f32; 3]"); break;
    case WT_VEC4F32: strcpy(out, "[f32; 4]"); break;
    case WT_VEC2F16: *uses_f16 = true; strcpy(out, "[WeftF16; 2]"); break;
    case WT_VEC3F16: *uses_f16 = true; strcpy(out, "[WeftF16; 3]"); break;
    case WT_VEC4F16: *uses_f16 = true; strcpy(out, "[WeftF16; 4]"); break;
    case WT_ARRAY: {
        weft_field tmp = *f;
        tmp.kind = f->elem_kind;
        char elem[176];
        rs_field_type(&tmp, elem, uses_f16, uses_super);
        snprintf(out, 176, "[%.150s; %u]", elem, f->count);
        break;
    }
    case WT_STRUCT:
        *uses_super = true;
        snprintf(out, 128, "%s", f->struct_type->rust_name);
        break;
    default:
        snprintf(out, 128, "%s", rs_scalar_type(f->kind, uses_f16));
        break;
    }
}

// hex with underscores: 0x8F4C_1120_A9B3_0012
static void rs_hex64(uint64_t v, char out[32])
{
    snprintf(out, 32, "0x%04X_%04X_%04X_%04X",
             (unsigned)(v >> 48) & 0xFFFFu, (unsigned)(v >> 32) & 0xFFFFu,
             (unsigned)(v >> 16) & 0xFFFFu, (unsigned)v & 0xFFFFu);
}

static void rs_hex32(uint32_t v, char out[24])
{
    snprintf(out, 24, "0x%04X_%04X", (v >> 16) & 0xFFFFu, v & 0xFFFFu);
}

// ---------------------------------------------------------------------------
// shared core module
// ---------------------------------------------------------------------------

static void emit_rust_core(strbuf* b)
{
    wsb_printf(b,
        "//! weft_projection_core — generated by weftc-codegen %s. DO NOT EDIT.\n"
        "//!\n"
        "//! Shared core for every weftc-generated Rust projection module:\n"
        "//! the error taxonomy and the dependency-free IEEE 754 binary16 codec.\n"
        "//! no_std — `core` only, no alloc (Law 2).\n"
        "#![allow(dead_code)]\n"
        "\n"
        "use core::fmt;\n"
        "\n"
        "/// Projection validation codes — mirrors `weft_error_t` in the C core.\n"
        "/// OK-success is encoded as `Ok(())`; these name every refusal mode.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n"
        "pub enum WeftError {\n"
        "    /// `len < struct size` — refused before any byte is read.\n"
        "    ShortBuffer,\n"
        "    /// buffer address violates the struct alignment requirement.\n"
        "    BadAlign,\n"
        "    /// schema hash header does not match this type.\n"
        "    SchemaMismatch,\n"
        "}\n"
        "\n"
        "impl fmt::Display for WeftError {\n"
        "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n"
        "        match self {\n"
        "            WeftError::ShortBuffer => write!(f, \"weft: buffer shorter than struct size\"),\n"
        "            WeftError::BadAlign => write!(f, \"weft: buffer address violates struct alignment\"),\n"
        "            WeftError::SchemaMismatch => write!(f, \"weft: schema hash header mismatch\"),\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "/// IEEE 754 binary16 as a bit-exact newtype over `u16` — zero deps, no\n"
        "/// `half` crate (Law 2). Round-to-nearest-even both directions,\n"
        "/// denormals and infinities exact; mirrors the C core bit for bit.\n"
        "#[derive(Clone, Copy, Default, PartialEq, Eq)]\n"
        "pub struct WeftF16(pub u16);\n"
        "\n",
        WEFTC_CODEGEN_VERSION);
    wsb_puts(b,
        "impl WeftF16 {\n"
        "    #[inline]\n"
        "    pub const fn from_bits(bits: u16) -> Self { WeftF16(bits) }\n"
        "    #[inline]\n"
        "    pub const fn to_bits(self) -> u16 { self.0 }\n"
        "\n"
        "    /// Exact half -> float (denormals normalized, inf/nan preserved).\n"
        "    #[inline]\n"
        "    pub fn to_f32(self) -> f32 {\n"
        "        let sign = ((self.0 as u32 & 0x8000) as u32) << 16;\n"
        "        let exp = ((self.0 >> 10) as u32) & 0x1F;\n"
        "        let mut man = (self.0 & 0x3FF) as u32;\n"
        "        let bits: u32;\n"
        "        if exp == 0 {\n"
        "            if man == 0 {\n"
        "                bits = sign;\n"
        "            } else {\n"
        "                let mut shift = 0u32;\n"
        "                while (man & 0x0400) == 0 { man <<= 1; shift += 1; }\n"
        "                bits = sign | ((113 - shift) << 23) | ((man & 0x03FF) << 13);\n"
        "            }\n"
        "        } else if exp == 0x1F {\n"
        "            bits = sign | 0x7F80_0000 | if man != 0 { man << 13 } else { 0 };\n"
        "        } else {\n"
        "            // exp + 112 == (exp - 15) + 127, arranged so no intermediate\n"
        "            // underflow occurs (Rust debug builds panic on u32 wrap)\n"
        "            bits = sign | ((exp + 112) << 23) | (man << 13);\n"
        "        }\n"
        "        f32::from_bits(bits)\n"
        "    }\n"
        "\n"
        "    /// Exact float -> half, round-to-nearest-even (RNE), overflow to\n"
        "    /// infinity, underflow to zero — bit-identical with the C core.\n"
        "    #[inline]\n"
        "    pub fn from_f32(f: f32) -> Self {\n"
        "        let b = f.to_bits();\n"
        "        let sign = (b >> 16) & 0x8000;\n"
        "        let be = (b >> 23) & 0xFF;\n"
        "        let man = b & 0x7F_FF_FF;\n"
        "        let exp = be as i32 - 127;\n"
        "        if be == 0xFF {\n"
        "            return WeftF16((sign | 0x7C00 | if man != 0 { 0x0200 } else { 0 }) as u16);\n"
        "        }\n"
        "        if exp > 15 {\n"
        "            return WeftF16((sign | 0x7C00) as u16);\n"
        "        }\n"
        "        if exp >= -14 {\n"
        "            let mut r = (((exp + 15) as u32) << 10) | (man >> 13);\n"
        "            let rb = man & 0x1FFF;\n"
        "            if rb > 0x1000 || (rb == 0x1000 && (r & 1) != 0) { r += 1; }\n"
        "            return WeftF16((sign | r) as u16);\n"
        "        }\n"
        "        if exp < -25 {\n"
        "            return WeftF16(sign as u16);\n"
        "        }\n"
        "        let m = man | 0x80_00_00;\n"
        "        let shift = (-14 - exp) as u32;\n"
        "        let mut r = m >> (13 + shift);\n"
        "        let rb = m & ((1u32 << (13 + shift)) - 1);\n"
        "        let half = 1u32 << (12 + shift);\n"
        "        if rb > half || (rb == half && (r & 1) != 0) {\n"
        "            r += 1;\n"
        "            if r == 0x0400 { return WeftF16((sign | 0x0400) as u16); }\n"
        "        }\n"
        "        WeftF16((sign | r) as u16)\n"
        "    }\n"
        "}\n"
        "\n"
        "impl fmt::Debug for WeftF16 {\n"
        "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n"
        "        write!(f, \"WeftF16({:#06x} = {})\", self.0, self.to_f32())\n"
        "    }\n"
        "}\n"
        "\n"
        "/// Batch schema-hash scan (scalar; the C core carries the AVX2/NEON\n"
        "/// specializations — LLVM auto-vectorizes this loop at -O2/-C opt-level=2).\n"
        "pub fn weft_validate_batch<const STRIDE: usize>(\n"
        "    bytes: &[u8],\n"
        "    read_id: impl Fn(&[u8]) -> u64,\n"
        "    expected: u64,\n"
        ") -> (usize, Option<usize>) {\n"
        "    let n = bytes.len() / STRIDE;\n"
        "    for i in 0..n {\n"
        "        let id = read_id(&bytes[i * STRIDE..]);\n"
        "        if id != expected {\n"
        "            return (i, Some(i));\n"
        "        }\n"
        "    }\n"
        "    (n, None)\n"
        "}\n"
        "\n");

    // optional bytemuck impls for the f16 newtype
    wsb_puts(b,
        "#[cfg(feature = \"bytemuck\")]\n"
        "unsafe impl bytemuck::Zeroable for WeftF16 {}\n"
        "#[cfg(feature = \"bytemuck\")]\n"
        "impl bytemuck::Pod for WeftF16 {}\n");
}

// ---------------------------------------------------------------------------
// per-struct module
// ---------------------------------------------------------------------------

static void emit_rust_struct(const weft_ir* ir, const weft_struct* s, const weft_emit_opts* o)
{
    strbuf b;
    wsb_init(&b);

    bool uses_f16 = false;
    bool uses_super = false;
    for (uint32_t f = 0; f < s->nfields; f++) {
        char ty[176];
        rs_field_type(&s->fields[f], ty, &uses_f16, &uses_super);
    }

    // ---- banner ---------------------------------------------------------
    wsb_printf(&b,
        "//! %s — generated by weftc-codegen %s (target: rust). DO NOT EDIT.\n"
        "//! module: %s | struct: %s | root: %s\n",
        s->name, WEFTC_CODEGEN_VERSION, ir->module, s->name,
        s->root ? "yes" : "no (embedded layout type)");
    if (s->root) {
        wsb_printf(&b, "//! schema_id: %s (%s)\n", s->schema_id_str,
                   s->schema_auto ? "auto: FNV-1a-64 of the canonical layout signature" : "explicit");
    }
    wsb_printf(&b,
        "//! layout: %u bytes, align %u — byte-identical with `%s` (C) and the\n"
        "//! byte-exact GPU structs (WGSL storage / GLSL std430).\n"
        "//!\n"
        "//! Laws: zero allocation on every path; no_std (`core` only); unaligned\n"
        "//! access only through read_unaligned/write_unaligned; layout is a\n"
        "//! compile-time contract via #[repr(C)].\n"
        "#![allow(dead_code)]\n"
        "\n",
        s->size, s->align, s->c_name);

    // ---- imports ---------------------------------------------------------
    wsb_printf(&b, "use super::%s::WeftError;\n", o->core_name);
    if (uses_f16) {
        wsb_printf(&b, "use super::%s::WeftF16;\n", o->core_name);
    }
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        weft_type_kind dep = (fl->kind == WT_ARRAY) ? fl->elem_kind : fl->kind;
        if (dep == WT_STRUCT) {
            wsb_printf(&b, "use super::%s::%s;\n", fl->struct_ref, fl->struct_type->rust_name);
        }
    }
    wsb_puts(&b, "\n");

    // ---- struct -----------------------------------------------------------
    if (s->repr_align) {
        wsb_printf(&b, "#[repr(C, align(%u))]\n", s->align);
    } else {
        wsb_puts(&b, "#[repr(C)]\n");
    }
    wsb_printf(&b,
        "#[derive(Clone, Copy, Debug, PartialEq)]\n"
        "pub struct %s {\n",
        s->rust_name);
    // Synthesized pads: #[repr(C)] computes offsets from the DECLARED order,
    // so every gap in the normative weft-ir layout must become an explicit
        // pad member or field offsets drift (mcu_status's 18..20 gap is the
        // fixture that proves it).
    uint32_t cursor = 0;
    int pad_idx = 0;
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        while (cursor < fl->offset) {
            uint32_t gap = fl->offset - cursor;
            const char* ty = "[u8; 1]";
            uint32_t w = 1;
            if (gap % 8u == 0u && cursor % 8u == 0u) { w = 8; }
            else if (gap % 4u == 0u && cursor % 4u == 0u) { w = 4; }
            else if (gap % 2u == 0u && cursor % 2u == 0u) { w = 2; }
            switch (w) {
            case 8: ty = "[u64; 1]"; break;
            case 4: ty = "[u32; 1]"; break;
            case 2: ty = "[u16; 1]"; break;
            default: ty = "[u8; 1]"; break;
            }
            if (gap / w > 1u) {
                wsb_printf(&b, "    /// synthesized pad (weft-ir gap %u..%u)\n", cursor, fl->offset);
                wsb_printf(&b, "    pub weft_pad%d: [%s; %u],\n", pad_idx, w == 8 ? "u64" : w == 4 ? "u32" : w == 2 ? "u16" : "u8", gap / w);
            } else {
                wsb_printf(&b, "    /// synthesized pad (weft-ir gap %u..%u)\n", cursor, fl->offset);
                wsb_printf(&b, "    pub weft_pad%d: %s,\n", pad_idx, ty);
            }
            pad_idx++;
            cursor = fl->offset;
        }
        char ty[176];
        bool f16f = false, supf = false;
        rs_field_type(fl, ty, &f16f, &supf);
        if (fl->doc) {
            wsb_printf(&b, "    /// %s\n", fl->doc);
        }
        wsb_printf(&b, "    pub %s: %s,\n", fl->name, ty);
        cursor = fl->offset + fl->size;
    }
    while (cursor < s->size) {
        uint32_t gap = s->size - cursor;
        const char* base = "u8";
        uint32_t w = 1;
        if (gap % 8u == 0u && cursor % 8u == 0u) { w = 8; base = "u64"; }
        else if (gap % 4u == 0u && cursor % 4u == 0u) { w = 4; base = "u32"; }
        else if (gap % 2u == 0u && cursor % 2u == 0u) { w = 2; base = "u16"; }
        wsb_printf(&b, "    /// synthesized tail pad (weft-ir gap %u..%u)\n", cursor, s->size);
        wsb_printf(&b, "    pub weft_pad%d: [%s; %u],\n", pad_idx, base, gap / w);
        pad_idx++;
        cursor = s->size;
    }
    wsb_printf(&b, "}\n\n");

    // ---- impl ---------------------------------------------------------------
    wsb_printf(&b, "impl %s {\n", s->rust_name);
    if (s->root) {
        char hex[40];
        if (s->schema_width == 64) {
            rs_hex64(s->schema_id, hex);
            wsb_printf(&b, "    /// 64-bit schema hash header this type projects.\n"
                           "    pub const SCHEMA_ID: u64 = %s;\n", hex);
        } else {
            rs_hex32((uint32_t)s->schema_id, hex);
            wsb_printf(&b, "    /// 32-bit schema hash header this type projects.\n"
                           "    pub const SCHEMA_ID: u32 = %s;\n", hex);
        }
    }
    wsb_printf(&b,
        "    /// Exact struct size in bytes (weft-ir normative).\n"
        "    pub const SIZE: usize = %u;\n"
        "    /// Exact struct alignment in bytes (weft-ir normative).\n"
        "    pub const ALIGN: usize = %u;\n\n",
        s->size, s->align);

    if (s->root) {
        const char* idty = (s->schema_width == 64) ? "u64" : "u32";
        wsb_printf(&b,
            "    /// Zero-copy projection: validates length, alignment and the schema\n"
            "    /// hash header, then borrows the buffer as `&Self`. No copy, no\n"
            "    /// allocation (Law 1); the check is three compares + one load.\n"
            "    #[inline(always)]\n"
            "    pub fn from_bytes(bytes: &[u8]) -> Result<&Self, WeftError> {\n"
            "        Self::validate_header(bytes)?;\n"
            "        Ok(unsafe { &*(bytes.as_ptr() as *const Self) })\n"
            "    }\n\n"
            "    /// Mutable twin (writer side: ring slots, UMEM pages).\n"
            "    #[inline(always)]\n"
            "    pub fn from_bytes_mut(bytes: &mut [u8]) -> Result<&mut Self, WeftError> {\n"
            "        Self::validate_header(bytes)?;\n"
            "        Ok(unsafe { &mut *(bytes.as_mut_ptr() as *mut Self) })\n"
            "    }\n\n"
            "    #[inline(always)]\n"
            "    fn validate_header(bytes: &[u8]) -> Result<(), WeftError> {\n"
            "        let p = bytes.as_ptr();\n"
            "        if bytes.len() < Self::SIZE {\n"
            "            return Err(WeftError::ShortBuffer);\n"
            "        }\n"
            "        if (p as usize) & (Self::ALIGN - 1) != 0 {\n"
            "            return Err(WeftError::BadAlign);\n"
            "        }\n"
            "        let id = unsafe { core::ptr::read_unaligned(p as *const %s) };\n"
            "        if id != Self::SCHEMA_ID {\n"
            "            return Err(WeftError::SchemaMismatch);\n"
            "        }\n"
            "        Ok(())\n"
            "    }\n\n",
            idty);
    }

    wsb_printf(&b,
        "    /// Byte view of this value (host little-endian) — direct\n"
        "    /// queue.writeBuffer()/vkMapMemory upload source.\n"
        "    #[inline(always)]\n"
        "    pub fn as_bytes(&self) -> &[u8; Self::SIZE] {\n"
        "        unsafe { &*(self as *const Self as *const [u8; Self::SIZE]) }\n"
        "    }\n\n"
        "    /// Alignment-free by-value read from a possibly-packed source\n"
        "    /// (Law 3). Trusted-source path: no schema validation — use\n"
        "    /// from_bytes for untrusted input.\n"
        "    #[inline]\n"
        "    pub fn read_packed(bytes: &[u8]) -> Result<Self, WeftError> {\n"
        "        if bytes.len() < Self::SIZE {\n"
        "            return Err(WeftError::ShortBuffer);\n"
        "        }\n"
        "        Ok(unsafe { core::ptr::read_unaligned(bytes.as_ptr() as *const Self) })\n"
        "    }\n\n"
        "    /// Alignment-free write to a possibly-packed destination (UMEM/DMA).\n"
        "    #[inline]\n"
        "    pub fn write_packed(&self, dst: &mut [u8]) -> Result<(), WeftError> {\n"
        "        if dst.len() < Self::SIZE {\n"
        "            return Err(WeftError::ShortBuffer);\n"
        "        }\n"
        "        unsafe { core::ptr::write_unaligned(dst.as_mut_ptr() as *mut Self, *self); }\n"
        "        Ok(())\n"
        "    }\n\n");

    // zero-overhead mutation builders
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        char ty[176];
        bool f16f = false, supf = false;
        rs_field_type(fl, ty, &f16f, &supf);
        wsb_printf(&b,
            "    /// Zero-overhead builder: `frame.with_%s(v)` consumes and returns self.\n"
            "    #[inline(always)]\n"
            "    pub const fn with_%s(mut self, %s: %s) -> Self {\n"
            "        self.%s = %s;\n"
            "        self\n"
            "    }\n\n",
            fl->name, fl->name, fl->name, ty, fl->name, fl->name);
    }

    // bitfield accessors
    for (uint32_t f = 0; f < s->nfields; f++) {
        const weft_field* fl = &s->fields[f];
        for (uint32_t bt = 0; bt < fl->nbits; bt++) {
            const weft_bits* bf = &fl->bits[bt];
            uint32_t width = bf->hi - bf->lo + 1;
            char mask[32];
            if (fl->kind == WT_U64 || fl->kind == WT_I64) {
                if (width >= 64) {
                    strcpy(mask, "0xFFFF_FFFF_FFFF_FFFF");
                } else {
                    snprintf(mask, sizeof(mask), "0x%llX", (unsigned long long)((1ull << width) - 1));
                }
            } else {
                if (width >= 32) {
                    strcpy(mask, "0xFFFF_FFFF");
                } else {
                    snprintf(mask, sizeof(mask), "0x%X", (unsigned)((1u << width) - 1));
                }
            }
            const char* castty = (fl->kind == WT_U64 || fl->kind == WT_I64) ? "u64" : "u32";
            wsb_printf(&b,
                "    /// %s.%s: bits [%u..%u] of %s\n"
                "    #[inline(always)]\n"
                "    pub const fn %s(&self) -> %s {\n"
                "        (self.%s >> %u) & %s\n"
                "    }\n"
                "    #[inline(always)]\n"
                "    pub fn set_%s(&mut self, v: %s) {\n"
                "        self.%s = (self.%s & !(%s)) | ((v & %s) << %u);\n"
                "    }\n"
                "    #[inline(always)]\n"
                "    pub const fn with_%s(mut self, v: %s) -> Self {\n"
                "        self.%s = (self.%s & !(%s)) | ((v & %s) << %u);\n"
                "        self\n"
                "    }\n\n",
                s->name, bf->name, bf->lo, bf->hi, fl->name,
                bf->name, castty,
                fl->name, bf->lo, mask,
                bf->name, castty,
                fl->name, fl->name, mask, mask, bf->lo,
                bf->name, castty,
                fl->name, fl->name, mask, mask, bf->lo);
        }
    }
    wsb_puts(&b, "}\n\n");

    // ---- optional trait impls -------------------------------------------------
    if (o->rust_bytemuck) {
        wsb_printf(&b,
            "#[cfg(feature = \"bytemuck\")]\n"
            "unsafe impl bytemuck::Zeroable for %s {}\n"
            "#[cfg(feature = \"bytemuck\")]\n"
            "impl bytemuck::Pod for %s {}\n\n",
            s->rust_name, s->rust_name);
    }
    if (o->rust_zerocopy) {
        wsb_printf(&b,
            "// zerocopy 0.8 API trio (Immutable/TryFromBytes/IntoBytes); the crate\n"
            "// must be a dependency of the consuming crate for this feature.\n"
            "#[cfg(feature = \"zerocopy\")]\n"
            "unsafe impl zerocopy::Immutable for %s {}\n"
            "#[cfg(feature = \"zerocopy\")]\n"
            "unsafe impl zerocopy::TryFromBytes for %s {}\n"
            "#[cfg(feature = \"zerocopy\")]\n"
            "unsafe impl zerocopy::IntoBytes for %s {}\n\n",
            s->rust_name, s->rust_name, s->rust_name);
    }

    char path[512];
    snprintf(path, sizeof(path), "%s/%s.rs", o->out_dir, s->name);
    weft_write_file(path, &b);
    wsb_free(&b);
}

int weft_emit_rust(const weft_ir* ir, const weft_emit_opts* o)
{
    {
        strbuf core;
        wsb_init(&core);
        emit_rust_core(&core);
        char path[512];
        snprintf(path, sizeof(path), "%s/%s.rs", o->out_dir, o->core_name);
        weft_write_file(path, &core);
        wsb_free(&core);
    }
    for (uint32_t k = 0; k < ir->nstructs; k++) {
        emit_rust_struct(ir, &ir->ss[k], o);
    }
    return 0;
}
