#!/usr/bin/env python3
"""gen_golden.py — emit the weft_tensor_view golden fixture.

INDEPENDENT ORACLE: this script re-derives every offset with plain Python
integer arithmetic (its own row-major stride products, its own span math).
It shares NO code with the C engine — the C test parsing this fixture is
therefore a cross-implementation bit-exactness proof (the house
xlang-golden pattern, pointed at geometry instead of bytes).

Line format (space-separated; '-' marks contiguous strides):
  case_id dtype ndim shape(csv) strides(csv|'-') byte_offset byte_length idx(csv) expected_offset

byte_length is the TIGHT walking span (RFC-0021 §3): for contiguous views
nelements*dtype_size; for strided views |L| + U + dtype_size where
  U    = sum of stride_k*(shape_k-1) over stride_k > 0
  |L|  = sum of |stride_k|*(shape_k-1) over stride_k < 0.
The generator refuses (exits non-zero) any case whose window would dip
below the payload base (byte_offset < |L|) — it only emits spec-conformant
goldens.

Run: python3 tests/gen_golden.py > tests/fixtures/tensor_view_golden.txt
"""

import sys

DSZ = {"u8": 1, "i8": 1, "i16": 2, "f16": 2, "bf16": 2, "f32": 4, "f64": 8}


def contiguous_strides(shape, dsz):
    strides = [0] * len(shape)
    acc = dsz
    for k in range(len(shape) - 1, -1, -1):
        strides[k] = acc
        acc *= shape[k]
    return strides


def span_of(shape, strides, dsz):
    u = sum(s * (n - 1) for s, n in zip(strides, shape) if s > 0)
    lneg = sum(-s * (n - 1) for s, n in zip(strides, shape) if s < 0)
    return lneg, u, lneg + u + dsz


def offset_of(shape, strides, byte_offset, idx):
    return byte_offset + sum(i * s for i, s in zip(idx, strides))


def emit(case_id, dtype, shape, strides, byte_offset, byte_length, idx):
    dsz = DSZ[dtype]
    if strides is None:
        strides = contiguous_strides(shape, dsz)
    lneg, u, span = span_of(shape, strides, dsz)
    if byte_offset < lneg:
        sys.exit(f"generator spec violation: {case_id} window dips below base")
    if byte_length is None:
        byte_length = span
    if byte_length < span:
        sys.exit(f"generator spec violation: {case_id} byte_length < tight span")
    off = offset_of(shape, strides, byte_offset, idx)
    print("{} {} {} {} {} {} {} {} {}".format(
        case_id, dtype, len(shape),
        ",".join(str(n) for n in shape),
        ",".join(str(s) for s in strides),
        byte_offset, byte_length,
        ",".join(str(i) for i in idx),
        off))


def main():
    print("# weft_tensor_view golden fixture — generated by gen_golden.py")
    print("# (independent Python oracle; regenerate, do not hand-edit).")
    print("# format: case dtype ndim shape strides byte_offset byte_length idx expected_offset")

    # ---- 1D audio ---------------------------------------------------------
    emit("audio_f32_512_last", "f32", [512], None, 0, None, [511])
    emit("audio_f32_512_mid", "f32", [512], None, 0, None, [256])
    emit("audio_i16_pcm_1k", "i16", [1024], None, 0, None, [999])
    # interleaved stereo: channel 1 (R) frames at stride 12B, base+16
    emit("audio_f32_stereo_R", "f32", [171], [12], 16, None, [170])
    emit("audio_f32_stereo_R_first", "f32", [171], [12], 16, None, [0])

    # ---- 2D spectrograms --------------------------------------------------
    emit("spec_f16_257x129_last", "f16", [257, 129], None, 0, None, [256, 128])
    emit("spec_f16_257x129_mid", "f16", [257, 129], None, 0, None, [128, 64])
    # padded rows: 100 f16 columns carried in a 256B row stride
    emit("spec_f16_padded_last", "f16", [64, 100], [256, 2], 0, None, [63, 99])
    emit("spec_f16_padded_first", "f16", [64, 100], [256, 2], 0, None, [0, 0])
    emit("spec_f32_mel_80x101", "f32", [80, 101], None, 0, None, [79, 100])
    # flipped (vertical flip): byte_offset at the LAST row origin
    emit("spec_f32_flip_first", "f32", [480, 640], [-2560, 4], 1226240, None, [0, 0])
    emit("spec_f32_flip_last", "f32", [480, 640], [-2560, 4], 1226240, None, [479, 639])

    # ---- 4D NCHW ----------------------------------------------------------
    emit("nchw_u8_1x3x224x224_ch2_last", "u8", [1, 3, 224, 224], None, 0, None, [0, 2, 223, 223])
    emit("nchw_u8_1x3x224x224_center", "u8", [1, 3, 224, 224], None, 0, None, [0, 1, 112, 112])
    emit("nchw_f32_4x3x224x224_last", "f32", [4, 3, 224, 224], None, 0, None, [3, 2, 223, 223])
    emit("nchw_f32_4x3x224x224_mid", "f32", [4, 3, 224, 224], None, 0, None, [3, 1, 200, 150])
    emit("nchw_bf16_1x8x56x56_last", "bf16", [1, 8, 56, 56], None, 0, None, [0, 7, 55, 55])

    # ---- 4D NHWC ----------------------------------------------------------
    emit("nhwc_u8_1x224x224x3", "u8", [1, 224, 224, 3], None, 0, None, [0, 200, 100, 2])
    emit("nhwc_f16_2x480x640x3_last", "f16", [2, 480, 640, 3], None, 0, None, [1, 479, 639, 2])

    # ---- 5D KV-cache block + windowed sub-view ----------------------------
    emit("kv_f16_2x8x128x64x2_last", "f16", [2, 8, 128, 64, 2], None, 0, None, [1, 7, 127, 63, 1])
    # a 224x224 crop window carved out of a 240x320 sensor plane, 128B in
    emit("sensor_u8_crop_first", "u8", [224, 224], [320, 1], 128 + 8 * 320 + 16, None, [0, 0])
    emit("sensor_u8_crop_last", "u8", [224, 224], [320, 1], 128 + 8 * 320 + 16, None, [223, 223])

    # ---- logits -----------------------------------------------------------
    emit("logits_u8_8x1000_last", "u8", [8, 1000], None, 0, None, [7, 999])


if __name__ == "__main__":
    main()
