/**
 * Weft Studio — deterministic multi-target codegen (7 languages).
 * Emitted sources pin layout explicitly (pad fields where the compiler would
 * insert them), so every target reproduces the managed layout byte-for-byte.
 * Same input doc + layout => identical output bytes (golden-fixture pinned).
 */

import { SchemaDoc, StructDef, PRIMS } from './schema';
import { LayoutResult, alignUp } from './layout';
import { fieldAlign, fieldSize } from './codegen-internals';

export type CodegenTarget = 'c' | 'cpp' | 'rust' | 'typescript' | 'python' | 'dart' | 'swift';
export const CODEGEN_TARGETS: readonly CodegenTarget[] = [
  'c', 'cpp', 'rust', 'typescript', 'python', 'dart', 'swift',
];

const BANNER = (lang: string, schemaHash: string) =>
  `// Generated by Weft Studio (Pillar 7) — ${lang} target — schema ${schemaHash} — DO NOT EDIT\n`;

function sortedStructs(doc: SchemaDoc): StructDef[] {
  return doc.structs.slice().sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

function padName(i: number): string {
  return `weft_pad_${i}`;
}

// ---------------------------------------------------------------- C / C++ ---

function emitC(doc: SchemaDoc, lr: LayoutResult, cpp: boolean): string {
  const out: string[] = [];
  out.push(BANNER(cpp ? 'C++' : 'C', doc.hash));
  if (cpp) out.push('#include <cstdint>\n#include <cstddef>\n');
  else out.push('#include <stdint.h>\n#include <stddef.h>\n');
  out.push('');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    let padIdx = 0;
    out.push(`/* ${s.name}: size=${L.size} align=${L.alignment} used=${L.usedBytes} padding=${L.paddingBytes} */`);
    out.push(`${cpp ? 'struct' : 'typedef struct'} ${cpp ? '' : ''}${s.name} ${cpp ? '{' : '{'}`);
    let off = 0;
    for (const f of s.fields) {
      const a = fieldAlign(s, f, doc);
      const sz = fieldSize(s, f, doc);
      const aligned = alignUp(off, a);
      if (aligned > off) {
        out.push(`  uint8_t ${padName(padIdx++)}[${aligned - off}]; /* explicit padding */`);
      }
      const ctype = cType(f.type);
      out.push(`  ${ctype} ${f.name};${f.attrs.writer !== undefined ? ` /* @writer(${f.attrs.writer}) */` : ''}`);
      off = aligned + sz;
    }
    if (off < L.size) out.push(`  uint8_t ${padName(padIdx++)}[${L.size - off}]; /* tail padding */`);
    out.push(cpp ? `}; /* sizeof == ${L.size} */` : `} ${s.name}_t; /* sizeof == ${L.size} */`);
    out.push(`_Static_assert(sizeof(${s.name}${cpp ? '' : '_t'}) == ${L.size}, "weft layout drift");`);
    if (cpp) out.push(`static_assert(alignof(${s.name}) == ${L.alignment}, "weft alignment drift");`);
    out.push('');
  }
  return out.join('\n');
}

function cType(t: string): string {
  if (PRIMS.includes(t)) return `_${t === 'bool' ? 'Bool' : 'int' + primBits(t) + '_t'}`;
  return `${t}_t`;
}
function primBits(t: string): number {
  return t === 'bool' ? 8 : parseInt(t.replace(/[iu]/, ''), 10);
}

// ----------------------------------------------------------------- Rust ----

function emitRust(doc: SchemaDoc, lr: LayoutResult): string {
  const out: string[] = [];
  out.push(BANNER('Rust', doc.hash));
  out.push('#![allow(dead_code)]');
  out.push('');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    let padIdx = 0;
    out.push(`#[repr(C, align(${L.alignment}))]`);
    out.push(`#[derive(Clone, Copy, Debug)]`);
    out.push(`pub struct ${s.name} {`);
    let off = 0;
    for (const f of s.fields) {
      const a = fieldAlign(s, f, doc);
      const sz = fieldSize(s, f, doc);
      const aligned = alignUp(off, a);
      if (aligned > off) out.push(`    pub ${padName(padIdx++)}: [u8; ${aligned - off}],`);
      out.push(`    pub ${f.name}: ${rustType(f.type)},${f.attrs.writer !== undefined ? ` // @writer(${f.attrs.writer})` : ''}`);
      off = aligned + sz;
    }
    if (off < L.size) out.push(`    pub ${padName(padIdx++)}: [u8; ${L.size - off}],`);
    out.push('}');
    out.push(`const _: () = assert!(core::mem::size_of::<${s.name}>() == ${L.size});`);
    out.push('');
  }
  return out.join('\n');
}

function rustType(t: string): string {
  if (t === 'bool') return 'bool';
  if (PRIMS.includes(t)) return t;
  return t;
}

// ------------------------------------------------------------ TypeScript ---

function emitTypeScript(doc: SchemaDoc, lr: LayoutResult): string {
  const out: string[] = [];
  out.push(BANNER('TypeScript', doc.hash));
  out.push("import { DataView } from './weft-runtime';");
  out.push('');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    out.push(`export const ${s.name}_OFFSETS = {`);
    for (const leaf of L.leaves.filter((x) => x.struct === s.name)) {
      out.push(`  ${leaf.field}: ${leaf.offset},`);
    }
    out.push(`} as const;`);
    out.push(`export const ${s.name}_SIZE = ${L.size};`);
    out.push(`export class ${s.name}View {`);
    out.push(`  static readonly SIZE = ${L.size};`);
    out.push('  constructor(private readonly dv: DataView, private readonly base = 0) {}');
    for (const leaf of L.leaves.filter((x) => x.struct === s.name)) {
      const prim = leaf.type;
      const at = `this.base + ${leaf.offset}`;
      out.push(dvAccessor(leaf.field, prim, at, leaf.writer));
    }
    out.push('}');
    out.push('');
  }
  return out.join('\n');
}

function dvAccessor(field: string, prim: string, at: string, writer: number | undefined): string {
  const w = writer !== undefined ? ` // @writer(${writer})` : '';
  switch (prim) {
    case 'u8': return `  get ${field}(): number { return this.dv.getUint8(${at}); }${w}`;
    case 'i8': return `  get ${field}(): number { return this.dv.getInt8(${at}); }${w}`;
    case 'u16': return `  get ${field}(): number { return this.dv.getUint16(${at}, true); }${w}`;
    case 'i16': return `  get ${field}(): number { return this.dv.getInt16(${at}, true); }${w}`;
    case 'u32': return `  get ${field}(): number { return this.dv.getUint32(${at}, true); }${w}`;
    case 'i32': return `  get ${field}(): number { return this.dv.getInt32(${at}, true); }${w}`;
    case 'u64': return `  get ${field}(): bigint { return this.dv.getBigUint64(${at}, true); }${w}`;
    case 'i64': return `  get ${field}(): bigint { return this.dv.getBigInt64(${at}, true); }${w}`;
    case 'f32': return `  get ${field}(): number { return this.dv.getFloat32(${at}, true); }${w}`;
    case 'f64': return `  get ${field}(): number { return this.dv.getFloat64(${at}, true); }${w}`;
    case 'bool': return `  get ${field}(): boolean { return this.dv.getUint8(${at}) !== 0; }${w}`;
    default: return `  // nested struct ${field}: see ${prim}View at offset ${at.replace('this.base + ', '')}${w}`;
  }
}

// ---------------------------------------------------------------- Python ---

function emitPython(doc: SchemaDoc, lr: LayoutResult): string {
  const out: string[] = [];
  out.push(BANNER('Python', doc.hash));
  out.push('import struct');
  out.push('');
  out.push('FIELD_TABLES = {');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    const fields = L.leaves.filter((x) => x.struct === s.name);
    const entries = fields.map((l) => `'${l.field}': (${l.offset}, '${pyFmt(l.type)}')`).join(', ');
    out.push(`    '${s.name}': {${entries}},`);
  }
  out.push('}');
  out.push('');
  out.push('STRUCT_SIZES = {');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (L) out.push(`    '${s.name}': ${L.size},`);
  }
  out.push('}');
  out.push('');
  out.push('class WeftStructView:');
  out.push('    """Zero-copy flyweight over a little-endian buffer (Pillar 6 pattern)."""');
  out.push('    __slots__ = ("_buf", "_offset")');
  out.push('    def __init__(self, buf, offset=0):');
  out.push('        self._buf = buf');
  out.push('        self._offset = offset');
  return out.join('\n') + '\n';
}

function pyFmt(t: string): string {
  switch (t) {
    case 'u8': return 'B'; case 'i8': return 'b';
    case 'u16': return 'H'; case 'i16': return 'h';
    case 'u32': return 'I'; case 'i32': return 'i';
    case 'u64': return 'Q'; case 'i64': return 'q';
    case 'f32': return 'f'; case 'f64': return 'd';
    case 'bool': return 'B';
    default: return `${t}#nested`;
  }
}

// ------------------------------------------------------------------ Dart ---

function emitDart(doc: SchemaDoc, lr: LayoutResult): string {
  const out: string[] = [];
  out.push(BANNER('Dart', doc.hash));
  out.push("import 'dart:typed_data';");
  out.push('');
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    out.push(`class ${s.name}View {`);
    out.push(`  static const int size = ${L.size};`);
    out.push('  final ByteData _bd;');
    out.push('  final int _base;');
    out.push('  const ${C}.(this._bd, this._base);'.replace('${C}.(', `// ctor: `));
    out.push(`  ${s.name}View.of(this._bd, [this._base = 0]);`);
    for (const leaf of L.leaves.filter((x) => x.struct === s.name)) {
      out.push(dartAccessor(leaf.field, leaf.type, leaf.offset, leaf.writer));
    }
    out.push('}');
    out.push('');
  }
  return out.join('\n');
}

function dartAccessor(field: string, prim: string, offset: number, writer: number | undefined): string {
  const w = writer !== undefined ? ` // @writer(${writer})` : '';
  switch (prim) {
    case 'u8': return `  int get ${field} => _bd.getUint8(_base + ${offset});${w}`;
    case 'i8': return `  int get ${field} => _bd.getInt8(_base + ${offset});${w}`;
    case 'u16': return `  int get ${field} => _bd.getUint16(_base + ${offset}, Endian.little);${w}`;
    case 'i16': return `  int get ${field} => _bd.getInt16(_base + ${offset}, Endian.little);${w}`;
    case 'u32': return `  int get ${field} => _bd.getUint32(_base + ${offset}, Endian.little);${w}`;
    case 'i32': return `  int get ${field} => _bd.getInt32(_base + ${offset}, Endian.little);${w}`;
    case 'u64': return `  int get ${field} => _bd.getUint64(_base + ${offset}, Endian.little);${w}`;
    case 'i64': return `  int get ${field} => _bd.getInt64(_base + ${offset}, Endian.little);${w}`;
    case 'f32': return `  double get ${field} => _bd.getFloat32(_base + ${offset}, Endian.little);${w}`;
    case 'f64': return `  double get ${field} => _bd.getFloat64(_base + ${offset}, Endian.little);${w}`;
    case 'bool': return `  bool get ${field} => _bd.getUint8(_base + ${offset}) != 0;${w}`;
    default: return `  // nested: ${prim} at +${offset}${w}`;
  }
}

// ----------------------------------------------------------------- Swift ---

function emitSwift(doc: SchemaDoc, lr: LayoutResult): string {
  const out: string[] = [];
  out.push(BANNER('Swift', doc.hash));
  for (const s of sortedStructs(doc)) {
    const L = lr.layouts.get(s.name);
    if (!L) continue;
    let padIdx = 0;
    out.push(`// ${s.name}: size=${L.size} align=${L.alignment}`);
    out.push(`struct ${s.name} {`);
    let off = 0;
    for (const f of s.fields) {
      const a = fieldAlign(s, f, doc);
      const sz = fieldSize(s, f, doc);
      const aligned = alignUp(off, a);
      if (aligned > off) out.push(`  var ${padName(padIdx++)}: (UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8) /* padding ${aligned - off}B */`);
      out.push(`  var ${f.name}: ${swiftType(f.type)}${f.attrs.writer !== undefined ? ` // @writer(${f.attrs.writer})` : ''}`);
      off = aligned + sz;
    }
    if (off < L.size) out.push(`  var ${padName(padIdx++)}: (UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8) /* tail padding ${L.size - off}B */`);
    out.push('}');
    out.push('');
  }
  return out.join('\n');
}

function swiftType(t: string): string {
  switch (t) {
    case 'bool': return 'Bool';
    case 'f32': return 'Float';
    case 'f64': return 'Double';
    case 'u64': return 'UInt64'; case 'i64': return 'Int64';
    case 'u32': return 'UInt32'; case 'i32': return 'Int32';
    case 'u16': return 'UInt16'; case 'i16': return 'Int16';
    case 'u8': return 'UInt8'; case 'i8': return 'Int8';
    default: return t;
  }
}

// ----------------------------------------------------------------- entry ---

export function generate(target: CodegenTarget, doc: SchemaDoc, lr: LayoutResult): string {
  switch (target) {
    case 'c': return emitC(doc, lr, false);
    case 'cpp': return emitC(doc, lr, true);
    case 'rust': return emitRust(doc, lr);
    case 'typescript': return emitTypeScript(doc, lr);
    case 'python': return emitPython(doc, lr);
    case 'dart': return emitDart(doc, lr);
    case 'swift': return emitSwift(doc, lr);
  }
}
