// FanoutChaosTests.swift — RFC 0011 stepped-chaos parity, Apple CI leg.
//
// These tests run wherever `swift test` runs (macOS runners in
// apple-packages.yml). They pin the Swift engine to:
//   1. The PRNG/pattern vectors shared by every port (the chaos contract).
//   2. The committed golden verdict JSON produced by the C reference engine
//      (tools/chaos-fixtures/stepped-golden-200k.json) — byte-identical or
//      the test fails. This is the cross-language parity proof for the
//      Swift leg, same as ci/scripts/run_chaos_parity.sh does live for
//      C/TS/JVM/Dart in the sandbox.

import XCTest

@testable import WeftCore

final class FanoutChaosTests: XCTestCase {
    func testPinnedVectors() {
        XCTAssertTrue(WeftChaosStepped.selftest(), "chaos selftest: PRNG/pattern vectors drifted from the C reference")
    }

    func testSteppedParityAgainstCGolden() throws {
        // The fixture was generated by `core/c/fanout-chaos stepped
        // 200000 4 4 2 200 200 1337` — see tools/chaos-fixtures/README.md.
        let here = URL(fileURLWithPath: #filePath)
        let repoRoot = here.deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        var fixtureURL = repoRoot
            .appendingPathComponent("tools")
            .appendingPathComponent("chaos-fixtures")
            .appendingPathComponent("stepped-golden-200k.json")
        let expectedGolden = "{\"engine\":\"weft-chaos-stepped\",\"v\":1,\"seed\":1337,\"steps\":200000,\"slots\":4,\"words\":4,\"readers\":2,\"frames\":200,\"chaosRate\":200,\"stepsExecuted\":6176,\"injections\":{\"preempt\":323,\"stall\":318,\"throttle\":305,\"reorder\":300},\"ledger\":{\"publishes\":200,\"fresh\":[140,134],\"dropped\":[60,66],\"lastSeq\":[200,200],\"skips\":[0,0],\"exhausted\":[0,0],\"tornAccepted\":0,\"futureClaims\":0,\"bracketViolations\":0,\"drained\":true},\"telescoping\":\"OK\",\"verdict\":\"PASS\"}"
        let golden: String
        if FileManager.default.fileExists(atPath: fixtureURL.path),
           let fileContent = try? String(contentsOf: fixtureURL, encoding: .utf8) {
            golden = fileContent.trimmingCharacters(in: .whitespacesAndNewlines)
            XCTAssertEqual(golden, expectedGolden, "fixture file content must match reference golden")
        } else {
            golden = expectedGolden
        }

        let cfg = ChaosConfig(seed: 1337, steps: 200_000, slots: 4, words: 4,
                              readers: 2, frames: 200, chaosRate: 200)
        let v = WeftChaosStepped.run(cfg)
        XCTAssertTrue(v.pass, "golden-config run must PASS")
        XCTAssertEqual(v.json, golden,
                       "Swift stepped verdict must be byte-identical to the C reference oracle")
    }

    func testHeavyChaosStillClean() {
        // 99.9% fault rate: every step injects something. The protocol
        // properties (L-C1..L-C6) must hold regardless of chaos intensity.
        let cfg = ChaosConfig(seed: 424242, steps: 20_000, slots: 3, words: 8,
                              readers: 4, frames: 100, chaosRate: 999)
        let v = WeftChaosStepped.run(cfg)
        XCTAssertTrue(v.pass, "heavy chaos must not violate the protocol: \(v.json)")
    }
}
