# test_cluster_wire.py — cross-language WCN1 wire parity (Python side).
# The fixture is generated by packages/weft-cluster/test/crosslang_vectors.mjs
# and frozen; both languages must decode identical bytes to identical results.
import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from weft_cluster import wire, errors, WCN1_HEADER_SIZE  # noqa: E402

VEC = json.loads(
    (Path(__file__).resolve().parents[2] / "fixtures" / "cluster" / "wcn1_vectors.json")
    .read_text())


def test_full_field_vector_decodes_byte_exactly():
    c = VEC["cases"][0]
    e = c["expect"]
    raw = bytes.fromhex(c["hex"])
    mv = memoryview(raw)
    frame = wire.Frame()
    code = wire.decode_wcn1_into(mv, 0, frame)
    assert code == errors.WC_OK
    assert frame.version == e["version"] == 1
    assert frame.header_size == e["headerSize"] == 64
    assert frame.flags == e["flags"] == 5  # INLINE | CRC
    assert frame.src_node == e["srcNode"]
    assert frame.topic_hash == (e["topicHash"]["hi"] << 32) | e["topicHash"]["lo"]
    assert frame.seq == (e["seq"]["hi"] << 32) | e["seq"]["lo"]
    assert frame.timestamp_ns == (e["ts"]["hi"] << 32) | e["ts"]["lo"]
    assert frame.payload_len == e["payloadLen"]
    assert frame.schema_id == e["schemaId"]
    assert frame.crc == e["crc"]
    assert bytes(frame.payload).hex() == e["payloadHex"]
    assert wire.verify_frame_crc(frame) == errors.WC_OK


def test_malformed_vectors_map_to_identical_error_codes():
    for m in VEC["malformed"]:
        raw = bytes.fromhex(m["hex"])
        frame = wire.Frame()
        code = wire.decode_wcn1_into(memoryview(raw), 0, frame)
        if m["name"] == "bad-crc" and code == errors.WC_OK:
            code = wire.verify_frame_crc(frame)
        assert code == m["code"], f"malformed case {m['name']}: {code} != {m['code']}"


def test_fnv1a64_reference_vectors():
    for input_str, expected in VEC["fnv"].items():
        got = wire.topic_hash64(input_str)
        assert got == int(expected, 16), f"fnv1a64({input_str!r})"


def test_crc32_reference_vectors_match_ts():
    for input_str, expected in VEC["crc32"].items():
        assert wire.crc32_ieee(input_str.encode()) == expected


def test_python_encode_is_byte_compatible_with_ts_decode_path():
    """Python-encode a datagram, decode with the same strict rules the TS
    decoder applies, and verify every field — the inverse direction the TS
    consumer runs when a Python producer publishes."""
    payload = b"py-producer-frame"
    topic = "trades"
    th = wire.topic_hash64(topic)
    seq = (1 << 32) | 7  # exercise the hi word
    ts = 0x1122334455667788
    datagram = wire.encode_wcn1(
        wire.WC_FLAG_INLINE_PAYLOAD | wire.WC_FLAG_CRC_PRESENT,
        src_node=9, topic_hash=th, seq=seq, timestamp_ns=ts,
        payload=payload, schema_id=3)
    assert len(datagram) == WCN1_HEADER_SIZE + len(payload)
    frame = wire.Frame()
    code = wire.decode_wcn1_into(memoryview(bytes(datagram)), 0, frame)
    assert code == errors.WC_OK
    assert frame.src_node == 9
    assert frame.topic_hash == th
    assert frame.seq == seq
    assert frame.timestamp_ns == ts
    assert bytes(frame.payload) == payload
    assert wire.verify_frame_crc(frame) == errors.WC_OK


def test_wgs1_gossip_round_trip():
    entries = [
        {"node_id": 1, "addr": 0x0100007F, "gossip_port": 5101,
         "entry_flags": 1, "last_seen_ms": 100, "incarnation": 0, "data_port": 6101},
        {"node_id": 2, "addr": 0, "gossip_port": 5102,
         "entry_flags": 2, "last_seen_ms": 200, "incarnation": 3, "data_port": 6102},
    ]
    raw = wire.encode_wgs1(1, entries, gossip_round=11,
                           sender_monotonic_ns=123456, boot_id=99,
                           sender_flags=1)
    assert len(raw) == wire.WGS1_HEADER_SIZE + 2 * wire.WGS1_ENTRY_SIZE
    g = {}
    mv = memoryview(raw)
    assert wire.decode_wgs1_into(mv, g) == errors.WC_OK
    assert g["sender_node"] == 1
    assert g["entry_count"] == 2
    assert g["gossip_round"] == 11
    e0 = wire.read_gossip_entry(mv, 0)
    assert e0["node_id"] == 1 and e0["gossip_port"] == 5101 and e0["data_port"] == 6101
    e1 = wire.read_gossip_entry(mv, 1)
    assert e1["entry_flags"] == 2 and e1["incarnation"] == 3
