#!/usr/bin/env python3
"""Generate weft_crc32c_tables.h - slicing-by-8 tables for CRC-32C (Castagnoli).

Table[0] is the standard reflected CRC-32C table (poly 0x82F63B78).
Table[k] for k >= 1 is derived by the standard recurrence:
    T_k[i] = (T_{k-1}[i] >> 8) ^ T_0[T_{k-1}[i] & 0xFF]
which is the classic zlib/Intel slicing-by-8 construction.

The generated header is deterministic and checked into the pillar; this
script is the provenance artifact for the audit report (D-61).

Check value (validation happens in the C test suite):
    crc32c("123456789") == 0xE3069283
    crc32c(32 zero bytes) == 0x8A9136AA
"""
import sys

POLY = 0x82F63B78  # CRC-32C, reflected (reverse of 0x1EDC6F41)


def base_table():
    t = []
    for i in range(256):
        c = i
        for _ in range(8):
            c = (c >> 1) ^ (POLY if (c & 1) else 0)
        t.append(c)
    return t


def main(out_path):
    tables = [base_table()]
    for _ in range(1, 8):
        prev = tables[-1]
        nxt = []
        for i in range(256):
            c = prev[i]
            nxt.append((c >> 8) ^ tables[0][c & 0xFF])
        tables.append(nxt)

    # Self-check: T0 must reproduce the classic implementation on a vector.
    def crc_ref(data):
        crc = 0xFFFFFFFF
        for b in data:
            crc = (crc >> 8) ^ tables[0][(crc ^ b) & 0xFF]
        return crc ^ 0xFFFFFFFF

    v1 = crc_ref(b"123456789")
    v2 = crc_ref(bytes(32))
    assert v1 == 0xE3069283, hex(v1)
    assert v2 == 0x8A9136AA, hex(v2)

    with open(out_path, "w", encoding="ascii") as f:
        f.write("/*\n")
        f.write(" * weft_crc32c_tables.h - CRC-32C slicing-by-8 coefficient tables.\n")
        f.write(" * GENERATED by scripts/gen_crc32c_tables.py - DO NOT EDIT BY HAND.\n")
        f.write(" * Poly: 0x82F63B78 (reflected Castagnoli). Check: crc32c(\"123456789\") == 0xE3069283.\n")
        f.write(" * Weft Pillar 6 (weft-adapters) - private include, not part of the frozen C-ABI.\n")
        f.write(" */\n")
        f.write("#ifndef WEFT_CRC32C_TABLES_H\n#define WEFT_CRC32C_TABLES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        f.write("static const uint32_t weft_crc32c_slice8[8][256] = {\n")
        for k, tbl in enumerate(tables):
            f.write("    { /* lane %d */\n" % k)
            for row in range(0, 256, 8):
                vals = ", ".join("0x%08Xu" % tbl[i] for i in range(row, row + 8))
                f.write("        %s%s\n" % (vals, "," if row + 8 < 256 else ""))
            f.write("    }%s\n" % ("," if k < 7 else ""))
        f.write("};\n\n")
        f.write("#ifdef __cplusplus\n}\n#endif\n\n")
        f.write("#endif /* WEFT_CRC32C_TABLES_H */\n")

    print("wrote %s (check vectors OK: 0xE3069283, 0x8A9136AA)" % out_path)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else
         "/home/z/my-project/weft-repo/core/c/src/adapters/weft_crc32c_tables.h")
