// test/layout.test.mjs — WTR1 layout primitives: CRC oracle, f16 vectors,
// fail-closed header validation matrix (Law 4).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { crc32 as zlibCrc32 } from 'node:zlib';
import { readFileSync } from 'node:fs';

import {
  RING_HEADER_SIZE, SLOT_HEADER_SIZE, OFF_PRODUCER_SEQ, OFF_HEADER_CRC, OFF_FLAGS,
  RING_FLAG_LITTLE_ENDIAN, f16FromBits, f16ToBits, ringHeaderCrc, validateRingHeader,
  LayoutError, fourccFromString, fourccToString, DLPackCode, isValidDtype,
} from '../src/layout.js';
import { WeftTensorRing } from '../src/ring.js';

const FIXTURES = new URL('../../../fixtures/weft-tensor/', import.meta.url);
const f32Bin = readFileSync(new URL('ring-v1-f32.bin', FIXTURES));
const u8Bin = readFileSync(new URL('ring-v1-u8.bin', FIXTURES));

// ---------------------------------------------------------------- CRC oracle

test('crc32 matches node:zlib over the static header region', () => {
  for (const bin of [f32Bin, u8Bin]) {
    const ab = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength);
    const dv = new DataView(ab);
    const staticRegion = new Uint8Array(ab.slice(0, 96));
    const tail = new Uint8Array(ab.slice(104, 112));
    const merged = new Uint8Array(96 + 8);
    merged.set(staticRegion); merged.set(tail, 96);
    const expected = zlibCrc32(merged) >>> 0;
    const embedded = dv.getUint32(OFF_HEADER_CRC, true);
    assert.equal(ringHeaderCrc(dv), expected, 'our CRC == zlib CRC');
    assert.equal(embedded, expected, 'embedded CRC == zlib CRC');
  }
});

// ------------------------------------------------------------- f16 vs numpy

// Golden vectors generated by numpy float16 (scripts log, Pillar 2 P2).
const F16_FROM_BITS = [
  [0, 0.0], [32768, -0.0], [15360, 1.0], [48128, -1.0], [14336, 0.5],
  [16384, 2.0], [31743, 65504.0], [1024, 6.103515625e-05],
  [1023, 6.097555160522461e-05], [13312, 0.25], [16968, 3.140625],
  [18688, 10.0], [22080, 100.0], [15872, 1.5], [49408, -2.5],
  [13653, 0.333251953125],
  [31744, Infinity], [64512, -Infinity],
  [1, 5.960464477539063e-08], [1023, 6.097555160522461e-05],
  [0, 0.0], [32768, -0.0],
];

test('f16FromBits matches numpy float16 decode exactly', () => {
  for (const [bits, value] of F16_FROM_BITS) {
    const got = f16FromBits(bits);
    if (Number.isNaN(value)) assert.ok(Number.isNaN(got));
    else assert.ok(Object.is(got, value), `bits ${bits}: got ${got}, want ${value}`);
  }
  assert.ok(Number.isNaN(f16FromBits(0x7e00)));
  assert.ok(Number.isNaN(f16FromBits(0x7d00)));
});

test('f16ToBits matches numpy round-to-nearest-even', () => {
  for (const [bits, value] of F16_FROM_BITS) {
    if (!Number.isFinite(value)) continue;
    assert.equal(f16ToBits(value), bits, `value ${value}`);
  }
  // specials
  assert.equal(f16ToBits(Infinity), 0x7c00);
  assert.equal(f16ToBits(-Infinity), 0xfc00);
  assert.equal((f16ToBits(NaN) & 0x7c00), 0x7c00, 'NaN keeps exponent bits');
  // overflow -> Inf
  assert.equal(f16ToBits(65536.0), 0x7c00);
  assert.equal(f16ToBits(-70000.0), 0xfc00);
  // underflow -> signed zero
  assert.equal(f16ToBits(1e-9), 0x0000);
  assert.equal(f16ToBits(-1e-9), 0x8000);
  // round-to-nearest-even boundary: 1 + 2^-11 (tie) -> 1.0 (even)
  assert.equal(f16ToBits(1 + 2 ** -11), 15360);
  // 1 + 2^-10 + epsilon rounds up
  assert.equal(f16ToBits(1 + 2 ** -10 + 2 ** -20), (15360 + 1));
});

// ---------------------------------------------------------------- fourcc

test('fourcc round-trips as LE ASCII', () => {
  for (const s of ['RGBA', 'BGRA', 'I420', 'PCM ', 'F32 ', 'RAW ']) {
    assert.equal(fourccToString(fourccFromString(s)), s);
  }
  assert.equal(fourccFromString('RGBA') >>> 0, 0x41424752); // LE bytes 'R','G','B','A'
});

// ------------------------------------------------- validation corruption matrix

function corrupt(bin, write) {
  const ab = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength);
  write(new DataView(ab));
  return ab;
}

test('validateRingHeader accepts both golden fixtures', () => {
  for (const bin of [f32Bin, u8Bin]) {
    const ab = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength);
    const layout = validateRingHeader(ab);
    assert.equal(layout.version, 1);
    assert.equal(layout.slotCount, 4);
    assert.equal(layout.slotStride, 128);
    assert.equal(layout.payloadCap, 64);
    assert.equal(layout.tickHz, 120);
    assert.equal(layout.flags, RING_FLAG_LITTLE_ENDIAN | 2);
    assert.equal(layout.schemaId, 0xA11CE00000000001);
  }
  const lf = validateRingHeader(f32Bin.buffer.slice(f32Bin.byteOffset, f32Bin.byteOffset + f32Bin.byteLength));
  assert.deepEqual([lf.dtype.code, lf.dtype.bits], [DLPackCode.FLOAT, 32]);
  assert.equal(lf.rank, 2);
  assert.deepEqual(Array.from(lf.shape.slice(0, 3)), [2, 3, 0]);
  assert.deepEqual(Array.from(lf.strides.slice(0, 2)), [3, 1]);
  const lu = validateRingHeader(u8Bin.buffer.slice(u8Bin.byteOffset, u8Bin.byteOffset + u8Bin.byteLength));
  assert.equal(lu.rank, 3);
  assert.deepEqual(Array.from(lu.shape.slice(0, 4)), [2, 2, 4, 0]);
});

test('fail-closed corruption matrix — every mutation gets a machine-readable code', () => {
  const cases = [
    ['WTR1_BAD_MAGIC', (dv) => dv.setUint8(0, 0x58)],
    ['WTR1_BAD_VERSION', (dv) => dv.setUint16(4, 2, true)],
    ['WTR1_BAD_HEADER_SIZE', (dv) => dv.setUint16(6, 256, true)],
    ['WTR1_BAD_SLOT_COUNT', (dv) => dv.setUint32(8, 1, true)],
    ['WTR1_BAD_SLOT_STRIDE', (dv) => dv.setUint32(12, 100, true)],
    ['WTR1_BAD_DTYPE', (dv) => dv.setUint8(16, 9)],
    ['WTR1_BAD_DTYPE', (dv) => dv.setUint16(18, 2, true)], // lanes != 1 -> same fail-closed family
    ['WTR1_BAD_ELEM_SIZE', (dv) => dv.setUint32(20, 3, true)],
    ['WTR1_BAD_STRIDES', (dv) => dv.setUint32(60, 0, true)], // unit stride zeroed -> insane
    ['WTR1_SEQ_OVERFLOW', (dv) => dv.setUint32(OFF_PRODUCER_SEQ + 4, 0x200000, true)],
    ['WTR1_NOT_LITTLE_ENDIAN', (dv) => dv.setUint32(OFF_FLAGS, 2, true)],
    ['WTR1_BAD_CRC', (dv) => dv.setUint32(OFF_HEADER_CRC, 0xdeadbeef, true)],
  ];
  for (const [code, write] of cases) {
    const ab = corrupt(f32Bin, write);
    assert.throws(() => validateRingHeader(ab), (e) => {
      assert.ok(e instanceof LayoutError, `expected LayoutError, got ${e}`);
      assert.equal(e.code, code, `expected code ${code}, got ${e.code}`);
      return true;
    }, `mutation for ${code} must fail closed`);
  }
  // Short buffers
  assert.throws(() => validateRingHeader(new ArrayBuffer(64)), (e) => e.code === 'WTR1_SHORT');
  const truncated = new Uint8Array(f32Bin).slice(0, 600);
  assert.throws(() => validateRingHeader(truncated.buffer), (e) => e.code === 'WTR1_SHORT_RING');
});

test('dtype validity table', () => {
  assert.equal(isValidDtype(DLPackCode.FLOAT, 16), true);
  assert.equal(isValidDtype(DLPackCode.UINT, 8), true);
  assert.equal(isValidDtype(DLPackCode.INT, 64), true);
  assert.equal(isValidDtype(DLPackCode.BOOL, 8), true);
  assert.equal(isValidDtype(DLPackCode.FLOAT, 12), false);
  assert.equal(isValidDtype(DLPackCode.BFLOAT, 16), false); // reserved for V2
});

// ------------------------------------------------------- ring header builder

test('create() writes a self-validating header (round trip through attach)', () => {
  const ring = WeftTensorRing.create({
    slotCount: 3, payloadCap: 48, dtype: { code: DLPackCode.FLOAT, bits: 32 },
    shape: [2, 6], schemaId: 0x1234567890abcdn, tickHz: 60, fourcc: 'F32 ',
  });
  const again = WeftTensorRing.attach(ring.buffer);
  assert.equal(again.layout.schemaId, Number(0x1234567890abcdn));
  assert.equal(again.slotCount, 3);
  assert.equal(again.describe().includes('shape=[2x6]'), true);
  assert.equal(isValidDtype(again.layout.dtype.code, again.layout.dtype.bits), true);
  assert.ok(RING_HEADER_SIZE === 128 && SLOT_HEADER_SIZE === 64);
});
