// audio_peak.glsl — generated by weftc-codegen 0.1.0 (target: glsl). DO NOT EDIT.
// module: audio | struct: audio_peak | schema_id: 0x06EF25278BA8C8C2
// host layout: 16 bytes, align 8
//
// WEFT-GPU-NOT-EXACT: audio_peak — std430 variant WITHHELD (Law 4)
// reason: field levels_db (aggregate): array element: GLSL struct members of float16_t need rarely-enabled extensions; use f32 or the wgsl target
// remediation: widen 8/16-bit integers to u32, replace bool with u32
//   flags + bitfields, or keep this struct host-side.
// The refusal is total: no struct is emitted, because a struct with a
// silently-wrong layout is worse than no struct.
