// audio_peak_validate.wgsl — generated by weftc-codegen 0.1.0. DO NOT EDIT.
// Direct-consumption proof: a compute shader reading an array of AudioPeak
// straight out of a storage buffer (bytes written by C/Rust, no
// repacking) and validating every schema hash GPU-side.
//   binding 0: read-only storage — array<AudioPeak>
//   binding 1: read_write storage — u32 triple [ok, bad_index+1, total]

enable f16;

// address space: storage (std430-equivalent) — byte-exact
struct AudioPeak {
  schema_id: u64,         // @0 (8)
  levels_db: array<f16, 4>,        // @8 (8)
}; // size 16, align 8

@group(0) @binding(0) var<storage, read> frames_in: array<AudioPeak>;
@group(0) @binding(1) var<storage, read_write> scan: array<u32>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  let n = arrayLength(&frames_in);
  if (i >= n) {
    return;
  }
  atomicAdd(&scan[2], 1u);
  if (frames_in[i].schema_id == 0x06EF25278BA8C8C2u) {
    atomicAdd(&scan[0], 1u);
  } else {
    atomicExchange(&scan[1], i + 1u);
  }
}
