// audio_peak.wgsl — generated by weftc-codegen 0.1.0 (target: wgsl). DO NOT EDIT.
// module: audio | struct: audio_peak | schema_id: 0x06EF25278BA8C8C2
// host layout: 16 bytes, align 8
// storage variant: BYTE-EXACT with the host struct — members sit at the
// same offsets as the C/Rust projections; upload host bytes unchanged
// via queue.writeBuffer() into a storage buffer. No host repacking.
// uniform variant: REFUSED (Law 4) — field schema_id (scalar): u64/i64 are not permitted in the uniform address space (WGSL; std140 has no 64-bit integers) — use the storage variant
//
enable f16;
//
// address space: storage (std430-equivalent) — byte-exact
struct AudioPeak {
  schema_id: u64,         // @0 (8)
  levels_db: array<f16, 4>,        // @8 (8)
}; // size 16, align 8

