// AUTO-GENERATED by weftc-managed/1.0.0 (dart) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/imu_sample.json (irVersion 1) · struct ImuSample · 32 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/imu_sample.json --target dart
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import 'dart:ffi' as ffi;
import 'dart:typed_data';

/// Zero-copy managed projections over ImuSample.
/// Header-less 32-byte lean payload: exercises the no-handshake validateHeader() path (bounds check only) and proves backends emit correct code when no const/role fields exist.
///
/// Layout (little-endian):
///   0x00  u64  timestampNs
///   0x08  f32[3]  accel
///   0x14  f32[3]  gyro
///
/// Steady-state reads and writes allocate nothing (Law 1): create the
/// view once, then bind() for every frame. Every multi-byte access
/// passes Endian.little explicitly (Law 2).

/// dart:ffi projection for native memory (offset-order declaration;
/// the IR's natural alignment guarantees an identical layout).
final class ImuSampleFfi extends ffi.Struct {
  /// @byteOffset 0 (u64)
  external ffi.Uint64 timestamp_ns;
  /// @byteOffset 8 (f32[3])
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> accel;
  /// @byteOffset 20 (f32[3])
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> gyro;
}

/// High-level zero-copy view over a ByteData window (Flutter hot path).
class ImuSample {
  static const int byteLength = 32;
  /// @byteOffset 0 (u64)
  static const int timestampNsOffset = 0;
  /// @byteOffset 8 (f32[3])
  static const int accelOffset = 8;
  /// @byteOffset 20 (f32[3])
  static const int gyroOffset = 20;

  ByteData? _bd;
  int _offset = 0;

  /// True once bound.
  bool get isBound => _bd != null;

  /// Absolute offset within the bound ByteData.
  int get byteOffset => _offset;

  /// COLD PATH — rebinds this instance in place (zero copy).
  ImuSample bind(ByteData bd, [int byteOffset = 0]) {
    if (byteOffset < 0 || byteOffset + byteLength > bd.lengthInBytes) {
      throw RangeError('ImuSample.bind: window [$byteOffset..${byteOffset + byteLength}) exceeds ${bd.lengthInBytes} bytes');
    }
    _bd = bd;
    _offset = byteOffset;
    return this;
  }

  /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
  bool validateHeader([int? avail]) {
    final bd = _bd;
    if (bd == null) { return false; }
    return true;
  }

  /// Monotonic hardware timestamp, nanoseconds.
  /// @byteOffset 0x00 (u64)
  int get timestampNs {
    final bd = _bd!;
    return bd.getUint64(_offset + 0, Endian.little);
  }

  set timestampNs(int value) {
    final bd = _bd!;
    bd.setUint64(_offset + 0, value, Endian.little);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  ImuSample withTimestampNs(int value) {
    timestampNs = value;
    return this;
  }

  /// Low 32 bits of timestampNs @0x0 — primitive-only path.
  int get timestampNsLo => _bd!.getUint32(_offset + 0, Endian.little);
  /// High 32 bits of timestampNs @0x4.
  int get timestampNsHi => _bd!.getUint32(_offset + 4, Endian.little);
  set timestampNsLo(int value) => _bd!.setUint32(_offset + 0, value, Endian.little);
  set timestampNsHi(int value) => _bd!.setUint32(_offset + 4, value, Endian.little);
  ImuSample withTimestampNsLo(int value) { timestampNsLo = value; return this; }
  ImuSample withTimestampNsHi(int value) { timestampNsHi = value; return this; }

  /// Linear acceleration, g.
  /// @byteOffset 0x08 (f32[3])
  double getAccelAt(int index) {
    final bd = _bd!;
    return bd.getFloat32(_offset + 8 + index * 4, Endian.little);
  }

  void setAccelAt(int index, double value) {
    final bd = _bd!;
    bd.setFloat32(_offset + 8 + index * 4, value, Endian.little);
  }
  ImuSample withAccelAt(int index, double value) {
    setAccelAt(index, value);
    return this;
  }

  /// Angular rate, rad/s.
  /// @byteOffset 0x14 (f32[3])
  double getGyroAt(int index) {
    final bd = _bd!;
    return bd.getFloat32(_offset + 20 + index * 4, Endian.little);
  }

  void setGyroAt(int index, double value) {
    final bd = _bd!;
    bd.setFloat32(_offset + 20 + index * 4, value, Endian.little);
  }
  ImuSample withGyroAt(int index, double value) {
    setGyroAt(index, value);
    return this;
  }
}
