// AUTO-GENERATED by weftc-managed/1.0.0 (dart) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/telemetry_frame.json (irVersion 1) · struct TelemetryFrame · 64 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/telemetry_frame.json --target dart
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import 'dart:ffi' as ffi;
import 'dart:typed_data';

/// Zero-copy managed projections over TelemetryFrame.
/// Canonical 64-byte payload schema used across all managed backends for parity fixtures. Designed as the payload of a triad-1 envelope (bind at envelope.headerSize). Every numeric field is naturally aligned; all values in golden fixtures are exactly representable (dyadic) so cross-language comparisons are bit-exact.
///
/// Layout (little-endian):
///   0x00  u64  schemaId
///   0x08  u64  timestampNs
///   0x10  f32[3]  velocity
///   0x1c  f32  pressurePa
///   0x20  u8  state
///   0x21  u8[3]  reserved
///   0x28  f64[2]  gpsCoordinates
///   0x38  u8[8]  payloadHash
///
/// Steady-state reads and writes allocate nothing (Law 1): create the
/// view once, then bind() for every frame. Every multi-byte access
/// passes Endian.little explicitly (Law 2).

/// dart:ffi projection for native memory (offset-order declaration;
/// the IR's natural alignment guarantees an identical layout).
final class TelemetryFrameFfi extends ffi.Struct {
  /// @byteOffset 0 (u64)
  external ffi.Uint64 schema_id;
  /// @byteOffset 8 (u64)
  external ffi.Uint64 timestamp_ns;
  /// @byteOffset 16 (f32[3])
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> velocity;
  /// @byteOffset 28 (f32)
  external ffi.Float pressure_pa;
  /// @byteOffset 32 (u8)
  external ffi.UnsignedChar state;
  /// @byteOffset 33 (u8[3])
  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedChar> reserved;
  /// @byteOffset 40 (f64[2])
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Double> gps_coordinates;
  /// @byteOffset 56 (u8[8])
  @ffi.Array.multi([8])
  external ffi.Array<ffi.UnsignedChar> payload_hash;
}

/// High-level zero-copy view over a ByteData window (Flutter hot path).
class TelemetryFrame {
  static const int byteLength = 64;
  static const int schemaId = 0x8F4C1120A9B30012;
  static const int schemaVersion = 3;
  /// @byteOffset 0 (u64)
  static const int schemaIdOffset = 0;
  /// @byteOffset 8 (u64)
  static const int timestampNsOffset = 8;
  /// @byteOffset 16 (f32[3])
  static const int velocityOffset = 16;
  /// @byteOffset 28 (f32)
  static const int pressurePaOffset = 28;
  /// @byteOffset 32 (u8)
  static const int stateOffset = 32;
  /// @byteOffset 33 (u8[3])
  static const int reservedOffset = 33;
  /// @byteOffset 40 (f64[2])
  static const int gpsCoordinatesOffset = 40;
  /// @byteOffset 56 (u8[8])
  static const int payloadHashOffset = 56;

  ByteData? _bd;
  int _offset = 0;

  /// True once bound.
  bool get isBound => _bd != null;

  /// Absolute offset within the bound ByteData.
  int get byteOffset => _offset;

  /// COLD PATH — rebinds this instance in place (zero copy).
  TelemetryFrame bind(ByteData bd, [int byteOffset = 0]) {
    if (byteOffset < 0 || byteOffset + byteLength > bd.lengthInBytes) {
      throw RangeError('TelemetryFrame.bind: window [$byteOffset..${byteOffset + byteLength}) exceeds ${bd.lengthInBytes} bytes');
    }
    _bd = bd;
    _offset = byteOffset;
    return this;
  }

  /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
  bool validateHeader([int? avail]) {
    final bd = _bd;
    if (bd == null) { return false; }
    if (bd.getUint64(_offset + 0, Endian.little) != ((0x8F4C1120 << 32) | 0xA9B30012)) { return false; }
    return true;
  }

  /// Payload schema handshake; checked by validateHeader() before any field read (Law 4).
  /// @byteOffset 0x00 (u64)
  int get schemaId {
    final bd = _bd!;
    return bd.getUint64(_offset + 0, Endian.little);
  }

  /// Low 32 bits of schemaId @0x0 — primitive-only path.
  int get schemaIdLo => _bd!.getUint32(_offset + 0, Endian.little);
  /// High 32 bits of schemaId @0x4.
  int get schemaIdHi => _bd!.getUint32(_offset + 4, Endian.little);

  /// Monotonic hardware timestamp, nanoseconds.
  /// @byteOffset 0x08 (u64)
  int get timestampNs {
    final bd = _bd!;
    return bd.getUint64(_offset + 8, Endian.little);
  }

  set timestampNs(int value) {
    final bd = _bd!;
    bd.setUint64(_offset + 8, value, Endian.little);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  TelemetryFrame withTimestampNs(int value) {
    timestampNs = value;
    return this;
  }

  /// Low 32 bits of timestampNs @0x8 — primitive-only path.
  int get timestampNsLo => _bd!.getUint32(_offset + 8, Endian.little);
  /// High 32 bits of timestampNs @0xc.
  int get timestampNsHi => _bd!.getUint32(_offset + 12, Endian.little);
  set timestampNsLo(int value) => _bd!.setUint32(_offset + 8, value, Endian.little);
  set timestampNsHi(int value) => _bd!.setUint32(_offset + 12, value, Endian.little);
  TelemetryFrame withTimestampNsLo(int value) { timestampNsLo = value; return this; }
  TelemetryFrame withTimestampNsHi(int value) { timestampNsHi = value; return this; }

  /// Velocity vector, m/s. Maps to SIMD3<Float> / vector_float3 on Apple platforms.
  /// @byteOffset 0x10 (f32[3])
  double getVelocityAt(int index) {
    final bd = _bd!;
    return bd.getFloat32(_offset + 16 + index * 4, Endian.little);
  }

  void setVelocityAt(int index, double value) {
    final bd = _bd!;
    bd.setFloat32(_offset + 16 + index * 4, value, Endian.little);
  }
  TelemetryFrame withVelocityAt(int index, double value) {
    setVelocityAt(index, value);
    return this;
  }

  /// Ambient pressure, Pa.
  /// @byteOffset 0x1c (f32)
  double get pressurePa {
    final bd = _bd!;
    return bd.getFloat32(_offset + 28, Endian.little);
  }

  set pressurePa(double value) {
    final bd = _bd!;
    bd.setFloat32(_offset + 28, value, Endian.little);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  TelemetryFrame withPressurePa(double value) {
    pressurePa = value;
    return this;
  }

  /// Device state enum byte.
  /// @byteOffset 0x20 (u8)
  int get state {
    final bd = _bd!;
    return bd.getUint8(_offset + 32);
  }

  set state(int value) {
    final bd = _bd!;
    bd.setUint8(_offset + 32value);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  TelemetryFrame withState(int value) {
    state = value;
    return this;
  }

  /// lat/lon pair, degrees.
  /// @byteOffset 0x28 (f64[2])
  double getGpsCoordinatesAt(int index) {
    final bd = _bd!;
    return bd.getFloat64(_offset + 40 + index * 8, Endian.little);
  }

  void setGpsCoordinatesAt(int index, double value) {
    final bd = _bd!;
    bd.setFloat64(_offset + 40 + index * 8, value, Endian.little);
  }
  TelemetryFrame withGpsCoordinatesAt(int index, double value) {
    setGpsCoordinatesAt(index, value);
    return this;
  }

  /// Truncated payload digest (u8[8]).
  /// @byteOffset 0x38 (u8[8])
  int getPayloadHashAt(int index) {
    final bd = _bd!;
    return bd.getUint8(_offset + 56 + index * 1);
  }

  void setPayloadHashAt(int index, int value) {
    final bd = _bd!;
    bd.setUint8(_offset + 56 + index * 1, value);
  }
  TelemetryFrame withPayloadHashAt(int index, int value) {
    setPayloadHashAt(index, value);
    return this;
  }
}
