// AUTO-GENERATED by weftc-managed/1.0.0 (dart) — DO NOT EDIT.
// Source IR: tools/weftc/schema/fixtures/weft_envelope.json (irVersion 1) · struct WeftEnvelope · 16 B · little-endian
// Regenerate: node tools/weftc/weftc.mjs --ir tools/weftc/schema/fixtures/weft_envelope.json --target dart
// Layout is normative; hand edits will be overwritten and drift will fail CI.


import 'dart:ffi' as ffi;
import 'dart:typed_data';

/// Zero-copy managed projections over WeftEnvelope.
/// The triad-1 wire envelope per docs 03-ENVELOPE and core/c/weft.h. Byte-layout and validation semantics are normative: [0..4) magic 'WEFT', [4..6) version u16, [6..8) header_size u16, [8..12) seq u32, [12..16) payload_len u32. validateHeader() mirrors weft_envelope_decode() as a non-throwing boolean handshake (Law 4).
///
/// Layout (little-endian):
///   0x00  u8[4]  magic
///   0x04  u16  version
///   0x06  u16  headerSize
///   0x08  u32  seq
///   0x0c  u32  payloadLen
///
/// Steady-state reads and writes allocate nothing (Law 1): create the
/// view once, then bind() for every frame. Every multi-byte access
/// passes Endian.little explicitly (Law 2).

/// dart:ffi projection for native memory (offset-order declaration;
/// the IR's natural alignment guarantees an identical layout).
final class WeftEnvelopeFfi extends ffi.Struct {
  /// @byteOffset 0 (u8[4])
  @ffi.Array.multi([4])
  external ffi.Array<ffi.UnsignedChar> magic;
  /// @byteOffset 4 (u16)
  external ffi.UnsignedShort version;
  /// @byteOffset 6 (u16)
  external ffi.UnsignedShort header_size;
  /// @byteOffset 8 (u32)
  external ffi.UnsignedInt seq;
  /// @byteOffset 12 (u32)
  external ffi.UnsignedInt payload_len;
}

/// High-level zero-copy view over a ByteData window (Flutter hot path).
class WeftEnvelope {
  static const int byteLength = 16;
  static const int schemaVersion = 1;
  /// Normative triad-1 minimum header size (03-ENVELOPE §2).
  static const int minHeaderSize = 16;
  /// @byteOffset 0 (u8[4])
  static const int magicOffset = 0;
  /// @byteOffset 4 (u16)
  static const int versionOffset = 4;
  /// @byteOffset 6 (u16)
  static const int headerSizeOffset = 6;
  /// @byteOffset 8 (u32)
  static const int seqOffset = 8;
  /// @byteOffset 12 (u32)
  static const int payloadLenOffset = 12;

  ByteData? _bd;
  int _offset = 0;

  /// True once bound.
  bool get isBound => _bd != null;

  /// Absolute offset within the bound ByteData.
  int get byteOffset => _offset;

  /// COLD PATH — rebinds this instance in place (zero copy).
  WeftEnvelope bind(ByteData bd, [int byteOffset = 0]) {
    if (byteOffset < 0 || byteOffset + byteLength > bd.lengthInBytes) {
      throw RangeError('WeftEnvelope.bind: window [$byteOffset..${byteOffset + byteLength}) exceeds ${bd.lengthInBytes} bytes');
    }
    _bd = bd;
    _offset = byteOffset;
    return this;
  }

  /// Law 4 handshake — non-throwing; mirrors weft_envelope_decode().
  bool validateHeader([int? avail]) {
    final bd = _bd;
    if (bd == null) { return false; }
    if (bd.getUint8(_offset + 0) != 87) { return false; } // "W"
    if (bd.getUint8(_offset + 1) != 69) { return false; } // "E"
    if (bd.getUint8(_offset + 2) != 70) { return false; } // "F"
    if (bd.getUint8(_offset + 3) != 84) { return false; } // "T"
    if (bd.getUint16(_offset + 4, Endian.little) != 1) { return false; }
    if (bd.getUint16(_offset + 6, Endian.little) != 16) { return false; }
    if (avail != null) {
      final hs = bd.getUint16(_offset + 6, Endian.little);
      final pl = bd.getUint32(_offset + 12, Endian.little);
      if (hs < minHeaderSize || hs > avail) { return false; }
      if (pl > avail - hs) { return false; } // payload bytes must exist (kernel SHORT)
    }
    return true;
  }

  /// ASCII 'WEFT' frame magic.
  /// @byteOffset 0x00 (u8[4])
  int getMagicAt(int index) {
    final bd = _bd!;
    return bd.getUint8(_offset + 0 + index * 1);
  }

  /// Envelope wire version (triad-1 = 1).
  /// @byteOffset 0x04 (u16)
  int get version {
    final bd = _bd!;
    return bd.getUint16(_offset + 4, Endian.little);
  }

  /// Total header size; payload begins at this offset, NEVER at 16 (L8b extensible headers).
  /// @byteOffset 0x06 (u16)
  int get headerSize {
    final bd = _bd!;
    return bd.getUint16(_offset + 6, Endian.little);
  }

  /// Monotonic frame sequence number; mirrors the buffer canary.
  /// @byteOffset 0x08 (u32)
  int get seq {
    final bd = _bd!;
    return bd.getUint32(_offset + 8, Endian.little);
  }

  set seq(int value) {
    final bd = _bd!;
    bd.setUint32(_offset + 8, value, Endian.little);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  WeftEnvelope withSeq(int value) {
    seq = value;
    return this;
  }

  /// Payload byte length starting at headerSize.
  /// @byteOffset 0x0c (u32)
  int get payloadLen {
    final bd = _bd!;
    return bd.getUint32(_offset + 12, Endian.little);
  }

  set payloadLen(int value) {
    final bd = _bd!;
    bd.setUint32(_offset + 12, value, Endian.little);
  }

  /// Fluent mutator — returns this, allocates nothing (Law 1).
  WeftEnvelope withPayloadLen(int value) {
    payloadLen = value;
    return this;
  }
}
