// emitter.mjs — deterministic output assembly.
//
// EVERY backend funnels its files through here. Determinism rules:
//   - no clocks, no randomness, no map-iteration-order dependence
//   - a fixed banner naming the source IR and regeneration command
//   - files are produced as a sorted { path -> content } map
// The codegen determinism CI gate re-runs generation and byte-compares —
// any nondeterminism fails the build.

import { camel } from './names.mjs';

/**
 * @param {object} opts
 * @param {string} opts.generator  e.g. "weftc-managed/1.0.0"
 * @param {string} opts.irPath     path of the source IR document
 * @param {object} opts.ir         normalized IR struct (from loadIr)
 * @param {string} opts.target     ts|swift|dart|python
 * @returns {string} banner line block (terminated by blank line)
 */
export function banner({ generator, irPath, ir, target }) {
  const parts = [
    `// AUTO-GENERATED by ${generator} (${target}) — DO NOT EDIT.`,
    `// Source IR: ${irPath} (irVersion 1) · struct ${ir.name} · ${ir.byteLength} B · ${ir.endian}-endian`,
    `// Regenerate: node tools/weftc/weftc.mjs --ir ${irPath} --target ${target}`,
    `// Layout is normative; hand edits will be overwritten and drift will fail CI.`,
  ];
  return parts.join('\n') + '\n\n';
}

/** Doc-comment renderer: `doc` IR text -> language comment lines. */
export function docComment(text, prefix) {
  if (!text) return [];
  return text.split('\n').map((line) => `${prefix}${line}`);
}

/**
 * @param {object} ir normalized IR
 * @returns {string[]} hot-path getter/setter JS property names, used by the
 *   static allocation-site scanner in tests (Law 1 gate).
 */
export function hotPathMembers(ir) {
  const out = [];
  for (const f of ir.fields) {
    if (f.role === 'reserved') continue;
    out.push(camel(f.name));
  }
  return out;
}
